/** Run locked upstream PostgreSQL queries and native SQLite rules against the same fixture. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,join} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';
import {at,seedPostgres,seedSqlite,stories} from '../../tests/golden/fixture.mjs';import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';
const workspace=resolve(import.meta.dirname,'../..');const upstream=process.argv[2]??process.env.AIHOT_SOURCE;
if(!upstream)throw new Error('Provide the pinned AIHOT checkout as argv[2] or AIHOT_SOURCE');
process.env.DATABASE_URL='postgres://hotstream_test:HOTSTREAM_LOCAL_NON_SECRET_FIXTURE@127.0.0.1:55432/hotstream_reference';process.env.MODEL_CALLS_ENABLED='false';process.env.COLLECT_ENABLED='false';process.env.FEISHU_CONTENT_PUSH_ENABLED='false';process.env.AIHOT_CREDENTIALS_DIR=join(workspace,'artifacts/reference/no-credentials');
const url=path=>pathToFileURL(resolve(upstream,path)).href;const {sql,closeDb}=await import(url('packages/backend/src/db.ts'));const hot=await import(url('packages/backend/src/events/hot.ts'));const edition=await import(url('packages/backend/src/reports/edition.ts'));const composition=await import(url('packages/backend/src/reports/compose.ts'));
const db=new DatabaseSync(':memory:');const store=new HotstreamDatabase(db);const records={target:'AIHOT cc66cceb / DSH 0.2.0-rc.2',at:new Date(at).toISOString(),results:{}};
try{
 await seedPostgres(sql);seedSqlite(db);
 await hot.computeHotRanking(new Date(at));const pgHot=(await hot.storedHotRanking()).entries;const nativeHot=store.execute('heat',{epoch:0,now:at,compute:true});
 const normalizePg=entries=>entries.map(entry=>({story:stories.find(story=>story.pg===entry.storyId).id,title:entry.title,heat:entry.heat,trend:entry.trend,trendPct:entry.trendPct,badges:entry.badges,participants:entry.participantCount,editorial:entry.sourceCount,signal:entry.signalCount,representative:entry.representativeItemId,sourceNames:entry.sourceNames}));
 const normalizedNative=nativeHot.map(entry=>({story:entry.storyId,title:entry.title,heat:entry.heat,trend:entry.trend,trendPct:entry.trendPct,badges:entry.badges,participants:entry.participants,editorial:entry.editorialParticipants,signal:entry.signalCount,representative:entry.representativeItemId,sourceNames:entry.sourceNames}));
 records.results.heat={upstream:normalizePg(pgHot),native:normalizedNative};assert.deepEqual(normalizedNative,normalizePg(pgHot));records.results.heat.pass=true;
 const pgDaily=await edition.dailyEdition('2026-10-04',new Date(at-86400000),new Date(at));const nativeDaily=store.execute('dailyEdition',{date:'2026-10-04',start:at-86400000,end:at});
 const normalizeEdition=entries=>entries.map(entry=>({id:entry.entry.itemId,title:entry.entry.title,related:(entry.entry.related??[]).map(item=>item.itemId),sources:entry.entry.sources,authority:entry.authority,importance:entry.importance,mentions:[...entry.mentions].map(id=>typeof id==='number'?stories.find(story=>story.pg===id)?.id??id:id),fillIn:entry.entry.fillIn??false,previous:entry.previous}));
 records.results.daily={upstream:normalizeEdition(pgDaily.entries),native:normalizeEdition(nativeDaily.entries),upstreamStats:pgDaily.stats,nativeStats:nativeDaily.stats};assert.deepEqual(normalizeEdition(nativeDaily.entries),normalizeEdition(pgDaily.entries));assert.deepEqual(nativeDaily.stats,pgDaily.stats);records.results.daily.pass=true;
 await composition.composeDaily('2026-10-04');const [saved]=await sql`SELECT content FROM reports WHERE kind='daily' AND key='2026-10-04'`;
 db.prepare('INSERT INTO reports VALUES(?,?,?,?,?,?,?,?,?,?)').run('fixture-daily','daily','2026-10-04','Asia/Shanghai',at-86400000,at,at,1,'model',JSON.stringify(saved.content));
 const pgPeriod=await edition.periodEntries('2026-10-01','2026-10-04');const nativePeriod=store.execute('periodEntries',{startDate:'2026-10-01',endDate:'2026-10-04',now:at});const normalizePeriod=result=>({issues:result.issues,entries:result.entries.map(entry=>({id:entry.itemId,title:entry.title,score:entry.score,role:entry.role,source:entry.sourceId}))});records.results.period={upstream:normalizePeriod(pgPeriod),native:normalizePeriod(nativePeriod)};assert.deepEqual(normalizePeriod(nativePeriod),normalizePeriod(pgPeriod));records.results.period.pass=true;
}catch(error){records.error=error.stack;process.exitCode=1;}finally{await closeDb();db.close();const out=join(workspace,'artifacts/reference/compare.json');await mkdir(resolve(out,'..'),{recursive:true});await writeFile(out,JSON.stringify(records,null,2)+'\n');console.log(JSON.stringify({evidence:out,passed:Object.entries(records.results).filter(([,value])=>value.pass).map(([name])=>name),error:records.error?.slice(0,180)},null,2));}
