/** Fixed input differential against the pinned original method and PostgreSQL monitor reducer. */
import{DatabaseSync}from'node:sqlite';import assert from'node:assert/strict';import{writeFile}from'node:fs/promises';import{resolve,join}from'node:path';import{pathToFileURL}from'node:url';import{randomUUID}from'node:crypto';
import{HotstreamDatabase}from'../../packages/storage-sqlite/lib/types/database.js';import{LeaderboardComputer}from'../../packages/host/lib/index.js';import{defaultSettings}from'../../packages/contracts/lib/types/runtime.js';import{leaderboardInput}from'../../tests/golden/leaderboard-fixture.mjs';
const upstream=process.argv[2]??process.env.AIHOT_SOURCE,url=p=>pathToFileURL(resolve(upstream,p)).href;
if(!upstream)throw new Error('Provide the pinned AIHOT checkout as argv[2] or AIHOT_SOURCE');
process.env.DATABASE_URL='postgres://hotstream_test:HOTSTREAM_LOCAL_NON_SECRET_FIXTURE@127.0.0.1:55432/hotstream_reference';process.env.MODEL_CALLS_ENABLED='false';process.env.COLLECT_ENABLED='false';process.env.FEISHU_CONTENT_PUSH_ENABLED='false';process.env.AIHOT_CREDENTIALS_DIR=resolve('artifacts/reference/no-credentials');
const original=await import(url('packages/backend/src/leaderboard/method/consensus.ts'));const{sql,closeDb}=await import(url('packages/backend/src/db.ts'));const monitor=await import(url('packages/backend/src/monitor/assemble.ts'));const db=new DatabaseSync(':memory:'),store=new HotstreamDatabase(db),computer=new LeaderboardComputer(new AbortController().signal);const records={version:'AIHOT cc66cceb / DSH 0.2.0-rc.2',simulated:true,modelsDispatched:0,results:{}};
try{
 const input=leaderboardInput();const upstreamBoard=await original.computeBoard(input),[nativeBoard]=await computer.run([input]);assert.deepEqual(nativeBoard,upstreamBoard);records.results.leaderboard={pass:true,input,upstream:upstreamBoard,native:nativeBoard};
 const now=Date.parse('2026-10-04T00:00:00Z');const settings=defaultSettings({provider:'mock',model:'fixture'}),state=store.execute('initialize',{commandId:randomUUID(),settings,sources:[{createdAt:null,id:'fixture',name:'模拟监控',kind:'external',config:{},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'isolated',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null}],now});
 await sql`TRUNCATE monitor_event_posts,monitor_events,monitor_posts,monitor_state CASCADE`;
 const steps=[['8999','Codex is down.',null,false,'outage'],['9001','We will reset everyone in the next hour.','announce',false],['9002','Reset is still propagating.','progress',false],['9005','Codex has recovered.',null,false,'recovery'],['9003','All reset for everyone.','confirm',false],['9004','We may reset later.','announce',true]];const states=[];
 for(const[index,[id,text,action,needsReview,outage=null]]of steps.entries()){const at=now+index*1000,rec={relevant:true,translationZh:null,contextZh:[],outage,needsReview,propositions:action?[{kind:'direct_reset',kindExplicit:true,action,real:true,count:1,relatesTo:null,excerpt:text,excerptZh:text,statedTime:id==='9001'?{precision:'deadline',relativeHours:1,period:null,clock:null,clockThrough:null,dayOffset:null}:null,timeInferred:false,expectedLanding:null,scope:{audienceSource:'everyone',plans:null,audienceZh:'所有用户',productsZh:'Codex'}}]:[]};
  await sql`INSERT INTO monitor_posts(id,author,published_at,text,url,context,raw) VALUES(${id},'thsottiaux',${new Date(at)},${text},${'https://example.com/'+id},'[]','{}')`;await monitor.applyRecognition(id,{...rec,model:'fixture',promptVersion:'fixture',receiptId:0});
  store.execute('monitorPosts',{epoch:state.epoch,posts:[{id,author:'thsottiaux',publishedAt:at,text,url:'https://example.com/'+id,context:[],raw:{}}],cursor:{},receiptIds:[],now:at});const receipt=store.execute('reserve',{key:id,service:'llm',epoch:state.epoch,requestHash:'f'.repeat(64),request:{simulated:true},now:at}).receipt;store.execute('sent',{id:receipt.id,epoch:state.epoch,auditRef:'simulation',now:at});store.execute('receive',{id:receipt.id,epoch:state.epoch,response:{simulated:true},usage:{},now:at});store.execute('monitorApply',{epoch:state.epoch,postId:id,recognition:rec,receiptId:receipt.id,now:at});
  const pg=(await sql`SELECT type,status,withdrawn,confirmed_at,schedule,estimate FROM monitor_events ORDER BY created_at`).map(r=>({kind:r.type,status:r.status,withdrawn:r.withdrawn,confirmedAt:r.confirmed_at?.getTime()??null,schedule:r.schedule,estimate:r.estimate}));const native=store.execute('optionalData',{module:'monitor',limit:100,offset:0}).records.map(r=>({kind:r.kind,status:r.status,withdrawn:r.withdrawn,confirmedAt:r.confirmedAt,schedule:r.schedule,estimate:r.estimate}));assert.deepEqual(native,pg);const pgOutages=(await sql`SELECT text,outage FROM monitor_posts WHERE outage IS NOT NULL ORDER BY published_at`).map(r=>({text:r.text,recoveredAt:r.outage.recoveredAt,resetLinked:!!r.outage.resetEventId}));const nativeOutages=store.execute('optionalData',{module:'monitor',limit:100,offset:0}).state.outages.map(r=>({text:r.text,recoveredAt:r.recoveredAt,resetLinked:!!r.resetEventId}));assert.deepEqual(nativeOutages,pgOutages);states.push({id,upstream:pg,native,outages:{upstream:pgOutages,native:nativeOutages}});
 }records.results.monitor={pass:true,states};
 await writeFile('tests/golden/optional-expected.json',JSON.stringify({leaderboard:upstreamBoard,monitor:states.map(s=>s.upstream)},null,2));
}catch(error){records.error=error.stack;process.exitCode=1;}finally{await computer.close();db.close();await closeDb();await writeFile('artifacts/reference/optional-compare.json',JSON.stringify(records,null,2));console.log(JSON.stringify({passed:Object.keys(records.results),error:records.error?.slice(0,400)},null,2));}
