/** Repository-neutral port of AIHOT method/inputs: latest evidence, seven-day carry, frozen scales. */
import {SCORING_SOURCES,OVERALL_POLICY,categoryPolicy,ANCHORS,buildCalibration,RELEASE_WINDOW_MONTHS,type BoardInput,type SignalRow,type RegistryEntry,type Calibration} from 'dsh-hotstream-core/leaderboard/method/consensus';
import {qualifyModels} from 'dsh-hotstream-core/leaderboard/method/qualification';
import {CALIBRATION_METHOD_VERSION} from 'dsh-hotstream-core/leaderboard/method/calibration';
import {protocolOf} from 'dsh-hotstream-core/leaderboard/protocol';
import {admissionOf} from './fetch/admission.ts';
import {cloakedModel} from 'dsh-hotstream-core/leaderboard/identity';
import type {HotstreamStore,Json,RuntimeSettings} from 'dsh-hotstream-contracts/runtime';
export async function buildInputs(store:HotstreamStore,epoch:number,now:number,configuration:RuntimeSettings['leaderboard']={arenaProxyUrl:null,sources:{},excludedModels:[],aliases:{}}):Promise<{boards:BoardInput[];snapshotIds:string[];evidence:Record<string,Json>;exclusions:Record<string,Json>}>{
 const history=await store.execute('lbHistory',{now});const snapshots=history.snapshots;const latest=new Map(snapshots.filter(s=>s.latest===true).map(s=>[String(s.source_key),s]));
 const bySnapshot=new Map(snapshots.map(s=>[String(s.id),s]));const sourceOf=new Map(SCORING_SOURCES.map(s=>[s.unit,s]));
 const unitRows=new Map<string,Map<string,SignalRow>>();const names=new Map<string,string>(),released=new Map<string,Date|null>();const evidence:Record<string,Json>={},exclusions:Record<string,Json>={};const present=new Set<string>();
 const scores=[...history.rows].sort((a,b)=>Number(bySnapshot.get(String(b.snapshot_id))?.fetched_at??0)-Number(bySnapshot.get(String(a.snapshot_id))?.fetched_at??0));
 for(const row of scores){const snapshot=bySnapshot.get(String(row.snapshot_id));if(!snapshot)continue;const sourceKey=String(snapshot.source_key);if((configuration.sources[sourceKey]??configuration.sources['*'])===false||configuration.excludedModels.includes(String(row.slug))){exclusions[sourceKey+':'+String(row.metric_key)+':'+String(row.slug)]=(configuration.sources[sourceKey]??configuration.sources['*'])===false?'Source disabled by saved configuration':'Model excluded by saved configuration';continue;}const current=latest.get(sourceKey);if(!current)continue;const snapshotMeta=snapshot.metadata as Record<string,Json>,currentMeta=current.metadata as Record<string,Json>;if(protocolOf(sourceKey,snapshotMeta)!==protocolOf(sourceKey,currentMeta))continue;const identity=sourceKey+':'+String(row.metric_key)+':'+String(row.slug);if(present.has(identity))continue;present.add(identity);
  const document=row.document as Record<string,Json>;if(row.selected_for_product!==1||row.raw_score===null||cloakedModel(String(row.slug),String(row.name)))continue;const meta={...snapshotMeta,...document.metadata as object};const admission=admissionOf(sourceKey,{sourceModelName:String(document.sourceModelName??row.name),configurationKey:String(row.configuration_key),metadata:meta});if(!admission.eligible){exclusions[identity]=admission.reason??'Incomparable protocol';continue;}
  const put=(unit:string,score:number,lower:number|null,upper:number|null)=>{const source=sourceOf.get(unit);if(!source)return;const rows=unitRows.get(unit)??new Map();unitRows.set(unit,rows);rows.set(String(row.slug),{score,modelSlug:String(row.slug),lowerBound:lower,upperBound:upper,configuration:String(row.configuration_key),snapshotId:String(row.snapshot_id)});names.set(String(row.slug),String(row.name));released.set(String(row.slug),row.released_at===null?null:new Date(Number(row.released_at)));evidence[unit+':'+String(row.slug)]={unit,operator:source.operator,protocol:protocolOf(sourceKey,snapshotMeta),snapshotId:String(row.snapshot_id),verifiedAt:String(snapshotMeta.lastSeenAt??new Date(Number(snapshot.fetched_at)).toISOString()),evaluatedAt:typeof meta.measuredAt==='string'?meta.measuredAt:null,publishedAt:snapshot.published_at===null?null:new Date(Number(snapshot.published_at)).toISOString(),configuration:String(row.configuration_key),carriedForward:snapshot.id!==current.id};};
  if(row.metric_key==='livebench-coding'){for(const [part,field]of [['direct','Coding'],['agentic','Agentic Coding']]){const value=meta['livebenchCategoryScore:'+field];if(typeof value==='number'&&Number.isFinite(value))put('livebench-coding:'+part,value,null,null);}}
  else put(String(row.metric_key),Number(row.raw_score),typeof document.lowerBound==='number'?document.lowerBound:null,typeof document.upperBound==='number'?document.upperBound:null);
 }
 const calibrations=new Map<string,Calibration>();for(const source of SCORING_SOURCES.filter(s=>s.scoring)){
  const current=latest.get(source.key);const protocol=protocolOf(source.key,current?.metadata as Record<string,Json>??{});const prior=history.calibrations.find(c=>c.unit===source.unit&&c.protocol===protocol&&c.version===CALIBRATION_METHOD_VERSION);
  const calibration=(prior?.calibration as unknown as Calibration|undefined)??buildCalibration(protocol,[...unitRows.get(source.unit)?.values()??[]]);if(calibration){calibrations.set(source.unit,calibration);if(!prior)await store.execute('lbCalibration',{epoch,unit:source.unit,protocol,calibration:JSON.parse(JSON.stringify(calibration)) as Record<string,Json>,now});}
 }
 const cutoff=new Date(now);cutoff.setUTCMonth(cutoff.getUTCMonth()-RELEASE_WINDOW_MONTHS);const boards:BoardInput[]=[];
 for(const board of ['overall','coding','reasoning','knowledge','professional']){const members=board==='overall'?SCORING_SOURCES:SCORING_SOURCES.filter(s=>s.category===board);const budget=members.reduce((sum,s)=>sum+s.weight,0);const active=members.filter(s=>s.scoring&&calibrations.has(s.unit)&&(unitRows.get(s.unit)?.size??0)>0);if(!active.length)continue;const registry:Record<string,RegistryEntry>={};for(const source of active)registry[source.unit]={sourceKey:source.key,family:source.family,budget:source.budget,calibration:calibrations.get(source.unit)!,weight:board==='overall'?source.weight:source.weight/budget,operator:source.operator,protocol:protocolOf(source.key,latest.get(source.key)?.metadata as Record<string,Json>??{}),direction:source.direction,interval_sd:source.intervalSd};const units=active.map(s=>s.unit);const policy=board==='overall'?OVERALL_POLICY:categoryPolicy(units.length,new Set(active.map(s=>s.operator)).size);const models=qualifyModels(units,registry,unitRows,policy,released,cutoff);if(!models.length)continue;const included=new Set(models);boards.push({board,names:Object.fromEntries(models.map(id=>[id,names.get(id)??id])),models,policy,anchors:ANCHORS,registry,signals:units.map(unit=>({key:unit,rows:[...unitRows.get(unit)!.values()].filter(r=>included.has(r.modelSlug)).sort((a,b)=>a.modelSlug.localeCompare(b.modelSlug))}))});}
 return {boards,snapshotIds:[...latest.values()].map(s=>String(s.id)),evidence,exclusions};
}
