import {useCallback,useEffect,useRef,useState} from 'react';
import {Checkbox} from '@deepseek-ai/dsh-client-ui-primitives';
import {settingsSchema,type RuntimeSettings} from 'dsh-hotstream-contracts/runtime';
import {createSettingsDraft} from '../settings-draft.ts';
import {Modal,Button,Field,NumberField,Choice,ModelRoute,BudgetForm,ToggleRow,Section} from './Controls.tsx';
import {Integrations} from './Integrations.tsx';
import {translator,type AdminProps,type CredentialDraftActions,type RegisterCredentialDraft} from './types.ts';
import styles from './Admin.module.css';

export function SettingsPage({state,face}:AdminProps){
  const tr=translator(face),runtime=state.runtime!.state;
  const editor=state.settingsDraft??createSettingsDraft(runtime.settings!,runtime.revision),draft=editor.value;
  const [advanced,setAdvanced]=useState(JSON.stringify(draft,null,2)),[advancedDirty,setAdvancedDirty]=useState(false),[advancedError,setAdvancedError]=useState('');
  const [promptKey,setPromptKey]=useState('prefilter'),[confirmation,setConfirmation]=useState(''),[secretDirty,setSecretDirty]=useState(false),[savingAll,setSavingAll]=useState(false),[savedLocally,setSavedLocally]=useState(false);
  const [clearAck,setClearAck]=useState(false),[clearPhrase,setClearPhrase]=useState('');
  const credentialDrafts=useRef(new Map<string,CredentialDraftActions>());
  const onSecretChange=useCallback(()=>{setSecretDirty([...credentialDrafts.current.values()].some(action=>action.isDirty()));setSavedLocally(false);},[]);
  const registerCredentialDraft=useCallback<RegisterCredentialDraft>((id,actions)=>{credentialDrafts.current.set(id,actions);return()=>{if(credentialDrafts.current.get(id)===actions)credentialDrafts.current.delete(id);};},[]);
  const saving=editor.status==='saving'||savingAll,dirty=editor.dirty||secretDirty||advancedDirty;
  const dirtyRef=useRef(dirty);dirtyRef.current=dirty;
  const applyAdvanced=()=>{try{face.editSettings(settingsSchema.parse(JSON.parse(advanced)));setAdvancedDirty(false);setAdvancedError('');return true;}catch{setAdvancedError(tr('高级配置不是有效的设置，请修正后再保存。','Advanced JSON is not valid settings. Correct it before saving.'));return false;}};
  const save=async()=>{
    if(saving)return false;if(advancedDirty&&!applyAdvanced())return false;
    setSavingAll(true);try{
      for(const actions of credentialDrafts.current.values())if(actions.isDirty()&&!await actions.save())return false;
      const success=await face.saveSettings();if(success)setSavedLocally(true);return success;
    }finally{setSavingAll(false);}
  };
  const saveRef=useRef(save);saveRef.current=save;
  const discard=()=>{face.resetSettingsDraft();for(const actions of credentialDrafts.current.values())actions.discard();setAdvancedDirty(false);setAdvancedError('');setSavedLocally(false);};
  const discardRef=useRef(discard);discardRef.current=discard;
  useEffect(()=>face.registerFormGuard({title:tr('设置','Settings'),isDirty:()=>dirtyRef.current,save:()=>saveRef.current(),discard:()=>discardRef.current()}),[face.registerFormGuard]);
  useEffect(()=>{if(!advancedDirty)setAdvanced(JSON.stringify(draft,null,2));},[draft,advancedDirty]);
  useEffect(()=>{if(!dirty)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
  const change=(patch:Partial<RuntimeSettings>)=>{setSavedLocally(false);face.editSettings(patch);};
  const status=saving?'saving':editor.status==='error'||advancedError?'error':dirty?'dirty':savedLocally||editor.status==='saved'?'saved':'clean';
  const statusLabel=({saving:tr('保存中…','Saving…'),error:tr('保存失败','Save failed'),dirty:tr('有未保存更改','Unsaved changes'),saved:tr('已保存','Saved'),clean:tr('与已保存配置一致','Up to date')})[status];
  const saveButton=(label:string)=><Button type="submit" form="hotstream-settings-form" disabled={!dirty||saving} aria-label={label}>{tr(saving?'保存中…':'保存更改',saving?'Saving…':'Save changes')}</Button>;
  return <>
    <header className={styles.pageHeader}><div><h1>{face.t('settingsPage')}</h1><p>{tr('修改后统一保存。保存成功会回读配置，切换页面或重启后继续生效。','Changes take effect after saving. Saved settings are verified and persist across navigation and restarts.')}</p></div><div className={styles.pageActions}><span className={styles.status} data-state={status} role="status">{statusLabel}</span>{saveButton(tr('保存设置：顶部','Save settings: top'))}</div></header>
    <nav className={styles.tabs} aria-label={tr('设置分组','Settings sections')}>{[['running',tr('运行','Running')],['models',tr('模型','Models')],['budgets',tr('预算与网络','Budgets and network')],['integrations',tr('第三方接入','Integrations')],['modules',tr('可选模块','Modules')],['retention',tr('数据保留','Retention')],['advanced',tr('高级','Advanced')]].map(([id,label])=><a key={id} href={`#settings-${id}`}>{label}</a>)}</nav>
    {editor.conflict&&<div role="alert" className={styles.notice}>{tr('已保存配置在编辑期间发生了变化。你的草稿已保留；请核对最新配置后再保存。','Saved settings changed while you were editing. Your draft is retained; review the latest configuration before saving.')}</div>}
    <form id="hotstream-settings-form" onSubmit={event=>{event.preventDefault();void save();}}>
      <div className={styles.sections}>
        <Section id="settings-running" title={tr('运行开关','Operation')} description={tr('开关改变的是待保存设置，点击“保存更改”后生效。','These switches update your draft. Apply them with Save changes.')}>
          <ToggleRow label={face.t('autoCollection')} description={tr('按信源计划采集新内容；暂停后保留已有内容。','Collect new material on each source schedule. Pausing retains existing content.')} checked={draft.autoCollectEnabled} onChange={autoCollectEnabled=>change({autoCollectEnabled})} disabled={saving}/>
          <ToggleRow label={face.t('processingEnabled')} description={tr('对候选内容执行筛选、评分和编辑，使用所选模型额度。','Filter, score and edit candidates using your selected model quota.')} checked={draft.processing.enabled} onChange={enabled=>change({processing:{enabled}})} disabled={saving}/>
        </Section>
        <Section id="settings-models" title={face.t('fixedModel')} description={tr('固定使用这里选定的模型，不跟随聊天窗口的模型切换。','This model is independent from the model selected in a chat.')}>
          <ModelRoute catalog={state.catalog} face={face} provider={draft.model.provider} model={draft.model.model} disabled={saving} setProvider={provider=>change({model:{...draft.model,provider,model:state.catalog.providers.find(item=>item.id===provider)?.models[0]?.id??''}})} setModel={model=>change({model:{...draft.model,model}})}/>
          <details><summary>{face.t('stageOverrides')}</summary><div className={styles.sections}>{['prefilter','score','structure','writing','translate','group','digest','report','monitor'].map(stage=>{const route=draft.model.stageOverrides[stage];return <fieldset className={styles.budget} key={stage}><legend>{stage}</legend><ToggleRow label={`${stage} · ${face.t('overrideEnabled')}`} description={tr('关闭时沿用基础模型。','Uses the base model when disabled.')} checked={!!route} disabled={saving} onChange={enabled=>{const stageOverrides={...draft.model.stageOverrides};if(enabled)stageOverrides[stage]={provider:draft.model.provider,model:draft.model.model};else delete stageOverrides[stage];change({model:{...draft.model,stageOverrides}});}}/>{route&&<ModelRoute catalog={state.catalog} face={face} provider={route.provider} model={route.model} disabled={saving} setProvider={provider=>change({model:{...draft.model,stageOverrides:{...draft.model.stageOverrides,[stage]:{provider,model:state.catalog.providers.find(item=>item.id===provider)?.models[0]?.id??''}}}})} setModel={model=>change({model:{...draft.model,stageOverrides:{...draft.model.stageOverrides,[stage]:{...route,model}}}})}/>}</fieldset>;})}</div></details>
        </Section>
        <Section id="settings-budgets" title={tr('预算、并发与网络','Budgets, concurrency and network')} description={tr('预算按实际请求次数计量，填 0 暂停对应服务。网络模式只影响本插件。','Limits count actual requests. Zero pauses that service. Network mode affects this plugin only.')}>
          <div className={styles.grid}><BudgetForm label={face.t('modelBudget')} face={face} value={draft.budgets.llm} disabled={saving} onChange={llm=>change({budgets:{...draft.budgets,llm}})}/><BudgetForm label={face.t('paidBudget')} face={face} value={draft.budgets.paidCollectorPerService} disabled={saving} onChange={paidCollectorPerService=>change({budgets:{...draft.budgets,paidCollectorPerService}})}/></div>
          <div className={styles.grid} style={{marginTop:20}}><NumberField label={face.t('collectConcurrency')} value={draft.concurrency.collect} min={1} max={10} disabled={saving} onChange={collect=>change({concurrency:{...draft.concurrency,collect}})}/><NumberField label={face.t('modelConcurrency')} value={draft.concurrency.model} min={1} max={10} disabled={saving} onChange={model=>change({concurrency:{...draft.concurrency,model}})}/><Choice label={face.t('network')} value={draft.network.dnsMode} choices={[{id:'system',label:face.t('systemDns')},{id:'public-doh',label:face.t('publicDns')}]} disabled={saving} onChange={dnsMode=>change({network:{...draft.network,dnsMode:dnsMode as 'system'|'public-doh'}})}/></div>
          <Field label={tr('公开新闻 HTTP 代理','Public news HTTP proxy')} placeholder="http://127.0.0.1:7897" value={draft.network.publicProxyUrl??''} disabled={saving} onChange={value=>change({network:{...draft.network,publicProxyUrl:value.trim()||null}})}/>
          <p className={styles.muted}>{tr('用于 RSS、公开网页正文、图片，以及 Terminal Bench 4 官方仓库的匿名读取。留空时按上方 DNS 模式直连；带凭据的 API 和 DSH 模型保持原有连接方式。','Used for RSS, public article bodies, images, and anonymous reads of the official Terminal Bench 4 repository. Leave blank for direct access with the selected DNS mode. Authenticated APIs and DSH model connections keep their existing route.')}</p>
          <p className={styles.muted}>{tr('公共 DNS 需要能访问其 HTTPS 服务。来源诊断若显示解析超时，可以选择系统 DNS，保存后再更新对应模块。','Public DNS needs a reachable HTTPS resolver. If diagnostics report DNS timeouts, select system DNS, save, then refresh the affected module.')}</p>
        </Section>
        <Integrations state={state} face={face} registerDraft={registerCredentialDraft} onDraftChange={onSecretChange}/>
        <Section id="settings-modules" title={face.t('features')} description={tr('启用与接入状态分别展示；单次测试不会开启周期监控。','Enabled state and connection status are separate. A one-time test never enables periodic monitoring.')}>
          <ToggleRow label={face.t('leaderboardPage')} description={tr('定期更新公开评测来源，保留最近一次有效榜单。','Periodically refresh public evaluation sources and retain the last valid board.')} checked={draft.features.leaderboard} disabled={saving} onChange={leaderboard=>change({features:{...draft.features,leaderboard}})}/>
          <Field label={tr('Arena HTTP 代理','Arena HTTP proxy')} placeholder="http://127.0.0.1:7897" value={draft.leaderboard.arenaProxyUrl??''} disabled={saving} onChange={value=>change({leaderboard:{...draft.leaderboard,arenaProxyUrl:value.trim()||null}})}/>
          <p className={styles.muted}>{tr('仅用于 Arena 的 Hugging Face 数据读取。填入本机已有的 HTTP 代理地址；留空直连。不支持带账号密码的代理地址。','Used only for Arena data on Hugging Face. Enter your existing HTTP proxy origin, or leave blank for direct access. Proxy credentials in the URL are not supported.')}</p>
          <ToggleRow label={face.t('monitorPage')} description={tr('每 10 分钟检查 Tibo 原帖，需要 SocialData 凭据并消耗其余额及模型额度。','Check Tibo posts every 10 minutes. Requires SocialData and uses its balance and model quota.')} checked={draft.features.codexResetMonitor} disabled={saving} onChange={codexResetMonitor=>change({features:{...draft.features,codexResetMonitor}})}/>
        </Section>
        <Section id="settings-retention" title={face.t('retention')} description={tr('清理普通日志与可重建缓存，不删除业务内容和必要调用审计。','Removes ordinary logs and rebuildable caches, while retaining content and required call evidence.')}><div className={styles.grid}><NumberField label={face.t('logDays')} value={draft.retention.ordinaryLogDays} min={1} max={3650} disabled={saving} onChange={ordinaryLogDays=>change({retention:{...draft.retention,ordinaryLogDays}})}/><NumberField label={face.t('cacheDays')} value={draft.retention.cacheDays} min={1} max={365} disabled={saving} onChange={cacheDays=>change({retention:{...draft.retention,cacheDays}})}/></div></Section>
        <Section id="settings-advanced" title={tr('高级配置','Advanced settings')}>
          <details><summary>{face.t('embedding')}</summary><Choice label={face.t('embeddingMode')} value={draft.embedding.mode} choices={[{id:'lexical',label:face.t('lexical')},{id:'vector',label:face.t('vector')}]} onChange={mode=>change({embedding:{...draft.embedding,mode:mode as 'lexical'|'vector'}})}/>{draft.embedding.mode==='vector'&&<div className={styles.grid}><Field label={face.t('embeddingEndpoint')} value={draft.embedding.endpoint??''} onChange={endpoint=>change({embedding:{...draft.embedding,endpoint:endpoint||null,credentialRef:'embedding'}})}/><Field label={face.t('modelName')} value={draft.embedding.model??''} onChange={model=>change({embedding:{...draft.embedding,model:model||null}})}/><NumberField label={face.t('embeddingDimension')} value={draft.embedding.dimension??1} min={1} max={16384} onChange={dimension=>change({embedding:{...draft.embedding,dimension}})}/><p className={styles.muted}>{face.t('vectorInfo')}</p></div>}</details>
          <details><summary>{face.t('externalInput')}</summary><ToggleRow label={face.t('externalInput')} checked={draft.externalIngest.enabled} description={face.t('externalInfo')} onChange={enabled=>change({externalIngest:{enabled,credentialRef:enabled?'external':null}})}/></details>
          <details><summary>{face.t('industry')}</summary><Field label={face.t('industryName')} value={draft.industry.name} onChange={name=>change({industry:{...draft.industry,name}})}/><div className={styles.budgetGrid}>{(['T1','T1_5','T2'] as const).map(tier=><NumberField key={tier} label={`${face.t('thresholds')} ${tier}`} value={draft.industry.thresholds[tier]} min={0} max={100} onChange={value=>change({industry:{...draft.industry,thresholds:{...draft.industry.thresholds,[tier]:value}}})}/>)}</div><Choice label={face.t('promptEditor')} value={promptKey} choices={['prefilter','selection-score','structure','summarize-article','understand','translate-body','group-batch','group-pair','group-signal','story-digest','report-period'].map(id=>({id,label:id}))} onChange={setPromptKey}/><label className={styles.field}><span>{face.t('promptEditor')}</span><textarea rows={10} value={draft.industry.promptOverrides[promptKey]??''} onChange={event=>{const promptOverrides={...draft.industry.promptOverrides};if(event.target.value)promptOverrides[promptKey]=event.target.value;else delete promptOverrides[promptKey];change({industry:{...draft.industry,promptOverrides}});}}/></label></details>
          <details className={styles.advanced}><summary>{tr('设置 JSON','Settings JSON')}</summary><textarea aria-label={tr('设置 JSON','Settings JSON')} value={advanced} onChange={event=>{setAdvanced(event.target.value);setAdvancedDirty(true);setAdvancedError('');}} rows={16}/><div className={styles.actions}><Button variant="outline" onClick={applyAdvanced}>{tr('校验并应用到草稿','Validate and apply to draft')}</Button></div>{advancedError&&<p className={styles.error} role="alert">{advancedError}</p>}</details>
        </Section>
      </div>
      <footer className={styles.saveBar}><div role="status"><strong>{statusLabel}</strong><p>{tr('保存后生效 · 密钥不会写入设置 JSON','Applied after saving · Keys are excluded from settings JSON')}</p>{editor.error&&<p className={styles.error} role="alert">{editor.error}</p>}</div><div className={styles.pageActions}><Button variant="outline" disabled={!dirty||saving} onClick={()=>setConfirmation('discard')}>{tr('放弃更改','Discard changes')}</Button>{saveButton(tr('保存设置：固定操作栏','Save settings: sticky bar'))}</div></footer>
    </form>
    <details className={styles.section} style={{marginTop:22}}><summary>{face.t('diagnosticTitle')}</summary><p className={styles.muted}>{face.t('space')}: {((state.diagnostics?.databaseBytes??0)+(state.diagnostics?.walBytes??0)).toLocaleString()} bytes · SQLite {state.diagnostics?.schemaVersion}</p><pre>{JSON.stringify(state.diagnostics?.resources,null,2)}</pre><p className={styles.muted}>{face.t('externalPort')}: {state.diagnostics?.externalPort??'—'}</p>{state.diagnostics?.externalError&&<p className={styles.error}>{state.diagnostics.externalError}</p>}</details>
    <details className={styles.section} style={{marginTop:22}}><summary>{face.t('clearTitle')}</summary><p className={styles.error}>{face.t('clearInfo')}</p><Checkbox checked={clearAck} onChange={setClearAck} label={face.t('clearAck')}/><Field label={face.t('clearPhrase')} value={clearPhrase} onChange={setClearPhrase}/><div className={styles.actions}><Button variant="outline" disabled={state.busy||!clearAck||clearPhrase!=='CLEAR HOTSTREAM'} onClick={face.clearNews}>{face.t('clearAction')}</Button></div></details>
    <Modal open={confirmation==='discard'} onClose={()=>setConfirmation('')} title={tr('放弃未保存更改？','Discard unsaved changes?')} closeLabel={tr('关闭','Close')} description={tr('会恢复当前已保存的设置，并清空尚未保存的 Key 输入。','Restores saved settings and clears unsaved key inputs.')} footer={<div className={styles.dialogFooter}><Button variant="outline" onClick={()=>setConfirmation('')}>{tr('继续编辑','Keep editing')}</Button><Button onClick={()=>{discard();setConfirmation('');}}>{tr('放弃更改','Discard changes')}</Button></div>}/>
  </>;
}

export function FormNavigationModal({state,face}:AdminProps){
  const tr=translator(face),pending=state.formNavigation;
  return <Modal open={!!pending} onClose={()=>{if(!pending?.saving)face.resolveFormNavigation('cancel');}} title={tr(`尚未保存：${pending?.title??''}`,`Unsaved changes: ${pending?.title??''}`)} closeLabel={tr('关闭','Close')} description={tr('离开前可以保存，也可以放弃本次更改。','Save before leaving, or discard these changes.')} footer={<div className={styles.dialogFooter}><Button variant="outline" disabled={pending?.saving} onClick={()=>face.resolveFormNavigation('cancel')}>{tr('继续编辑','Keep editing')}</Button><Button variant="ghost" disabled={pending?.saving} onClick={()=>face.resolveFormNavigation('discard')}>{tr('放弃修改','Discard')}</Button><Button disabled={pending?.saving} onClick={()=>face.resolveFormNavigation('save')}>{tr(pending?.saving?'保存中…':'保存并离开',pending?.saving?'Saving…':'Save and leave')}</Button></div>}>{(state.settingsDraft?.error||state.error)&&<p role="alert" className={styles.error}>{state.settingsDraft?.error??state.error}</p>}</Modal>;
}
