import {useEffect,useRef,useState} from 'react';
import {sourceSchema,type Source} from 'dsh-hotstream-contracts/runtime';
import {Modal,Button,Field,NumberField,Choice,ToggleRow,Section} from './Controls.tsx';
import {translator,type AdminProps} from './types.ts';
import styles from './Admin.module.css';

const isPaid=(source:Source)=>['x_search','mp_account'].includes(source.kind)||String(source.config.url??'').startsWith('https://r.jina.ai/');
export function SourcesPage({state,face}:AdminProps){
  const tr=translator(face),[editing,setEditing]=useState<Source|null>(null),[expected,setExpected]=useState(0),[advanced,setAdvanced]=useState(''),[advancedDirty,setAdvancedDirty]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[confirmPreview,setConfirmPreview]=useState<Source|null>(null),[remove,setRemove]=useState<Source|null>(null),[discard,setDiscard]=useState(false);
  const original=useRef(''),originalId=useRef(''),editorRef=useRef<HTMLDivElement>(null);
  const dirty=!!editing&&(JSON.stringify(editing)!==original.current||advancedDirty),dirtyRef=useRef(dirty);dirtyRef.current=dirty;
  const choose=(source:Source,revision=source.revision)=>{original.current=JSON.stringify(source);originalId.current=source.id;setExpected(revision);setEditing(structuredClone(source));setAdvanced(JSON.stringify(source,null,2));setAdvancedDirty(false);setError('');};
  useEffect(()=>{if(editing)editorRef.current?.scrollIntoView({block:'start',behavior:'smooth'});},[editing?.id]);
  const update=(patch:Partial<Source>)=>setEditing(source=>source?{...source,...patch}:source);
  const cfg=(key:string,value:Source['config'][string])=>setEditing(source=>source?{...source,config:{...source.config,[key]:value}}:source);
  const close=()=>{setEditing(null);setAdvancedDirty(false);setError('');};
  const save=async()=>{
    if(!editing||saving)return false;setError('');let source=editing;
    try{if(advancedDirty)source=sourceSchema.parse(JSON.parse(advanced));else source=sourceSchema.parse(editing);if(source.id!==originalId.current)throw new Error(tr('请保留信源编号；复制来源请使用“新增信源”。','Keep the source ID; use Add source to create a copy.'));}
    catch(cause){setError(cause instanceof Error?cause.message:face.t('invalidJson'));return false;}
    setSaving(true);try{const success=await face.saveSource(source,expected);if(success)close();return success;}finally{setSaving(false);}
  };
  const saveRef=useRef(save);saveRef.current=save;
  useEffect(()=>face.registerFormGuard({title:face.t('editSource'),isDirty:()=>dirtyRef.current,save:()=>saveRef.current(),discard:close}),[face.registerFormGuard]);
  const conflict=editing&&state.sources.some(source=>source.id===editing.id&&source.revision>expected);
  const fieldsDisabled=saving||state.busy;
  return <>
    <header className={styles.pageHeader}><div><h1>{face.t('sourcesPage')}</h1><p>{face.t('sourceInfo')}</p><p>{tr(`已启用 ${state.sources.filter(source=>source.enabled).length} / ${state.sources.length} 个信源`,`${state.sources.filter(source=>source.enabled).length} of ${state.sources.length} sources enabled`)}</p></div><Button disabled={!!editing||state.busy} onClick={()=>choose({createdAt:null,id:'source-'+crypto.randomUUID(),name:'',kind:'rss',config:{feedUrl:''},tags:[],tier:'T2',ownerEntityId:null,signalGroupId:null,participationMode:'editorial',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:Date.now(),lastError:null},0)}>{face.t('addSource')}</Button></header>
    {editing&&<div ref={editorRef}><Section title={expected?face.t('editSource'):face.t('addSource')} description={tr('填写后保存；试抓预览不会写入新闻库或执行评分。','Save your changes. A preview does not insert news or start scoring.')} actions={<span className={styles.status} data-state={dirty?'dirty':'clean'}>{tr(dirty?'未保存':'编辑中',dirty?'Unsaved':'Editing')}</span>}>
      <form onSubmit={event=>{event.preventDefault();void save();}}>
        {conflict&&<p role="alert" className={styles.notice}>{tr('此信源已在后台更新，草稿已保留。取消编辑后可重新读取最新版本。','The source changed in the background. Your draft is retained. Cancel and reopen to load the latest version.')}</p>}
        <div className={styles.grid}><Field label={face.t('sourceName')} value={editing.name} onChange={name=>update({name})} disabled={fieldsDisabled}/><Choice label={face.t('sourceKind')} value={editing.kind} choices={['rss','web_list','json_list','x_search','mp_account','external'].map(id=>({id,label:id}))} onChange={kind=>update({kind:kind as Source['kind'],config:{}})} disabled={fieldsDisabled}/>
          {!['mp_account','external'].includes(editing.kind)&&<Field label={editing.kind==='x_search'?tr('X 搜索条件','X search query'):face.t('sourceUrl')} value={String(editing.config[editing.kind==='rss'?'feedUrl':editing.kind==='x_search'?'query':'url']??'')} onChange={value=>cfg(editing.kind==='rss'?'feedUrl':editing.kind==='x_search'?'query':'url',value)} disabled={fieldsDisabled}/>}
          {editing.kind==='mp_account'&&<Field label={face.t('accountId')} value={String(editing.config.ghid??'')} onChange={value=>cfg('ghid',value)} disabled={fieldsDisabled}/>}
          {editing.kind==='web_list'&&<><Field label={face.t('listSelector')} value={String(editing.config.itemSelector??'')} onChange={value=>cfg('itemSelector',value)}/><Field label={face.t('linkSelector')} value={String(editing.config.linkSelector??'')} onChange={value=>cfg('linkSelector',value)}/></>}
          {editing.kind==='json_list'&&<><Field label={face.t('listPath')} value={String(editing.config.itemsPath??'')} onChange={value=>cfg('itemsPath',value)}/><Field label={face.t('titlePath')} value={Array.isArray(editing.config.titlePaths)?editing.config.titlePaths.join(', '):'title'} onChange={value=>cfg('titlePaths',value.split(',').map(item=>item.trim()).filter(Boolean))}/><Field label={face.t('urlPath')} value={String(editing.config.urlTemplate??'{url}')} onChange={value=>cfg('urlTemplate',value)}/></>}
          <NumberField label={face.t('interval')} value={editing.intervalMinutes} min={1} max={1440} onChange={intervalMinutes=>update({intervalMinutes})} disabled={fieldsDisabled}/><Choice label={face.t('tier')} value={editing.tier} choices={['T1','T1_5','T2','EXCLUDE_MP'].map(id=>({id,label:id}))} onChange={tier=>update({tier:tier as Source['tier']})} disabled={fieldsDisabled}/><Choice label={face.t('grouping')} value={editing.participationMode} choices={['editorial','hot_signal','isolated'].map(id=>({id,label:id}))} onChange={participationMode=>update({participationMode:participationMode as Source['participationMode']})} disabled={fieldsDisabled}/>
        </div>
        <ToggleRow label={face.t('enabled')} description={tr('保存后按照采集间隔执行。','Runs on the saved schedule.')} checked={editing.enabled} onChange={enabled=>update({enabled})} disabled={fieldsDisabled}/><ToggleRow label={face.t('fulltext')} description={tr('只展示来源许可的正文内容。','Show only source-permitted full text.')} checked={editing.siteFulltext} onChange={siteFulltext=>update({siteFulltext})} disabled={fieldsDisabled}/>
        <details className={styles.advanced}><summary>{face.t('advanced')}</summary><textarea aria-label={face.t('advanced')} rows={16} value={advancedDirty?advanced:JSON.stringify(editing,null,2)} onChange={event=>{setAdvanced(event.target.value);setAdvancedDirty(true);}}/></details>
        {error&&<p className={styles.error} role="alert">{error}</p>}
        <footer className={styles.saveBar}><div><strong>{tr(saving?'保存中…':dirty?'有未保存更改':'编辑信源',saving?'Saving…':dirty?'Unsaved changes':'Edit source')}</strong>{conflict&&<p className={styles.error}>{tr('版本已变化，请保留草稿后重新读取。','Source revision changed; reload before saving.')}</p>}</div><div className={styles.pageActions}><Button variant="outline" onClick={()=>dirty?setDiscard(true):close()} disabled={saving}>{face.t('cancel')}</Button><Button type="submit" disabled={fieldsDisabled||!editing.name.trim()||!!conflict}>{face.t('save')}</Button></div></footer>
      </form>
    </Section></div>}
    <div className={styles.tableScroll} role="region" aria-label={tr('信源列表，可横向滚动','Sources, horizontally scrollable')} tabIndex={0}><table className={styles.sourceTable}><thead><tr><th>{face.t('sourceName')}</th><th>{tr('类型 / 级别','Type / tier')}</th><th>{tr('间隔','Interval')}</th><th>{tr('状态','Status')}</th><th>{tr('最近成功','Last success')}</th><th>{tr('操作','Actions')}</th></tr></thead><tbody>{state.sources.map(source=><tr key={source.id}><td><strong>{source.name}</strong>{source.lastError&&<p className={styles.error}>{source.lastError}</p>}</td><td>{source.kind}<br/><span className={styles.muted}>{source.tier}</span></td><td>{source.intervalMinutes} {tr('分钟','min')}</td><td><span className={styles.status} data-state={!source.enabled?'clean':source.health==='failed'?'failed':source.health==='blocked'?'unconfigured':'saved'}>{tr(!source.enabled?'已停用':source.health==='failed'?'抓取失败':source.health==='blocked'?'等待处理':source.health==='unknown'?'待核对':'已启用',!source.enabled?'Disabled':source.health==='failed'?'Failed':source.health==='blocked'?'Blocked':source.health==='unknown'?'Not checked':'Enabled')}</span></td><td>{source.lastOkAt?new Date(source.lastOkAt).toLocaleString(face.t('back')==='Back'?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'short'}):'—'}</td><td><div className={styles.rowActions}><Button variant="outline" disabled={!!editing||state.busy} onClick={()=>choose(source)}>{face.t('editSource')}</Button><Button variant="outline" disabled={!!editing||state.busy||source.kind==='external'} onClick={()=>isPaid(source)?setConfirmPreview(source):face.previewSource(source.id,false)}>{face.t('previewSource')}</Button><Button variant="ghost" disabled={!!editing||state.busy} onClick={()=>{void face.saveSource({...source,enabled:!source.enabled},source.revision);}}>{face.t(source.enabled?'disabled':'enabled')}</Button><Button variant="ghost" disabled={!!editing||state.busy} onClick={()=>setRemove(source)}>{tr('移除','Remove')}</Button></div></td></tr>)}</tbody></table></div>
    {state.preview&&<Section title={face.t('previewSource')} description={tr('仅为返回结果预览，没有写入新闻库或评分。','Returned results only; no news insertion or scoring.')}><ul>{state.preview.items.map((item,index)=><li key={index}><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title}</a></li>)}</ul></Section>}
    <Modal open={!!confirmPreview} onClose={()=>setConfirmPreview(null)} title={tr('付费信源试抓','Preview a paid source')} closeLabel={tr('关闭','Close')} description={tr('最多发起一次采集请求，仅预览返回结果。费用从你自己的服务商余额扣除，不执行模型评分。','At most one collection request. Results are previewed only, with no model scoring. Charges use your own provider balance.')} footer={<div className={styles.dialogFooter}><Button variant="outline" onClick={()=>setConfirmPreview(null)}>{face.t('cancel')}</Button><Button onClick={()=>{if(confirmPreview)face.previewSource(confirmPreview.id,true);setConfirmPreview(null);}}>{tr('确认本次试抓','Confirm this preview')}</Button></div>}><p>{confirmPreview?.name}</p><p>{tr('服务','Service')}：{confirmPreview?.kind==='x_search'?'SocialData':confirmPreview?.kind==='mp_account'?'大家啦':'Jina'}</p><p className={styles.muted}>{String(confirmPreview?.config.query??confirmPreview?.config.ghid??confirmPreview?.config.url??'')}</p></Modal>
    <Modal open={!!remove} onClose={()=>setRemove(null)} title={face.t('removeSource')} closeLabel={tr('关闭','Close')} description={remove?.name??''} footer={<div className={styles.dialogFooter}><Button variant="outline" onClick={()=>setRemove(null)}>{face.t('cancel')}</Button><Button onClick={()=>{if(remove)face.removeSource(remove.id,remove.revision);setRemove(null);}}>{tr('确认移除','Remove source')}</Button></div>}/>
    <Modal open={discard} onClose={()=>setDiscard(false)} title={tr('放弃信源草稿？','Discard source draft?')} closeLabel={tr('关闭','Close')} footer={<div className={styles.dialogFooter}><Button variant="outline" onClick={()=>setDiscard(false)}>{tr('继续编辑','Keep editing')}</Button><Button onClick={()=>{close();setDiscard(false);}}>{tr('放弃更改','Discard changes')}</Button></div>}/>
  </>;
}
