import {describe,it,expect} from 'vitest';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {PublicNetwork} from '../../packages/host/lib/types/network.js';
import {settingsSchema,defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
const require=createRequire(new URL('../../packages/host/package.json',import.meta.url)),{ProxyAgent}=await import(require.resolve('undici'));
const fakeDns=async()=>[{address:'2001::c73b:94ce',family:6}];
async function withProxy(work,fallback){
 const targets=[],requests=[],sockets=new Set();const server=createServer((request,response)=>{const url=new URL(request.url);targets.push(url.hostname+':'+(url.port||'80'));requests.push(request.method+' '+url.pathname);if(url.pathname==='/slow')return;if(url.pathname==='/redirect'){response.writeHead(302,{location:'http://127.0.0.1/private','content-length':'0'});response.end();}else{response.writeHead(200,{'content-length':'2'});response.end('ok');}});
 server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.on('error',()=>{});});
 server.on('connect',(request,socket)=>{targets.push(request.url);socket.write('HTTP/1.1 200 Connection Established\r\n\r\n');socket.once('data',bytes=>{const line=bytes.toString().split('\r\n')[0];requests.push(line);if(line.includes('/slow'))return;if(line.includes('/redirect'))socket.end('HTTP/1.1 302 Found\r\nLocation: http://127.0.0.1/private\r\nContent-Length: 0\r\nConnection: close\r\n\r\n');else socket.end('HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nok');});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const proxy=`http://127.0.0.1:${server.address().port}`;
 const lifetime=new AbortController(),network=new PublicNetwork(lifetime.signal,new ProxyAgent(proxy),fakeDns,undefined,{proxied:true,ownsAgent:true,publicFallback:fallback});
 try{await work({network,lifetime,proxy,targets,requests});}finally{lifetime.abort();for(const socket of sockets)socket.destroy();await network.close();await new Promise(resolve=>server.close(resolve));}
}
describe('Arena proxy route and safety boundaries',()=>{
 it('uses the proxy to resolve a public host whose local DNS is poisoned',()=>withProxy(async({network,targets})=>{const result=await network.fetch('http://arena-public.invalid/data');expect(result.status).toBe(200);expect(result.text()).toBe('ok');expect(targets).toEqual(['arena-public.invalid:80']);}));
 it('rejects internal destinations and private redirects before sending them to the proxy',()=>withProxy(async({network,targets})=>{await expect(network.fetch('http://127.0.0.1/private')).rejects.toThrow('Blocked private');expect(targets).toHaveLength(0);await expect(network.fetch('http://arena-public.invalid/redirect')).rejects.toThrow('Blocked private');expect(targets).toEqual(['arena-public.invalid:80']);}));
 it('keeps origin-bound authentication off a cross-origin redirect',()=>withProxy(async({network,targets})=>{await expect(network.fetch('http://arena-public.invalid/redirect',{headers:{authorization:'fixture-only'}})).rejects.toThrow('Blocked cross-origin');expect(targets).toHaveLength(1);}));
 it('cancels a scoped read without closing its owner',()=>withProxy(async({network,requests})=>{const cancel=new AbortController(),scoped=network.fork(cancel.signal);const pending=scoped.fetch('http://arena-public.invalid/slow');const rejected=expect(pending).rejects.toMatchObject({name:'AbortError'});for(let n=0;n<100&&!requests.length;n++)await new Promise(resolve=>setTimeout(resolve,2));expect(requests).toHaveLength(1);cancel.abort();await rejected;await scoped.close();expect((await network.fetch('http://arena-public.invalid/ok')).text()).toBe('ok');}));
 it('uses the original transport for an authenticated request without contacting the public proxy',async()=>{const calls=[];const fallback={fetch:async(url,options)=>{calls.push({url,authorization:options.headers.authorization});return {status:200,text:()=>"direct"};}};await withProxy(async({network,targets})=>{const result=await network.fetch('https://service.invalid/data',{headers:{authorization:'fixture-only'}});expect(result.text()).toBe('direct');expect(targets).toEqual([]);},fallback);expect(calls).toEqual([{url:'https://service.invalid/data',authorization:'fixture-only'}]);});
 it('keeps the direct route strict and rejects unsafe proxy configuration',async()=>{const network=new PublicNetwork(new AbortController().signal,undefined,fakeDns);try{await expect(network.fetch('http://arena-public.invalid/data')).rejects.toThrow('Blocked private');}finally{await network.close();}const old=defaultSettings({provider:'fixture',model:'fixture'});delete old.leaderboard.arenaProxyUrl;expect(settingsSchema.parse(old).leaderboard.arenaProxyUrl).toBeNull();for(const value of ['socks5://127.0.0.1:7897','http://user:secret@127.0.0.1:7897','http://127.0.0.1:7897/proxy?token=secret']){expect(()=>settingsSchema.parse({...old,leaderboard:{...old.leaderboard,arenaProxyUrl:value}})).toThrow();}expect(settingsSchema.parse({...old,leaderboard:{...old.leaderboard,arenaProxyUrl:'http://127.0.0.1:7897'}}).leaderboard.arenaProxyUrl).toBe('http://127.0.0.1:7897');});
});
