import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
import {seedSqlite,at,sources} from '../golden/fixture.mjs';

function fixture(work){const db=new DatabaseSync(':memory:');const store=new HotstreamDatabase(db);try{store.execute('initialize',{commandId:randomUUID(),settings:{...defaultSettings({provider:'fixture',model:'fixture'}),autoCollectEnabled:false},sources:[{...sources[0],id:"placeholder",enabled:false}],now:at});seedSqlite(db);work(store,db);}finally{db.close();}}
function groupJob(store,article,now=Date.now()){const state=store.execute('state',{});const job=store.execute('enqueue',{kind:'group',subject:article,key:randomUUID(),epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{settings:state.settings},priority:100,maxAttempts:3,dueAt:now});const claimed=store.execute('claim',{kinds:['group'],owner:'fixture',now,leaseMs:600000});return {job:claimed??job,now,epoch:state.epoch};}

describe('atomic manual identity and publication commands',()=>{
 it('archives an earlier editorial run after an explicit rerun without overwriting its projection',()=>fixture(store=>{const before=store.execute('detail',{id:'a-official'});const commandId=randomUUID();store.execute('rerun',{id:'a-official',scope:'editorial',commandId,now:Date.now()});const state=store.execute('state',{});store.execute('enqueue',{kind:'writing',subject:'a-official',key:randomUUID(),epoch:0,inputRevision:1,configRevision:state.revision,payload:{settings:state.settings},priority:100,maxAttempts:3,dueAt:Date.now()});const claimed=store.execute('claim',{kinds:['writing'],owner:'fixture',now:Date.now(),leaseMs:600000});store.execute('analysis',{jobId:claimed.id,owner:'fixture',epoch:0,now:Date.now(),step:{articleId:'a-official',inputRevision:1,configRevision:state.revision,stage:'writing',slot:'writing',runKey:'initial',provider:'fixture',model:'fixture',promptHash:'old',result:{normalized:{titleZh:'迟到旧结果',summaryZh:'迟到旧结果不应该覆盖当前版本',relevance:'pass',selected:true,score:99}},receiptIds:[],createdAt:Date.now()}});expect(store.execute('detail',{id:'a-official'}).title).toBe(before.title);expect(store.execute('work',{id:'a-official'}).activeRun).toBe(commandId);expect(store.execute('work',{id:'a-official'}).steps.some(step=>step.promptHash==='old')).toBe(true);store.execute('override',{id:'a-official',expectedRevision:0,fields:{},visibility:null,reason:'reproject from applied evidence',now:Date.now()});expect(store.execute('detail',{id:'a-official'}).title).toBe(before.title);}));
 it('applies an editorial override once, rejects reused identities and records before/after',()=>fixture(store=>{const request={commandId:randomUUID(),id:'a-official',expectedRevision:0,visibility:null,fields:{title:'已核实的更正标题'},reason:'fixture correction',now:Date.now()};expect(store.execute('override',request)).toBe(true);expect(store.execute('override',request)).toBe(true);expect(store.execute('detail',{id:request.id}).title).toBe(request.fields.title);expect(store.execute('mutationHistory',{limit:10,offset:0})).toHaveLength(1);expect(()=>store.execute('override',{...request,fields:{title:'different'}})).toThrow('identity');expect(()=>store.execute('override',{...request,commandId:randomUUID()})).toThrow('revision');}));
 it('retains manual attribution and regenerates its participant evidence',()=>fixture((store,db)=>{store.execute('correctEvent',{commandId:randomUUID(),id:'a-media',mode:'assign',factId:'fact-b',expectedRevision:0,reason:'manual attribution',now:Date.now()});expect(store.execute('detail',{id:'a-media'}).storyId).toBe('story-b');expect(db.prepare('SELECT story_id FROM story_signals WHERE article_id=?').get('a-media').story_id).toBe('story-b');const f=groupJob(store,'a-media');expect(store.execute('grouping',{jobId:f.job.id,owner:'fixture',epoch:f.epoch,now:f.now,id:'a-media',revision:1,manualRevision:0,decisions:[],selection:{addsValue:true,reason:'stale'},receiptIds:[]})).toBe(false);expect(store.execute('detail',{id:'a-media'}).factId).toBe('fact-b');}));
 it('rejects stale candidate membership inside the grouping transaction',()=>fixture(store=>{const candidate=store.execute('candidates',{id:'roundup',now:at}).find(c=>c.factId==='fact-a');store.execute('correctEvent',{id:'a-media',mode:'standalone',factId:null,reason:'manual independent',now:Date.now()});const f=groupJob(store,'roundup');expect(store.execute('grouping',{jobId:f.job.id,owner:'fixture',epoch:f.epoch,now:f.now,id:'roundup',revision:1,manualRevision:0,candidateVersions:[{factId:candidate.factId,stamp:candidate.stamp}],decisions:[{factId:'fact-a',relation:'SAME_OCCURRENCE',confidence:0.99,note:''}],selection:{addsValue:true,reason:'stale'},receiptIds:[]})).toBe(false);expect(store.execute('detail',{id:'roundup'}).factId).toBeNull();expect(store.execute('jobs',{limit:100,offset:0}).some(j=>j.payload.candidateRefreshes===1)).toBe(true);}));
 it('splits a proper subset, preserves original membership and fences automatic remerging',()=>fixture(store=>{const old=store.execute('story',{id:'story-a'});const request={commandId:randomUUID(),id:old.id,expectedRevision:old.version,articleIds:['a-media'],reason:'confirmed separate event',now:Date.now()};store.execute('splitStory',request);const separate=store.execute('detail',{id:'a-media'}).storyId;expect(separate).not.toBe(old.id);expect(store.execute('story',{id:old.id}).articles.some(p=>p.id==='a-media')).toBe(false);expect(store.execute('mergeStories',{survivor:old.id,other:separate,now:Date.now()})).toBe(false);expect(store.execute('splitStory',request)).toBe(true);expect(store.execute('mutationHistory',{limit:100,offset:0}).filter(row=>row.kind==='story-split')).toHaveLength(1);}));
 it('manually merges with CAS and resolves the previous public address',()=>fixture(store=>{const a=store.execute('story',{id:'story-a'}),b=store.execute('story',{id:'story-b'});const request={commandId:randomUUID(),survivor:a.id,other:b.id,expectedSurvivor:a.version,expectedOther:b.version,reason:'confirmed same story',now:Date.now()};store.execute('mergeStories',request);expect(store.execute('story',{id:b.publicId}).id).toBe(a.id);expect(store.execute('mergeStories',request)).toBe(true);expect(()=>store.execute('mergeStories',{...request,commandId:randomUUID()})).toThrow('Active stories');}));
 it('clears withdrawn material from all reading projections while retaining a bookmark marker',()=>fixture(store=>{store.execute('marks',{id:'a-official',bookmarked:true,read:true,now:Date.now()});store.execute('override',{id:'a-official',expectedRevision:0,visibility:'withdrawn',fields:{},reason:'withdrawn',now:Date.now()});expect(store.execute('detail',{id:'a-official'})).toBeNull();expect(store.execute('story',{id:'story-a'}).articles.some(p=>p.id==='a-official')).toBe(false);const marker=store.execute('page',{view:'bookmarks',category:null,topic:null,query:'',limit:30,offset:0}).items[0];expect(marker).toMatchObject({id:'a-official',visibility:'withdrawn',title:'',summary:'',body:null,bookmarked:true});expect(store.execute('dailyEdition',{date:'2026-10-04',start:at-86400000,end:at}).entries.some(e=>e.entry.itemId==='a-official')).toBe(false);}));
});
