import {describe,it,expect} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {HotstreamSqliteProvider} from '../../packages/storage-sqlite/lib/index.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
const source={id:'fixture',name:'Fixture',kind:'external',config:{},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'isolated',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'hotstream-cancellation-'));const store=new HotstreamSqliteProvider(join(root,'news.sqlite'));try{const state=await store.execute('initialize',{commandId:randomUUID(),settings:defaultSettings({provider:'mock',model:'mock'}),sources:[source],now:Date.now()});await fn(store,state);}finally{await store.close();await rm(root,{recursive:true,force:true});}}
function queued(state,kind,key){return {kind,subject:key,key,epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{settings:state.settings},priority:10,maxAttempts:3,dueAt:Date.now()};}
describe('durable task and module cancellation',()=>{
 it('cancels only the leased batch while another task can commit',()=>fixture(async(store,state)=>{await store.execute('enqueue',queued(state,'score1','a'));await store.execute('enqueue',queued(state,'score1','b'));const a=await store.execute('claim',{kinds:['score1'],owner:'runtime',now:Date.now(),leaseMs:600000});const b=await store.execute('claim',{kinds:['score1'],owner:'runtime',now:Date.now(),leaseMs:600000});expect(await store.execute('cancelJob',{id:a.id,owner:'runtime',epoch:state.epoch,now:Date.now(),reason:'explicit cancellation'})).toBe(true);expect(await store.execute('finish',{id:a.id,owner:'runtime',epoch:state.epoch,now:Date.now(),result:null})).toBe(false);expect(await store.execute('finish',{id:b.id,owner:'runtime',epoch:state.epoch,now:Date.now(),result:{ok:true}})).toBe(true);const jobs=await store.execute('jobs',{limit:10,offset:0});expect(jobs.find(j=>j.id===a.id).state).toBe('cancelled');expect(jobs.find(j=>j.id===b.id).state).toBe('succeeded');}));
 it('fences an old optional run across off/on while retaining its previous successful state',()=>fixture(async(store,state)=>{let current=await store.execute('configure',{revision:state.revision,settings:{...state.settings,features:{leaderboard:true,codexResetMonitor:false}},now:Date.now()});const generation=current.moduleGenerations.leaderboard;const job=await store.execute('enqueue',queued(current,'leaderboard','lb'));expect(job.payload.moduleGeneration).toBe(generation);await store.execute('moduleStatus',{module:'leaderboard',source:'fixture',generation,state:{status:'ok',rows:3},now:Date.now()});current=await store.execute('configure',{revision:current.revision,settings:{...current.settings,features:{leaderboard:false,codexResetMonitor:false}},now:Date.now()});await expect(store.execute('moduleStatus',{module:'leaderboard',source:'fixture',generation,state:{status:'failed'},now:Date.now()})).rejects.toThrow('generation');expect((await store.execute('optionalData',{module:'leaderboard',limit:10,offset:0})).sources[0].rows).toBe(3);current=await store.execute('configure',{revision:current.revision,settings:{...current.settings,features:{leaderboard:true,codexResetMonitor:false}},now:Date.now()});expect(current.moduleGenerations.leaderboard).toBe(generation+2);await expect(store.execute('moduleStatus',{module:'leaderboard',source:'fixture',generation,state:{status:'ok',rows:9},now:Date.now()})).rejects.toThrow('generation');}));
});
