import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,createHash} from 'node:crypto';
import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
import {seedSqlite,sources,at} from '../golden/fixture.mjs';
function fixture(work){const db=new DatabaseSync(':memory:'),store=new HotstreamDatabase(db);store.execute('initialize',{commandId:randomUUID(),settings:{...defaultSettings({provider:'fixture',model:'fixture'}),autoCollectEnabled:false},sources:[{...sources[0],id:'placeholder',enabled:false}],now:at});seedSqlite(db);try{work(store,db);}finally{db.close();}}
describe('explicit cumulative real-model scope',()=>{
 it('caps every reserved attempt cumulatively and preserves the allowance across restart and clear',()=>fixture((store,db)=>{const commandId=randomUUID(),request={commandId,route:{provider:'fixture',model:'fixture'},articleIds:['a-official','a-media','b-person'],maximum:2,now:Date.now()};expect(store.execute('authorizeModels',request).used).toBe(0);expect(store.execute('authorizeModels',request).used).toBe(0);const job=store.execute('claim',{kinds:['prefilter'],owner:'fixture',now:Date.now(),leaseMs:600000});const reserve=key=>store.execute('reserve',{jobId:job.id,key,service:'llm',epoch:0,requestHash:createHash('sha256').update(key).digest('hex'),request:{provider:'fixture',model:'fixture'},now:Date.now()});expect(reserve('one').admitted).toBe(true);expect(reserve('two').admitted).toBe(true);expect(reserve('three')).toMatchObject({admitted:false,blockedReason:'explicit-model-test-limit'});expect(new HotstreamDatabase(db).execute('modelAuthorization',{}).used).toBe(2);store.execute('clear',{commandId:randomUUID(),now:Date.now()});expect(store.execute('modelAuthorization',{})).toMatchObject({used:2,maximum:2});}));
 it('refuses another route and other paid services without consuming the allowance',()=>fixture(store=>{store.execute('authorizeModels',{commandId:randomUUID(),route:{provider:'fixture',model:'fixture'},articleIds:['a-official','a-media','b-person'],maximum:30,now:Date.now()});const job=store.execute('claim',{kinds:['prefilter'],owner:'fixture',now:Date.now(),leaseMs:600000});const input={jobId:job.id,key:'wrong',service:'llm',epoch:0,requestHash:createHash('sha256').update('wrong').digest('hex'),request:{provider:'other',model:'other'},now:Date.now()};expect(store.execute('reserve',input).blockedReason).toBe('explicit-model-test-scope');expect(store.execute('reserve',{...input,service:'socialdata'}).blockedReason).toBe('other-paid-services-not-authorized');expect(store.execute('modelAuthorization',{}).used).toBe(0);}));
 it('shows captured candidates before editorial completion without exposing them as Publications',()=>fixture((store,db)=>{db.prepare('DELETE FROM publications WHERE article_id=?').run('a-official');const candidate=store.execute('candidatesPage',{query:'OpenAI',limit:100,offset:0}).items.find(item=>item.id==='a-official');expect(candidate).toMatchObject({title:'OpenAI 发布 Fixture',sourceName:'Official maker',publishedAt:at-20*3600000});expect(store.execute('detail',{id:'a-official'})).toBeNull();}));
});
