import {describe,it,expect} from 'vitest';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {HotstreamSqliteProvider} from '../../packages/storage-sqlite/lib/index.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
const source={id:'fixture',name:'Optional module fixture',kind:'external',config:{},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'isolated',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'hotstream-m4-'));const store=new HotstreamSqliteProvider(join(root,'news.sqlite'));try{const state=await store.execute('initialize',{commandId:randomUUID(),settings:defaultSettings({provider:'mock',model:'mock'}),sources:[source],now:Date.now()});await fn(store,state);}finally{await store.close();await rm(root,{recursive:true,force:true});}}
async function receipt(store,state){const now=Date.now();const hash=createHash('sha256').update('simulated monitor result').digest('hex');const row=await store.execute('reserve',{key:randomUUID(),service:'llm',epoch:state.epoch,requestHash:hash,request:{simulated:true},now});await store.execute('sent',{id:row.receipt.id,epoch:state.epoch,auditRef:'test-only',now});await store.execute('receive',{id:row.receipt.id,epoch:state.epoch,response:{simulated:true},usage:{},now});return row.receipt.id;}
function recognition(action,excerpt,extra={}){return {relevant:true,translationZh:null,contextZh:[],outage:null,needsReview:false,propositions:[{kind:'direct_reset',kindExplicit:true,action,real:true,count:1,relatesTo:null,excerpt,excerptZh:excerpt,statedTime:null,timeInferred:false,expectedLanding:null,scope:{audienceSource:'everyone',plans:null,audienceZh:'所有用户',productsZh:'Codex'},...extra}]};}
async function post(store,state,id,text,at=Date.now()){await store.execute('monitorPosts',{epoch:state.epoch,posts:[{id,author:'thsottiaux',publishedAt:at,text,url:'https://x.com/thsottiaux/status/'+id,context:[],raw:{}}],cursor:{scannedThrough:at},receiptIds:[],now:at});}
describe('M4 retained optional business relations',()=>{
 it('keeps both modules disabled and performs no paid attempts by default',()=>fixture(async(store,state)=>{for(const module of ['leaderboard','monitor']){const data=await store.execute('optionalData',{module,limit:10,offset:0});expect(data.enabled).toBe(false);expect(data.records).toEqual([]);}expect((await store.execute('receipts',{limit:10,offset:0})).length).toBe(0);}));
 it('imports locked public directory, aliases, fixed scales and official price seeds once',()=>fixture(async(store,state)=>{const models=JSON.parse(await readFile(new URL('../../industry/ai/leaderboard-models.json',import.meta.url),'utf8'));const prices=JSON.parse(await readFile(new URL('../../industry/ai/leaderboard-prices.json',import.meta.url),'utf8'));const input={epoch:state.epoch,models:models.models,aliases:models.aliases,calibrations:models.calibrations,prices:prices.prices,now:Date.now()};await store.execute('lbSeed',input);await store.execute('lbSeed',input);const data=await store.execute('optionalData',{module:'leaderboard',limit:100,offset:0});expect(data.models).toHaveLength(100);expect((await store.execute('lbHistory',{now:Date.now()})).calibrations).toHaveLength(17);expect(data.models.some(m=>m.prices.length>0)).toBe(true);}));
 it('does not turn a future announcement or progress into a confirmation',()=>fixture(async(store,state)=>{const at=Date.now();await post(store,state,'100','We will reset everyone in the next hour.',at);const id=await receipt(store,state);await store.execute('monitorApply',{epoch:state.epoch,postId:'100',recognition:recognition('announce','We will reset everyone in the next hour.',{statedTime:{precision:'deadline',relativeHours:1,period:null,clock:null,clockThrough:null,dayOffset:null}}),receiptId:id,now:at});let data=await store.execute('optionalData',{module:'monitor',limit:10,offset:0});expect(data.records[0].status).toBe('announced');await post(store,state,'101','Reset is still propagating.',at+1000);await store.execute('monitorApply',{epoch:state.epoch,postId:'101',recognition:recognition('progress','Reset is still propagating.'),receiptId:await receipt(store,state),now:at+1000});data=await store.execute('optionalData',{module:'monitor',limit:10,offset:0});expect(data.records[0].status).toBe('announced');await post(store,state,'102','All reset for everyone.',at+2000);await store.execute('monitorApply',{epoch:state.epoch,postId:'102',recognition:recognition('confirm','All reset for everyone.'),receiptId:await receipt(store,state),now:at+2000});data=await store.execute('optionalData',{module:'monitor',limit:10,offset:0});expect(data.records).toHaveLength(1);expect(data.records[0].status).toBe('confirmed');expect(data.records[0].posts).toHaveLength(3);}));
 it('holds uncertain or ungrounded claims and preserves manual corrections',()=>fixture(async(store,state)=>{await post(store,state,'100','We may reset later.');await store.execute('monitorApply',{epoch:state.epoch,postId:'100',recognition:{...recognition('confirm','All reset for everyone.'),needsReview:true},receiptId:await receipt(store,state),now:Date.now()});expect((await store.execute('optionalData',{module:'monitor',limit:10,offset:0})).records).toHaveLength(0);}));
 it('checks manual monitor revisions, keeps history, and refuses a later automatic confirmation over a manual decision',()=>fixture(async(store,state)=>{const at=Date.now();await post(store,state,'201','We will reset everyone.',at);await store.execute('monitorApply',{epoch:state.epoch,postId:'201',recognition:recognition('announce','We will reset everyone.'),receiptId:await receipt(store,state),now:at});const event=(await store.execute('optionalData',{module:'monitor',limit:10,offset:0})).records[0];const command={commandId:randomUUID(),expectedRevision:0,eventId:event.id,status:'announced',withdrawn:false,reason:'Human verified still pending',now:at};await store.execute('monitorCorrect',command);await store.execute('monitorCorrect',command);await expect(store.execute('monitorCorrect',{...command,commandId:randomUUID()})).rejects.toThrow('revision conflict');await expect(store.execute('monitorCorrect',{...command,status:'confirmed'})).rejects.toThrow('identity conflict');await post(store,state,'202','All reset for everyone.',at+1000);await store.execute('monitorApply',{epoch:state.epoch,postId:'202',recognition:recognition('confirm','All reset for everyone.'),receiptId:await receipt(store,state),now:at+1000});const preserved=(await store.execute('optionalData',{module:'monitor',limit:10,offset:0})).records[0];expect(preserved).toMatchObject({status:'announced',revision:1});expect(preserved.history.some(h=>h.action==='manual')).toBe(true);}));
 it('holds ungrounded quotes for human review and keeps the review command idempotent',()=>fixture(async(store,state)=>{await post(store,state,'301','We may reset later.');await store.execute('monitorApply',{epoch:state.epoch,postId:'301',recognition:recognition('confirm','All reset for everyone.'),receiptId:await receipt(store,state),now:Date.now()});let data=await store.execute('optionalData',{module:'monitor',limit:10,offset:0});expect(data.records).toHaveLength(0);expect(data.state.reviews[0].recognition.needsReview).toBe(true);const command={postId:'301',commandId:randomUUID(),accepted:false,reason:'Claim not in the source',now:Date.now()};await store.execute('monitorReview',command);await store.execute('monitorReview',command);expect((await store.execute('optionalData',{module:'monitor',limit:10,offset:0})).state.reviewHistory).toHaveLength(1);}));
 it('links acknowledged outage, recovery and a subsequent announced reset without claiming it completed',()=>fixture(async(store,state)=>{const at=Date.now();for(const[id,text,outage,action]of [['401','Codex is down.','outage',null],['402','We will reset everyone.',null,'announce'],['403','Codex has recovered.','recovery',null]]){await post(store,state,id,text,at+Number(id));await store.execute('monitorApply',{epoch:state.epoch,postId:id,recognition:action?recognition(action,text):{...recognition('announce',text),propositions:[],outage},receiptId:await receipt(store,state),now:at+Number(id)});}const data=await store.execute('optionalData',{module:'monitor',limit:10,offset:0});expect(data.records[0].status).toBe('announced');expect(data.state.outages[0]).toMatchObject({id:'401',resetEventId:data.records[0].id});expect(data.state.outages[0].recoveredAt).toBeTruthy();}));

});
