import {describe,it,expect} from 'vitest';
import {createRssCollector} from '../../packages/host/lib/types/sources/rss.js';
import {createWebCollector} from '../../packages/host/lib/types/sources/web-list.js';
import {createJsonCollector} from '../../packages/host/lib/types/sources/json-list.js';
import {Writing,Material,Url} from '../../packages/core/lib/index.js';
const source={id:'fixture',name:'fixture',kind:'rss',config:{feedUrl:'https://example.com/feed'},tier:'T1',participation_mode:'editorial',first_party:true,interval_minutes:60,enabled:true,cursor:null,fail_count:0};
function io(body,status=200,headers={}){return {fetch:async url=>({url,status,headers:new Headers(headers),body:Buffer.from(body),text:()=>body}),credential:()=>null,jina:async()=>{throw new Error('No paid service permitted');}};}
describe('M2 retained parser and identity behavior',()=>{
 it('parses RSS and Atom, retains body/summary differences and validators',async()=>{const rss='<rss><channel><item><title>OpenAI news</title><link>https://example.com/one</link><pubDate>Sun, 04 Oct 2026 00:00:00 GMT</pubDate><description>Summary only</description></item></channel></rss>';const read=await createRssCollector(io(rss,200,{etag:'fixture-v1'})).fetchRss(source);expect(read.candidates[0].title).toBe('OpenAI news');expect(read.candidates[0].bodyStatus).toBe('pending');expect(read.validator.etag).toBe('fixture-v1');const atom='<feed><entry><id>one</id><title>AI research</title><link href="https://example.com/two"/><updated>2026-10-04T00:00:00Z</updated><summary>Research summary</summary></entry></feed>';expect((await createRssCollector(io(atom)).fetchRss(source)).candidates[0].url).toBe('https://example.com/two');});
 it('reuses validators only for matching configuration and treats 304 as no content',async()=>{const rss='<rss><channel><item><title>Fixture</title><link>https://example.com/a</link></item></channel></rss>';let headers;let status=200;const collector=createRssCollector({...io(rss),fetch:async(url,options)=>{headers=options.headers;return {url,status,headers:new Headers({etag:'etag-1'}),body:Buffer.from(status===304?'':rss),text:()=>status===304?'':rss};}});const first=await collector.fetchRss(source);status=304;const next=await collector.fetchRss({...source,cursor:{rss:first.validator}});expect(next.notModified).toBe(true);expect(next.candidates).toEqual([]);expect(new Headers(headers).get('if-none-match')).toBe('etag-1');status=200;await collector.fetchRss({...source,cursor:{rss:first.validator},config:{feedUrl:'https://example.com/other'}});expect(new Headers(headers).get('if-none-match')).toBe(null);});
 it('maps configured JSON paths, dates and ids without executing embedded scripts',async()=>{const s={...source,kind:'json_list',config:{url:'https://example.com/api',itemsPath:'items',titlePaths:['title'],urlTemplate:'https://example.com/items/{id}',publishedAtPath:'time',publishedAtUnit:'epoch_s'}};const result=await createJsonCollector(io(JSON.stringify({items:[{id:'one',title:'AI product',time:1791072000}]}))).fetchJsonList(s);expect(result[0].url).toBe('https://example.com/items/one');expect(result[0].publishedAt.getTime()).toBe(1791072000000);await expect(createJsonCollector(io('{}')).fetchJsonList(s)).rejects.toThrow('array');});
 it('requires useful mapped web links and refuses a broken selector',async()=>{const s={...source,kind:'web_list',config:{url:'https://example.com/blog',itemSelector:'.post',linkSelector:'a',titleSelector:'h2'}};const html='<nav><a href="/">Home</a></nav><div class="post"><a href="/one"><h2>AI announcement</h2></a></div>';const result=await createWebCollector(io(html)).fetchWebList(s);expect(result.map(c=>c.title)).toEqual(['AI announcement']);await expect(createWebCollector(io(html)).fetchWebList({...s,config:{...s.config,itemSelector:'.missing'}})).rejects.toThrow();});
 it('keeps URL identity canonical while rejecting private and mapped-private addresses',()=>{expect(Url.identityKeyForUrl('http://www.example.com/a?utm_source=x')).toBe(Url.identityKeyForUrl('https://example.com/a'));for(const address of ['127.0.0.1','10.0.0.1','169.254.169.254','198.18.0.1','::1','::ffff:127.0.0.1','fc00::1'])expect(Url.isBlockedAddress(address)).toBe(true);});
 it('archives stale and future-time first imports and keeps UNKNOWN evidence behavior',()=>{const now=new Date('2026-10-04T00:00:00Z');expect(Material.decideTimeline(new Date('2026-09-01T00:00:00Z'),now).backfill).toBe(true);expect(Material.decideTimeline(new Date('2026-10-05T00:00:00Z'),now,'first-import').publishedAt).toBe(null);expect(Writing.looksZh('OpenAI 发布新模型')).toBe(true);});
});
