import {describe,it,expect} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {HotstreamSqliteProvider} from '../../packages/storage-sqlite/lib/index.js';
import {CallCoordinator,NewsPipeline} from '../../packages/host/lib/index.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
const require=createRequire(new URL('../../packages/host/package.json',import.meta.url));
const {Context}=await import(require.resolve('@deepseek-ai/cordis'));const {default:LlmRuntime,LlmAdapter}=await import(require.resolve('@deepseek-ai/dsh-llm'));
const fixtureSource={id:'fixture',name:'Isolated integration fixture',kind:'external',config:{},tags:[],tier:'T1',ownerEntityId:'openai',signalGroupId:null,participationMode:'editorial',firstParty:true,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};
const body='OpenAI today releases Fixture. The model is available to developers. '.repeat(15);
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'hotstream-m2-'));const ctx=new Context();new LlmRuntime(ctx);const chunks=[];const responses=[];class Mock extends LlmAdapter{async resolveModel(provider,model){return {provider,id:model,name:'Test model'};}async listModels(){return [];}async *stream(options){chunks.push(options);const text=JSON.stringify(responses.shift());yield {type:'block-start',index:0,blockType:'text'};yield {type:'text-delta',index:0,text};yield {type:'block-end',index:0,block:{type:'text',text}};yield {type:'usage',usage:{inputTokens:10,outputTokens:5}};yield {type:'finish',reason:{kind:'stop'}};}}
 ctx.llm.registerAdapter(['test'],new Mock());const store=new HotstreamSqliteProvider(join(root,'news.sqlite'));const signal=new AbortController();const calls=new CallCoordinator(ctx,store,join(root,'audit'),signal.signal);const pipeline=new NewsPipeline(store,calls,{fetch:async()=>{throw new Error('No network permitted');}},{});try{const state=await store.execute('initialize',{commandId:randomUUID(),settings:defaultSettings({provider:'test',model:'test-model'}),sources:[fixtureSource],now:Date.now()});await fn({store,calls,pipeline,state,chunks,responses});}finally{signal.abort();await calls.close();await store.close();await ctx.fiber.dispose();await rm(root,{recursive:true,force:true});}}
async function ingest(f,url='https://example.com/fixture'){const now=Date.now();const queued=await f.store.execute('enqueue',{kind:'collect',subject:'fixture',key:'collect:'+url,epoch:f.state.epoch,inputRevision:1,configRevision:f.state.revision,payload:{settings:f.state.settings},priority:100,maxAttempts:3,dueAt:now});const job=await f.store.execute('claim',{kinds:['collect'],owner:'test',now,leaseMs:600000});await f.store.execute('collection',{jobId:job.id,owner:'test',epoch:f.state.epoch,now,sourceId:'fixture',sourceRevision:1,items:[{url,title:'OpenAI releases Fixture',identityKey:null,author:null,language:'en',publishedAt:now,excerpt:null,bodyHtml:null,bodyText:body,bodyStatus:'ok',media:[],xPost:null,raw:null,backfillReason:null}],cursor:{initializedAt:new Date(now).toISOString()},receiptIds:[]});return (await f.store.execute('jobs',{limit:100,offset:0})).find(j=>j.kind==='prefilter').subject;}
async function stage(f,kind,response){f.responses.push(response);const job=await f.store.execute('claim',{kinds:[kind],owner:'test',now:Date.now(),leaseMs:600000});expect(job).not.toBe(null);await f.pipeline.run(job,'test');}
const structure={scope:'single',category:'ai-models',tags:['模型发布'],subjects:['openai'],fact:{title:'OpenAI 发布 Fixture',subject:'OpenAI',action:'发布',object:'Fixture',occurredAt:null,evidence:'OpenAI today releases Fixture.',conditions:[]}};
const writing={itemType:'model_release',authorRole:'principal',tags:['模型发布'],editorialJudgment:'官方发布',titleZh:'OpenAI 发布 Fixture',summaryZh:'OpenAI 发布 Fixture，现已向开发者开放。模型由原文所述接口提供。'};
describe('M2 editorial and publication transactions',()=>{
 it('runs independent score slots and gates selection on completed grouping',()=>fixture(async f=>{const id=await ingest(f);await stage(f,'prefilter',{label:'UNKNOWN',reason:'wide recall'});await stage(f,'score1',{attentionScore:60});await stage(f,'score2',{attentionScore:90});await stage(f,'structure',structure);await stage(f,'writing',writing);let p=await f.store.execute('detail',{id});expect(p.selected).toBe(false);expect(p.selectionCandidate).toBe(true);expect(p.score).toBe(75);const scoring=f.chunks.filter(c=>c.system.includes('attentionScore'));expect(scoring).toHaveLength(2);expect(scoring[0].messages[0].content).toEqual(scoring[1].messages[0].content);expect(scoring[1].messages[0].content[0].text).not.toMatch(/attentionScore["']?\s*:\s*60/);await stage(f,'group',{query:'single',decisions:[],selection:{addsValue:true,reason:'first release'}});p=await f.store.execute('detail',{id});expect(p.selected).toBe(true);expect(p.factId).not.toBe(null);expect(p.storyId).not.toBe(null);expect(p.body).toBe(null);expect((await f.store.execute('page',{view:'selected',query:'OpenAI',category:null,topic:null,limit:30,offset:0})).total).toBe(1);expect((await f.store.execute('receipts',{limit:100,offset:0})).every(r=>r.state==='completed')).toBe(true);}));
 it('BLOCK stops downstream work; UNKNOWN remains processable',()=>fixture(async f=>{const id=await ingest(f);await stage(f,'prefilter',{label:'BLOCK',reason:'outside industry'});expect((await f.store.execute('jobs',{limit:100,offset:0})).filter(j=>j.state==='queued')).toHaveLength(0);expect(await f.store.execute('detail',{id})).toBe(null);}));
 it('keeps bookmarks while all read surfaces obey withdrawal',()=>fixture(async f=>{const id=await ingest(f);for(const [kind,value]of [['prefilter',{label:'PASS',reason:''}],['score1',{attentionScore:80}],['score2',{attentionScore:80}],['structure',structure],['writing',writing],['group',{query:'single',decisions:[],selection:{addsValue:true,reason:'first'}}]])await stage(f,kind,value);await f.store.execute('marks',{id,bookmarked:true,read:true,now:Date.now()});expect((await f.store.execute('page',{view:'bookmarks',query:'',category:null,topic:null,limit:30,offset:0})).total).toBe(1);await f.store.execute('override',{id,expectedRevision:0,visibility:'withdrawn',fields:{},reason:'fixture withdrawal',now:Date.now()});expect(await f.store.execute('detail',{id})).toBe(null);const bookmarks=await f.store.execute('page',{view:'bookmarks',query:'',category:null,topic:null,limit:30,offset:0});expect(bookmarks.total).toBe(1);expect(bookmarks.items[0]).toMatchObject({visibility:'withdrawn',title:'',summary:'',body:null,bookmarked:true});}));
});
