import {describe,it,expect} from 'vitest';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {SourceCollectors,CallCoordinator} from '../../packages/host/lib/index.js';import {HotstreamSqliteProvider} from '../../packages/storage-sqlite/lib/index.js';import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';import {Url} from '../../packages/core/lib/index.js';
const source={id:'fixture',name:'Provider fixture',kind:'mp_account',config:{ghid:'fixture-account'},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'editorial',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'hotstream-provider-'));const store=new HotstreamSqliteProvider(join(root,'news.sqlite'));const control=new AbortController();const ctx={get:key=>key==='credentials'?{}:undefined,credentials:{readRecord:async()=>({kind:'api-key',key:'HOTSTREAM_NON_SECRET_FIXTURE'})}};const calls=new CallCoordinator(ctx,store,join(root,'audit'),control.signal);try{const state=await store.execute('initialize',{commandId:randomUUID(),settings:defaultSettings({provider:'mock',model:'mock'}),sources:[source],now:Date.now()});await store.execute('setBudget',{service:'dajiala',policy:{perMinute:100,perHour:100,per24Hours:100}});const job={id:randomUUID(),kind:'collect',key:'provider',subject:source.id,epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{collectAt:Date.now()},leaseOwner:null,leaseUntil:null,priority:100,state:'running',attempts:1,maxAttempts:3,dueAt:Date.now(),error:null};await fn({store,calls,ctx,state,job});}finally{control.abort();await calls.close();await store.close();await rm(root,{recursive:true,force:true});}}
const response=(url,body,status=200)=>({url,status,headers:new Headers({'content-type':'application/json'}),body:Buffer.from(body),text:()=>body});
describe('retained paid provider protocols',()=>{
 it('uses the seven-day/eight-new-post WeChat path and records actual list/body cost',()=>fixture(async f=>{const calls=[];const now=Date.now();const posts=Array.from({length:10},(_,i)=>({position:i,url:'https://mp.weixin.qq.com/s?__biz=fixture&mid='+i+'&idx=1&sn=s'+i,title:'Post '+i,post_time:Math.floor((now-i*60000)/1000),sn:'s'+i}));posts.push({url:'https://mp.weixin.qq.com/s?__biz=old&mid=999&idx=1&sn=old',title:'Old',post_time:Math.floor((now-8*86400000)/1000)});const network={fetch:async(url,opts)=>{calls.push({url,opts});return response(url,JSON.stringify(url.includes('post_history')?{code:0,data:posts,remain_money:10,cost_money:0.14}:{code:0,content:'<p>真实接口结构的离线正文</p>',author:'Fixture',desc:'摘要',cost_money:0.03}));}};const read=await new SourceCollectors(f.ctx,network,f.calls,f.store,{fetch:async()=>{throw new Error('Paid provider must not use the public news proxy');}}).collect(f.job,source);expect(read.items).toHaveLength(8);expect(read.items.every(i=>i.bodyStatus==='ok'&&i.language==='zh')).toBe(true);expect(read.items.some(i=>i.title==='Old')).toBe(false);expect(read.cursor.lastCheckedAt).toBeDefined();expect(read.cursor.remainMoney).toBe(10);expect(read.foundCount).toBe(11);expect(calls).toHaveLength(9);const receipts=await f.store.execute('receipts',{limit:100,offset:0});expect(receipts.every(r=>r.state==='received')).toBe(true);for(const receipt of receipts){const attempts=await f.store.execute('receiptAttempts',{id:receipt.id,limit:10,offset:0});expect(attempts[0].costBasis).toBe('actual');expect(attempts[0].currency).toBe('CNY');expect(attempts[0].response.httpStatus).toBe(200);}expect(JSON.stringify(receipts.map(r=>r.request))).not.toContain('HOTSTREAM_NON_SECRET_FIXTURE');}));
 it('retains malformed received JSON and replays it without billing another request',()=>fixture(async f=>{let attempts=0;const network={fetch:async url=>{attempts++;return response(url,'{broken');}};const collector=new SourceCollectors(f.ctx,network,f.calls,f.store);await expect(collector.collect(f.job,source)).rejects.toThrow('invalid JSON');await expect(collector.collect(f.job,source)).rejects.toThrow('invalid JSON');expect(attempts).toBe(1);const receipts=await f.store.execute('receipts',{limit:10,offset:0});expect(receipts[0].state).toBe('received');expect(receipts[0].response.body).toBe('{broken');}));
 it('preserves a definite HTTP rejection and classifies it separately from unknown dispatch',()=>fixture(async f=>{const network={fetch:async url=>response(url,'rate limited',429)};await expect(new SourceCollectors(f.ctx,network,f.calls,f.store).collect(f.job,source)).rejects.toMatchObject({status:429,retryable:true});const receipt=(await f.store.execute('receipts',{limit:10,offset:0}))[0];expect(receipt.state).toBe('failed');expect((await f.store.execute('receiptAttempts',{id:receipt.id,limit:10,offset:0}))[0].response).toMatchObject({httpStatus:429,body:'rate limited'});}));
});
describe('injected DNS keeps the public-address contract',()=>{
 it('rejects private answers before URL dispatch and at socket lookup',async()=>{await expect(Url.assertPublicUrl('https://example.com',false,false,async()=>[{address:'127.0.0.1',family:4}])).rejects.toThrow('private');await expect(new Promise((resolve,reject)=>Url.guardedLookup('example.com',{all:true},error=>error?reject(error):resolve(),async()=>[{address:'::ffff:127.0.0.1',family:6}]))).rejects.toThrow('private');await expect(Url.assertPublicUrl('https://localhost',false,false,async()=>[{address:'93.184.216.34',family:4}])).rejects.toThrow('Blocked host');});
});
