import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';
import {defaultSettings,settingsSchema} from '../../packages/contracts/lib/types/runtime.js';
import {SourceCollectors} from '../../packages/host/lib/types/sources/collect.js';
import {anonymousPublicRead} from '../../packages/host/lib/types/network.js';
const source=(id,now)=>({id,name:id,kind:'rss',config:{feedUrl:'https://example.com/'+id},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'editorial',firstParty:true,intervalMinutes:120,siteFulltext:true,enabled:true,revision:1,cursor:{initializedAt:new Date(now-60000).toISOString()},health:'ok',lastOkAt:now-60000,nextDueAt:now+3600000,lastError:null,createdAt:now-60000});
describe('public news routing',()=>{
 it('routes RSS through the public transport without invoking a paid provider',async()=>{const now=Date.now(),seen=[];const xml=`<rss><channel><item><title>AI research update</title><link>https://example.com/news</link><pubDate>${new Date(now).toUTCString()}</pubDate><description>Research summary</description></item></channel></rss>`;const publicNetwork={fetch:async(url)=>{seen.push(url);return {url,status:200,headers:new Headers({'content-type':'application/rss+xml'}),body:Buffer.from(xml),text:()=>xml};}},direct={fetch:async()=>{throw new Error('Unexpected direct/provider call');}};const collector=new SourceCollectors({get:()=>undefined},direct,{}, {},publicNetwork);const result=await collector.collect({dueAt:now,payload:{collectAt:now}},source('fixture',now));expect(seen).toEqual(['https://example.com/fixture']);expect(result.items.map(item=>item.title)).toEqual(['AI research update']);expect(result.receiptIds).toEqual([]);});
 it('keeps credentialed requests, POSTs and secret-bearing URLs off the public proxy',()=>{expect(anonymousPublicRead('https://example.com/rss',{headers:{'if-none-match':'etag'}})).toBe(true);for(const options of [{headers:{authorization:'fixture'}},{headers:{'x-api-key':'fixture'}},{headers:{cookie:'fixture'}},{method:'POST',body:'{}'}])expect(anonymousPublicRead('https://example.com/data',options)).toBe(false);expect(anonymousPublicRead('https://example.com/data?access_token=fixture')).toBe(false);const old=defaultSettings({provider:'mock',model:'mock'});delete old.network.publicProxyUrl;expect(settingsSchema.parse(old).network.publicProxyUrl).toBeNull();});
 it('requeues failed RSS with new frozen settings and preserves healthy work and extraction attempts',()=>{const db=new DatabaseSync(':memory:');try{const store=new HotstreamDatabase(db),now=Date.now(),settings=defaultSettings({provider:'mock',model:'mock'});const state=store.execute('initialize',{commandId:randomUUID(),settings,sources:[source('failed',now),source('healthy',now)],now});const enqueue=(kind,subject)=>store.execute('enqueue',{kind,subject,key:kind+':'+subject,epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{settings},priority:10,maxAttempts:3,dueAt:now});const failed=enqueue('collect','failed'),healthy=enqueue('collect','healthy'),extract=enqueue('extract','existing-article');store.execute('sourceFailure',{id:'failed',revision:1,epoch:state.epoch,now,error:'connection timeout',blocked:false,retryAt:now+600000});store.execute('configure',{revision:state.revision,settings:{...settings,network:{...settings.network,publicProxyUrl:'http://127.0.0.1:7897'}},now:now+1});const jobs=store.execute('jobs',{limit:100,offset:0});expect(jobs.find(j=>j.id===failed.id).state).toBe('cancelled');for(const id of [healthy.id,extract.id]){const old=jobs.find(j=>j.id===id);expect(old.state).toBe('queued');expect(old.payload.settings.network.publicProxyUrl).toBeNull();}expect(store.execute('schedule',{now:now+1})).toBe(1);const next=store.execute('jobs',{limit:100,offset:0}).find(j=>j.kind==='collect'&&j.subject==='failed'&&j.state==='queued');expect(next.payload.settings.network.publicProxyUrl).toBe('http://127.0.0.1:7897');expect(next.id).not.toBe(failed.id);}finally{db.close();}});
 it.each([1,3])('recovers a late old-route RSS failure with maxAttempts=%s without rewriting its history',maxAttempts=>{const db=new DatabaseSync(':memory:');try{const store=new HotstreamDatabase(db),now=Date.now(),settings=defaultSettings({provider:'mock',model:'mock'});const state=store.execute('initialize',{commandId:randomUUID(),settings,sources:[source('late-failure',now)],now});store.execute('enqueue',{kind:'collect',subject:'late-failure',key:'old-route',epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{settings},priority:10,maxAttempts,dueAt:now});const running=store.execute('claim',{kinds:['collect'],owner:'old-reader',now,leaseMs:600000});store.execute('configure',{revision:state.revision,settings:{...settings,network:{...settings.network,publicProxyUrl:'http://127.0.0.1:7897'}},now:now+1});expect(store.execute('jobs',{limit:10,offset:0}).find(j=>j.id===running.id).state).toBe('running');store.execute('sourceFailure',{id:'late-failure',revision:1,epoch:state.epoch,now:now+2,error:'old direct connection timed out',blocked:false,retryAt:now+600000});store.execute('fail',{id:running.id,owner:'old-reader',epoch:state.epoch,now:now+2,error:'old direct connection timed out',blocked:false,retryAt:now+600000});expect(store.execute('schedule',{now:now+3})).toBe(1);const jobs=store.execute('jobs',{limit:10,offset:0});expect(jobs.find(j=>j.id===running.id).state).toBe(maxAttempts===1?'failed':'cancelled');const fresh=jobs.find(j=>j.state==='queued');expect(fresh.payload.settings.network.publicProxyUrl).toBe('http://127.0.0.1:7897');expect(fresh.id).not.toBe(running.id);expect(store.execute('schedule',{now:now+4})).toBe(0);}finally{db.close();}});

});
