import {describe,it,expect,vi} from 'vitest';
import {mkdtemp,rm,readdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {HotstreamSqliteProvider} from '../../packages/storage-sqlite/lib/index.js';
import {CallCoordinator} from '../../packages/host/lib/index.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
const require=createRequire(new URL('../../packages/host/package.json',import.meta.url));
const {Context}=await import(require.resolve('@deepseek-ai/cordis'));
const {default:LlmRuntime,LlmAdapter,LlmError}=await import(require.resolve('@deepseek-ai/dsh-llm'));
async function fixture(work){const root=await mkdtemp(join(tmpdir(),'hotstream-recovery-'));let store=new HotstreamSqliteProvider(join(root,'news.sqlite'));const ctx=new Context();new LlmRuntime(ctx);const seen=[];const failures=[];class Mock extends LlmAdapter{async resolveModel(provider,model){return {provider,id:model,name:'fixture'};}async listModels(){return [];}async *stream(options){seen.push(options);if(failures.length)throw failures.shift();const text='durable response';yield {type:'block-start',index:0,blockType:'text'};yield {type:'text-delta',index:0,text};yield {type:'block-end',index:0,block:{type:'text',text}};yield {type:'usage',usage:{inputTokens:3,outputTokens:2}};yield {type:'finish',reason:{kind:'stop'}};}}
ctx.llm.registerAdapter(['fixture'],new Mock());const lifetime=new AbortController();let calls=new CallCoordinator(ctx,store,join(root,'audit'),lifetime.signal);const settings=defaultSettings({provider:'fixture',model:'news'});const seed={id:'s',name:'fixture',kind:'external',config:{},tags:[],tier:'T1',firstParty:true,ownerEntityId:null,signalGroupId:null,participationMode:'editorial',intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};const state=await store.execute('initialize',{commandId:randomUUID(),settings,sources:[seed],now:Date.now()});
const job={id:randomUUID(),key:'frozen',subject:'fixture',kind:'score1',epoch:state.epoch,inputRevision:1,configRevision:state.revision,payload:{},state:'running',attempts:1,maxAttempts:3,priority:1,dueAt:Date.now(),leaseOwner:null,leaseUntil:null,error:null};const input={stage:'score1',system:'original system',user:'original user',maxTokens:200,temperature:0.2,json:false};
try{await work({root,ctx,store,calls,job,settings,input,seen,failures,seed,restart:async()=>{await calls.close();await store.close();store=new HotstreamSqliteProvider(join(root,'news.sqlite'));calls=new CallCoordinator(ctx,store,join(root,'audit'),lifetime.signal);return {store,calls};}});}finally{lifetime.abort();await calls.close();await store.close();await ctx.fiber.dispose();await rm(root,{recursive:true,force:true});}}
describe('immutable dispatch and audit recovery',()=>{
 it('archives a late response but does not return it to business work after task cancellation',()=>fixture(async f=>{const control=new AbortController(),detach=f.calls.bindJob(f.job.id,control.signal);const execute=f.store.execute.bind(f.store);f.store.execute=async(operation,input)=>{if(operation==='receive')control.abort(new Error('Batch cancelled'));return execute(operation,input);};try{await expect(f.calls.model(f.job,f.settings,f.input)).rejects.toThrow('Batch cancelled');const receipt=(await execute('receipts',{limit:100,offset:0}))[0];expect(receipt.state).toBe('received');expect((await execute('receiptAttempts',{id:receipt.id,limit:100,offset:0}))[0]).toMatchObject({auditSettled:true});expect(f.seen).toHaveLength(1);}finally{detach();f.store.execute=execute;}}));
 it('applies the grouping stage route to its independent relation review substage',()=>fixture(async f=>{const settings={...f.settings,model:{...f.settings.model,stageOverrides:{group:{provider:'fixture',model:'group-fixed'}}}};const result=await f.calls.model(f.job,settings,{...f.input,stage:'group-review:fact'});expect(result.model).toBe('group-fixed');expect(f.seen[0].model).toBe('group-fixed');}));
 it('recovers the exact response from official Session persistence after SQLite receipt failure, without another dispatch',()=>fixture(async f=>{const execute=f.store.execute.bind(f.store);f.store.execute=async(operation,input)=>{if(['receive','archiveResponse'].includes(operation))throw Object.assign(new Error('database or disk is full'),{code:'HOTSTREAM_STORAGE_UNAVAILABLE'});return execute(operation,input);};await expect(f.calls.model(f.job,f.settings,f.input)).rejects.toThrow('disk is full');f.store.execute=execute;expect(f.seen).toHaveLength(1);const restart=await f.restart();await restart.calls.repairAudits();const result=await restart.calls.model(f.job,f.settings,f.input);expect(result).toMatchObject({reused:true,text:'durable response'});expect(f.seen).toHaveLength(1);expect((await restart.store.execute('receiptAttempts',{id:result.receiptId,limit:100,offset:0}))[0]).toMatchObject({auditSettled:true,outcome:'received'});}));
 it('records unknown billing separately, forbids automatic release and requires a current attempt to authorize retry',()=>fixture(async f=>{const now=Date.now();const reserve=await f.store.execute('reserve',{key:'unknown-fixture',service:'llm',epoch:f.job.epoch,requestHash:'f'.repeat(64),request:{},now});const id=reserve.receipt.id;await f.store.execute('sent',{id,attempt:1,epoch:f.job.epoch,auditRef:'test-only',now});await f.store.execute('settle',{id,attempt:1,epoch:f.job.epoch,state:'unknown',error:'lost connection',now});const command={id,attempt:1,commandId:randomUUID(),outcome:'billed',reason:'Checked test billing receipt',cost:null,currency:null,now};await f.store.execute('confirmUnknown',command);await f.store.execute('confirmUnknown',command);await expect(f.store.execute('confirmUnknown',{...command,reason:'different'})).rejects.toThrow('identity conflict');expect((await f.store.execute('recover',{now:now+3600000,startup:false})).released).toBe(0);await expect(f.store.execute('confirmRetry',{id,attempt:2,commandId:randomUUID(),acknowledged:true,now})).rejects.toThrow('revision conflict');await f.store.execute('confirmRetry',{id,attempt:1,commandId:randomUUID(),acknowledged:true,now});expect((await f.store.execute('findReceipt',{key:'unknown-fixture'})).state).toBe('failed');}));
 it('retains and exposes unresolved billing after clear, permits confirmation, and refuses a retry of the old epoch',()=>fixture(async f=>{const now=Date.now(),reservation=await f.store.execute('reserve',{key:'old-unknown',service:'llm',epoch:f.job.epoch,requestHash:'a'.repeat(64),request:{},now}),id=reservation.receipt.id;await f.store.execute('sent',{id,attempt:1,epoch:f.job.epoch,auditRef:'test-only',now});await f.store.execute('clear',{commandId:randomUUID(),now});expect((await f.store.execute('callSummary',{limit:100,offset:0})).find(row=>row.id===id)).toMatchObject({state:'unknown',epoch:f.job.epoch});await f.store.execute('confirmUnknown',{id,attempt:1,commandId:randomUUID(),outcome:'not-billed',reason:'Checked old attempt',cost:null,currency:null,now});await expect(f.store.execute('confirmRetry',{id,attempt:1,commandId:randomUUID(),acknowledged:true,now})).rejects.toThrow('Stale');expect((await f.store.execute('callAttempts',{id,attempt:1,limit:1,offset:0})).attempts[0].confirmation.outcome).toBe('not-billed');}));
 it('transfers attempt summaries first and reads the raw stream only for the chosen attempt',()=>fixture(async f=>{const answer=await f.calls.model(f.job,f.settings,f.input);const summary=await f.store.execute('callAttempts',{id:answer.receiptId,attempt:null,limit:50,offset:0});expect(summary.total).toBe(1);expect(summary.attempts[0]).toMatchObject({request:null,response:null,auditSettled:true});const detail=await f.store.execute('callAttempts',{id:answer.receiptId,attempt:1,limit:1,offset:0});expect(detail.attempts[0].request.messages).toHaveLength(1);expect(detail.attempts[0].response).toHaveLength(5);}));
 it('retains resolved dispatch across restart and different proposed route and input',()=>fixture(async f=>{f.failures.push(new LlmError('explicit rejection','HTTP_ERROR',{status:503}));await expect(f.calls.model(f.job,f.settings,f.input)).rejects.toThrow('explicit rejection');const original=f.seen[0];expect(Object.isFrozen(original)).toBe(true);expect(Object.isFrozen(original.messages)).toBe(true);const restart=await f.restart();const answer=await restart.calls.model(f.job,{...f.settings,model:{provider:'missing',model:'different',stageOverrides:{}}},{...f.input,system:'changed',user:'changed',maxTokens:9});expect(answer.text).toBe('durable response');expect(f.seen[1]).toMatchObject({provider:original.provider,model:original.model,maxTokens:original.maxTokens,system:original.system,messages:original.messages});const attempts=await restart.store.execute('receiptAttempts',{id:answer.receiptId,limit:10,offset:0});expect(attempts).toHaveLength(2);expect(attempts[0]).toMatchObject({outcome:'failed'});expect(attempts[0].response).toHaveLength(1);expect(attempts[1]).toMatchObject({outcome:'received',auditSettled:true,usage:{inputTokens:3,outputTokens:2}});expect(attempts[1].response).toHaveLength(5);}));
 it('repairs failed settlement after restart without another model attempt and stays idempotent',()=>fixture(async f=>{const settlement=vi.spyOn(f.calls.audits,'settle').mockRejectedValueOnce(new Error('injected audit flush failure'));await expect(f.calls.model(f.job,f.settings,f.input)).rejects.toThrow('injected');settlement.mockRestore();expect(f.seen).toHaveLength(1);const restart=await f.restart();await restart.calls.repairAudits();const result=await restart.calls.model(f.job,f.settings,f.input);await restart.calls.repairAudits();expect(result.reused).toBe(true);expect(f.seen).toHaveLength(1);const attempts=await restart.store.execute('receiptAttempts',{id:result.receiptId,limit:10,offset:0});expect(attempts[0].auditSettled).toBe(true);const files=await readdir(join(f.root,'audit'),{recursive:true});const path=files.find(p=>p.endsWith('.jsonl'));const lines=(await readFile(join(f.root,'audit',path),'utf8')).trim().split('\n').map(s=>JSON.parse(s));expect(lines.filter(r=>r.type==='hotstream/llm-request')).toHaveLength(1);expect(lines.filter(r=>r.type==='hotstream/llm-settlement')).toHaveLength(1);}));
 it('blocks initialization and writes while clear is draining, and can finish after restart',()=>fixture(async f=>{const commandId=randomUUID();const deleting=await f.store.execute('beginClear',{commandId,now:Date.now()});expect(deleting).toMatchObject({deleting:true,initialized:false,epoch:f.job.epoch+1});await expect(f.calls.model(f.job,f.settings,f.input)).rejects.toThrow('Stale');const restart=await f.restart();expect((await restart.store.execute('state',{})).deleting).toBe(true);await expect(restart.store.execute('initialize',{commandId:randomUUID(),settings:f.settings,sources:[f.seed],now:Date.now()})).rejects.toThrow('draining');const cleared=await restart.store.execute('clear',{commandId,now:Date.now()});expect(cleared).toMatchObject({deleting:false,initialized:false,epoch:deleting.epoch});}));
});
