import {describe,it,expect,vi} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';
import {defaultSettings} from '../../packages/contracts/lib/types/runtime.js';
import {ReportComposer} from '../../packages/host/lib/types/reports.js';
import {seedSqlite,at,sources} from '../golden/fixture.mjs';
async function fixture(work){const db=new DatabaseSync(':memory:'),runtime=new HotstreamDatabase(db);const settings={...defaultSettings({provider:'fixture',model:'fixture'}),autoCollectEnabled:false};runtime.execute('initialize',{commandId:randomUUID(),settings,sources:[{...sources[0],id:'placeholder',enabled:false}],now:at});seedSqlite(db);const store={execute:async(name,input)=>runtime.execute(name,input),close:async()=>{}};const calls={model:vi.fn(async()=>{const now=Date.now(),reservation=await store.execute('reserve',{key:randomUUID(),service:'llm',epoch:0,requestHash:'fixture',request:{stage:'report'},now});const id=reservation.receipt.id;await store.execute('sent',{id,epoch:0,auditRef:'fixture',now});await store.execute('receive',{id,epoch:0,response:[],usage:{},now});return {text:JSON.stringify({overview:'虚构公司发布 999999 款产品。',sections:{}}),receiptId:id};})};try{await work({db,runtime,store,settings,calls,composer:new ReportComposer(store,calls)});}finally{db.close();}}
async function job(f,kind,key){const state=await f.store.execute('state',{}),now=Date.now();await f.store.execute('enqueue',{kind:'report',subject:kind+':'+key,key:randomUUID(),epoch:0,inputRevision:0,configRevision:state.revision,payload:{settings:f.settings,kind,key},priority:100,maxAttempts:3,dueAt:now});return await f.store.execute('claim',{kinds:['report'],owner:'fixture',now,leaseMs:600000});}
async function composeDaily(f){const task=await job(f,'daily','2026-10-04');await f.composer.compose(task,f.settings);await f.store.execute('finish',{id:task.id,owner:'fixture',epoch:0,now:Date.now(),result:{}});return (await f.store.execute('reports',{kind:'daily',limit:30,offset:0}))[0];}
describe('durable issue composition and controlled revision',()=>{
 it('saves one Beijing daily issue with zero model calls',()=>fixture(async f=>{const report=await composeDaily(f);expect(report.key).toBe('2026-10-04');expect(report.windowEnd).toBe(at);expect(report.windowStart).toBe(at-86400000);expect(f.calls.model).not.toHaveBeenCalled();await composeDaily(f);expect((await f.store.execute('reports',{kind:'daily',limit:30,offset:0}))).toHaveLength(1);}));
 it('compiles weekly membership from daily issues and rejects ungrounded prose',()=>fixture(async f=>{await composeDaily(f);const task=await job(f,'weekly','2026-W40');await f.composer.compose(task,f.settings);const weekly=(await f.store.execute('reports',{kind:'weekly',limit:30,offset:0}))[0];expect(weekly.content.overview).toBeNull();expect(weekly.content.coverage).toMatchObject({dailyIssues:1,expectedDailyIssues:7,complete:false});expect(weekly.coverage).toBe('incomplete');expect(JSON.stringify(weekly.content.sections)).not.toContain('999999');expect(weekly.content.storyOrder.length).toBeGreaterThan(0);}));
 it('records revisions and refuses a stale recompile after an editor wins the race',()=>fixture(async f=>{const report=await composeDaily(f),commandId=randomUUID();await f.store.execute('reportRegenerate',{id:report.id,expectedRevision:1,commandId,reason:'verified new wording',now:Date.now()});const queued=await f.store.execute('claim',{kinds:['report'],owner:'fixture',now:Date.now(),leaseMs:600000});await f.composer.compose(queued,f.settings);expect((await f.store.execute('report',{id:report.id})).revision).toBe(2);expect(await f.store.execute('reportRevisions',{id:report.id})).toMatchObject([{revision:1,reason:'verified new wording'}]);await expect(f.composer.compose(queued,f.settings)).rejects.toThrow('revision conflict');}));
 it('updates saved report wording and removes withdrawn entries and old overview text',()=>fixture(async f=>{const report=await composeDaily(f),id=report.content.leadItemId;await f.store.execute('override',{id,expectedRevision:0,visibility:'withdrawn',fields:{},reason:'fixture withdrawal',now:Date.now()});const revised=await f.store.execute('report',{id:report.id});expect(revised.content.leadItemId).not.toBe(id);expect(JSON.stringify(revised.content.sections)).not.toContain('"itemId":"'+id+'"');expect(revised.content.overview).toBeNull();}));
 it('does not treat received-response audit failure as a free prose fallback',()=>fixture(async f=>{await composeDaily(f);f.calls.model.mockRejectedValueOnce(new Error('Audit settlement flush failed'));const task=await job(f,'weekly','2026-W40');await expect(f.composer.compose(task,f.settings)).rejects.toThrow('flush failed');expect(await f.store.execute('reports',{kind:'weekly',limit:30,offset:0})).toHaveLength(0);}));
});
