import { describe,it,expect } from 'vitest';
import { mkdtemp,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID,createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { HotstreamSqliteProvider } from '../../packages/storage-sqlite/lib/index.js';
import { defaultSettings } from '../../packages/contracts/lib/types/runtime.js';
const seeds=JSON.parse(await readFile(new URL('../../industry/ai/sources.snapshot.json',import.meta.url),'utf8')).sources.map(s=>({id:s.id,name:s.name,kind:s.kind,config:s.config,tags:s.tags,tier:s.tier,ownerEntityId:s.owner_entity_id,signalGroupId:null,participationMode:s.participation_mode,firstParty:false,intervalMinutes:s.interval_minutes,siteFulltext:s.site_fulltext,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:0,lastError:null}));
const hash=createHash('sha256').update('exact request').digest('hex');
const now=Date.parse('2026-10-04T00:00:00Z');
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'hotstream-m1-'));let store=new HotstreamSqliteProvider(join(root,'hotstream.sqlite'));try{await fn(store,async()=>{await store.close();store=new HotstreamSqliteProvider(join(root,'hotstream.sqlite'));return store;});}finally{await store.close();await rm(root,{recursive:true,force:true});}}
async function initialize(store){return store.execute('initialize',{commandId:randomUUID(),sources:seeds,settings:defaultSettings({provider:'mock',model:'news'}),now});}
function job(epoch,key='one'){return {kind:'score1',subject:'article:a',key,epoch,inputRevision:1,configRevision:2,payload:{prompt:'unchanged',route:{provider:'mock',model:'news'}},priority:90,maxAttempts:3,dueAt:now};}
function request(epoch,key='one'){return {key,service:'llm',epoch,requestHash:hash,request:{prompt:'exact request'},now};}
describe('M1 transactional runtime',()=>{
 it('does not notify or advance data revision on idle maintenance and ignores paused source wake times',()=>fixture(async store=>{let state=await initialize(store);state=await store.execute('configure',{revision:state.revision,settings:{...state.settings,autoCollectEnabled:false},now});const changes=[];const detach=store.subscribe(op=>changes.push(op));const before=(await store.execute('state',{})).dataRevision;expect(await store.execute('schedule',{now:now+1000})).toBe(0);expect(await store.execute('claim',{kinds:['group'],owner:'idle',now:now+1000,leaseMs:10000})).toBeNull();expect(await store.execute('recover',{now:now+1000,startup:false})).toEqual({jobs:0,unknown:0,released:0});expect((await store.execute('nextWake',{})).at).toBeNull();expect((await store.execute('state',{})).dataRevision).toBe(before);expect(changes).toEqual([]);detach();}));
 it('does not wake for model jobs while processing is paused but still admits explicit free ingest',()=>fixture(async store=>{let state=await initialize(store);state=await store.execute('configure',{revision:state.revision,settings:{...state.settings,autoCollectEnabled:false,processing:{enabled:false}},now});await store.execute('enqueue',job(state.epoch));expect((await store.execute('nextWake',{})).at).toBeNull();expect(await store.execute('claim',{kinds:['score1'],owner:'paused',now,leaseMs:10000})).toBeNull();await store.execute('enqueue',{...job(state.epoch,'free-ingest'),kind:'ingest',dueAt:now+5000});expect((await store.execute('nextWake',{})).at).toBe(now+5000);}));
 it('caches settings and source commands, rejects identity changes, and versions edited industry configuration',()=>fixture(async store=>{let state=await initialize(store);const command={commandId:randomUUID(),revision:state.revision,settings:{...state.settings,industry:{...state.settings.industry,promptOverrides:{prefilter:'New controlled prompt'}}},now};const changed=await store.execute('configure',command);expect(changed.settings.industry.revision).toBe(2);expect(await store.execute('configure',command)).toEqual(changed);await expect(store.execute('configure',{...command,settings:state.settings})).rejects.toThrow('identity');const source=(await store.execute('sources',{}))[0],save={commandId:randomUUID(),source:{...source,name:'Changed source name'},expectedRevision:source.revision,now};const first=await store.execute('saveSource',save),version=(await store.execute('state',{})).dataRevision;expect(await store.execute('saveSource',save)).toEqual(first);expect((await store.execute('state',{})).dataRevision).toBe(version);await expect(store.execute('saveSource',{...save,source})).rejects.toThrow('identity');const remove={commandId:randomUUID(),id:source.id,expectedRevision:first.revision,now};expect(await store.execute('removeSource',remove)).toBe(true);expect(await store.execute('removeSource',remove)).toBe(true);}));
 it('keeps External identity fixed even after a failed batch',()=>fixture(async store=>{const state=await initialize(store),input={...job(state.epoch,'external-history'),kind:'ingest',payload:{items:[{title:'same content'}]}};const queued=await store.execute('enqueue',input),claimed=await store.execute('claim',{kinds:['ingest'],owner:'fixture',now,leaseMs:10000});await store.execute('fail',{id:claimed.id,owner:'fixture',epoch:state.epoch,now,error:'fixture',blocked:false,retryAt:now});await store.execute('fail',{id:claimed.id,owner:'fixture',epoch:state.epoch,now,error:'fixture',blocked:false,retryAt:now});expect((await store.execute('enqueue',input)).id).toBe(queued.id);await expect(store.execute('enqueue',{...input,payload:{items:[{title:'different content'}]}})).rejects.toThrow('identity conflict');}));
 it('initializes 18 sources once across concurrent commands, loss of response and restart',()=>fixture(async(store,restart)=>{const commandId=randomUUID();const input={commandId,settings:defaultSettings({provider:'mock',model:'news'}),sources:seeds,now};const results=await Promise.all([store.execute('initialize',input),store.execute('initialize',input),initialize(store)]);expect(results.every(s=>s.sourceCount===18)).toBe(true);store=await restart();expect((await store.execute('initialize',input)).sourceCount).toBe(18);const state=await store.execute('state',{});expect(state.initialized).toBe(true);expect(state.counts.articles).toBe(0);expect(state.counts.receipts).toBe(0);}));
 it('coalesces missed source slots and does not reseed deleted sources',()=>fixture(async store=>{await initialize(store);expect(await store.execute('schedule',{now})).toBe(18);expect(await store.execute('schedule',{now:now+7*86400000})).toBe(0);expect((await store.execute('jobs',{limit:100,offset:0})).length).toBe(18);await store.execute('removeSource',{id:seeds[0].id,expectedRevision:1,now});await initialize(store);expect((await store.execute('sources',{})).length).toBe(17);}));
 it('deduplicates completed stages but allows an explicitly different rerun identity',()=>fixture(async store=>{const state=await initialize(store);const first=await store.execute('enqueue',job(state.epoch));expect((await store.execute('enqueue',job(state.epoch))).id).toBe(first.id);const claimed=await store.execute('claim',{kinds:['score1'],owner:'worker1',now,leaseMs:10000});expect(claimed.id).toBe(first.id);expect(await store.execute('finish',{id:first.id,owner:'worker1',epoch:state.epoch,now:now+1,result:{score:70}})).toBe(true);expect((await store.execute('enqueue',job(state.epoch))).id).toBe(first.id);expect((await store.execute('enqueue',job(state.epoch,'one:rerun:'+randomUUID()))).id).not.toBe(first.id);}));
 it('recovers expired leases and rejects the previous worker commit',()=>fixture(async store=>{const state=await initialize(store);const first=await store.execute('enqueue',job(state.epoch));await store.execute('claim',{kinds:['score1'],owner:'old',now,leaseMs:1000});await store.execute('recover',{now:now+2000});const fresh=await store.execute('claim',{kinds:['score1'],owner:'new',now:now+2000,leaseMs:10000});expect(fresh.id).toBe(first.id);expect(await store.execute('finish',{id:first.id,owner:'old',epoch:state.epoch,now:now+2001,result:null})).toBe(false);expect(await store.execute('finish',{id:first.id,owner:'new',epoch:state.epoch,now:now+2001,result:null})).toBe(true);}));
 it('atomically reserves a budget across concurrent callers and shares the service limit',()=>fixture(async store=>{const state=await initialize(store);await store.execute('setBudget',{service:'llm',policy:{perMinute:2,perHour:5,per24Hours:10}});const rows=await Promise.all(Array.from({length:8},(_,i)=>store.execute('reserve',request(state.epoch,'request:'+i))));expect(rows.filter(r=>r.admitted).length).toBe(2);expect(rows.filter(r=>r.blockedReason==='budget-exhausted').length).toBe(6);expect(rows[2].retryAt).toBe(now+60001);await store.execute('setBudget',{service:'llm',policy:{perMinute:0,perHour:5,per24Hours:10}});expect((await store.execute('reserve',request(state.epoch,'paused'))).blockedReason).toBe('service-paused');}));
 it('reuses a received response after restart without a new paid attempt',()=>fixture(async(store,restart)=>{const state=await initialize(store);const first=await store.execute('reserve',request(state.epoch));await store.execute('sent',{id:first.receipt.id,epoch:state.epoch,auditRef:'audit/session',now});await store.execute('receive',{id:first.receipt.id,epoch:state.epoch,response:{text:'durable'},usage:{inputTokens:10},now:now+1});store=await restart();await store.execute('recover',{now:now+5000});const replay=await store.execute('reserve',request(state.epoch));expect(replay.reusable).toBe(true);expect(replay.admitted).toBe(false);expect(replay.receipt.attempt).toBe(1);expect(replay.receipt.response).toEqual({text:'durable'});}));
 it('holds unknown dispatches 30 minutes and releases at most once',()=>fixture(async store=>{const state=await initialize(store);const first=await store.execute('reserve',request(state.epoch));await store.execute('sent',{id:first.receipt.id,epoch:state.epoch,auditRef:'audit1',now});await store.execute('recover',{now:now+1000});expect((await store.execute('reserve',request(state.epoch))).blockedReason).toBe('unknown-result');expect((await store.execute('recover',{now:now+1800000})).released).toBe(1);const second=await store.execute('reserve',{...request(state.epoch),now:now+1800001});expect(second.admitted).toBe(true);expect(second.receipt.attempt).toBe(2);await store.execute('sent',{id:first.receipt.id,epoch:state.epoch,auditRef:'audit2',now:now+1800001});await store.execute('recover',{now:now+3600002});expect((await store.execute('reserve',{...request(state.epoch),now:now+3600003})).retryAt).toBe(null);}));
 it('fences old responses and commands after an idempotent clear',()=>fixture(async store=>{const state=await initialize(store);const first=await store.execute('reserve',request(state.epoch));await store.execute('sent',{id:first.receipt.id,epoch:state.epoch,auditRef:'audit1',now});const commandId=randomUUID();const cleared=await store.execute('clear',{commandId,now});expect(cleared.epoch).toBe(state.epoch+1);expect(cleared.initialized).toBe(false);await initialize(store);expect((await store.execute('clear',{commandId,now})).epoch).toBe(cleared.epoch);expect((await store.execute('state',{})).initialized).toBe(true);await expect(store.execute('receive',{id:first.receipt.id,epoch:state.epoch,response:{late:true},usage:{},now})).rejects.toThrow('Stale');expect((await store.execute('receipts',{limit:10,offset:0})).length).toBe(1);}));
 it('enforces CAS for settings and source changes',()=>fixture(async store=>{const state=await initialize(store);const next=await store.execute('configure',{revision:state.revision,settings:{...state.settings,autoCollectEnabled:false},now});expect(next.revision).toBe(state.revision+1);await expect(store.execute('configure',{revision:state.revision,settings:state.settings,now})).rejects.toThrow('conflict');expect(await store.execute('schedule',{now})).toBe(0);await store.execute('saveSource',{source:{...seeds[0],name:'User changed'},expectedRevision:1,now});await expect(store.execute('saveSource',{source:seeds[0],expectedRevision:1,now})).rejects.toThrow('conflict');}));
});

describe('persisted request snapshots',()=>{it('keeps the first prompt and candidate mapping after a retry instead of accepting rebuilt input',()=>fixture(async store=>{const state=await initialize(store);const row=await store.execute('enqueue',job(state.epoch,'freeze'));const first=await store.execute('claim',{kinds:['score1'],owner:'worker',now,leaseMs:600000});const request={system:'original',user:'material',context:{candidates:['fact-a']}};expect(await store.execute('freezeJob',{jobId:first.id,owner:'worker',epoch:state.epoch,now,stage:'group',request})).toEqual(request);await store.execute('fail',{id:first.id,owner:'worker',epoch:state.epoch,now,error:'test interruption',blocked:false,retryAt:now+1000});const retry=await store.execute('claim',{kinds:['score1'],owner:'other',now:now+1000,leaseMs:600000});expect(await store.execute('freezeJob',{jobId:retry.id,owner:'other',epoch:state.epoch,now:now+1000,stage:'group',request:{system:'changed',user:'new',context:{candidates:['fact-b']}}})).toEqual(request);}));});

describe('X account shards',()=>{it('coalesces compatible account queries and commits all member cursors together',()=>fixture(async store=>{const state=await initialize(store);for(const seed of seeds)await store.execute('removeSource',{id:seed.id,expectedRevision:1,now});const accounts=['one','two'].map(id=>({...seeds[0],id,name:id,kind:'x_search',config:{query:'from:'+id+' -filter:replies'},cursor:{initializedAt:new Date(now).toISOString(),lastTweetId:'100',lastOkAt:new Date(now).toISOString()},nextDueAt:now}));for(const source of accounts)await store.execute('saveSource',{source,expectedRevision:0,now});expect(await store.execute('schedule',{now})).toBe(1);const job=await store.execute('claim',{kinds:['collect-shard'],owner:'shard',now,leaseMs:600000});expect(job.payload.sourceIds).toEqual(['one','two']);const members=accounts.map(source=>({sourceId:source.id,sourceRevision:1,items:[],cursor:{...source.cursor,lastTweetId:'200'},receiptIds:[]}));expect(await store.execute('collectionBatch',{jobId:job.id,owner:'shard',epoch:state.epoch,now,members})).toEqual({committed:true,created:0,revised:0});expect((await store.execute('sources',{})).every(s=>s.cursor.lastTweetId==='200')).toBe(true);}));});
