import{describe,it,expect}from'vitest';import{DatabaseSync}from'node:sqlite';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{randomUUID}from'node:crypto';import{HotstreamDatabase}from'../../packages/storage-sqlite/lib/types/database.js';import{HotstreamSqliteProvider}from'../../packages/storage-sqlite/lib/index.js';import{defaultSettings}from'../../packages/contracts/lib/types/runtime.js';
const source={createdAt:null,id:'fixture',name:'Storage fault fixture',kind:'external',config:{},tags:[],tier:'T1',ownerEntityId:null,signalGroupId:null,participationMode:'isolated',firstParty:false,intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{},health:'unknown',lastOkAt:null,nextDueAt:null,lastError:null};
const initialize=settings=>({commandId:randomUUID(),settings,sources:[source],now:Date.now()});
describe('migration and storage failures fail closed',()=>{
 it('rejects a bad checksum or a migration hole before applying pending SQL',()=>{for(const bad of ['checksum','hole']){const db=new DatabaseSync(':memory:');try{new HotstreamDatabase(db);db.exec("DELETE FROM schema_migrations WHERE id='012'");if(bad==='checksum')db.exec("UPDATE schema_migrations SET checksum='wrong' WHERE id='001'");else db.exec("DELETE FROM schema_migrations WHERE id='002'");const before=db.prepare("SELECT sql FROM sqlite_master ORDER BY name").all();expect(()=>new HotstreamDatabase(db)).toThrow(/checksum|discontinuous/);expect(db.prepare("SELECT sql FROM sqlite_master ORDER BY name").all()).toEqual(before);expect(db.prepare("SELECT id FROM schema_migrations WHERE id='012'").get()).toBeUndefined();}finally{db.close();}}});
 it('blocks an unrecognized database without creating a migration ledger or diagnostic tables',async()=>{const root=await mkdtemp(join(tmpdir(),'hotstream-migration-')),path=join(root,'news.sqlite');const db=new DatabaseSync(path);db.exec('CREATE TABLE user_data(value TEXT); INSERT INTO user_data VALUES(\'preserved\')');db.close();const store=new HotstreamSqliteProvider(path);try{await expect(store.execute('state',{})).rejects.toThrow('Unrecognized');const read=new DatabaseSync(path,{readOnly:true});expect(read.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(row=>row.name)).toEqual(['user_data']);expect(read.prepare('SELECT * FROM user_data').get().value).toBe('preserved');read.close();}finally{await store.close();await rm(root,{recursive:true,force:true});}});
 it('rolls back initialization on an actual SQLite page limit instead of leaving a partial seed',()=>{const db=new DatabaseSync(':memory:');try{const store=new HotstreamDatabase(db),pages=db.prepare('PRAGMA page_count').get().page_count;db.exec('PRAGMA max_page_count='+pages);const settings=defaultSettings({provider:'fixture',model:'fixture'});settings.industry.promptOverrides.prefilter='x'.repeat(50000);expect(()=>store.execute('initialize',initialize(settings))).toThrow(/full/);expect(store.execute('state',{})).toMatchObject({initialized:false,sourceCount:0});expect(db.prepare('SELECT count(*) n FROM command_receipts').get().n).toBe(0);}finally{db.close();}});
 it('returns a read-only write refusal without changing stored configuration',async()=>{const root=await mkdtemp(join(tmpdir(),'hotstream-readonly-')),path=join(root,'news.sqlite');try{const db=new DatabaseSync(path),store=new HotstreamDatabase(db);store.execute('initialize',initialize(defaultSettings({provider:'fixture',model:'fixture'})));db.close();const readonly=new DatabaseSync(path,{readOnly:true}),reader=new HotstreamDatabase(readonly),state=reader.state();expect(()=>reader.execute('configure',{revision:state.revision,settings:{...state.settings,autoCollectEnabled:false},now:Date.now()})).toThrow(/readonly/);expect(reader.state().settings.autoCollectEnabled).toBe(true);readonly.close();}finally{await rm(root,{recursive:true,force:true});}});
});
