import {readUiMonitor} from './ui-monitor.ts';
import {UiQueries} from './ui-queries.ts';
import {readingMedia} from 'dsh-hotstream-core/content/reading-media';
import {jobAdmissionSql} from './admission.ts';
/** Business transactions, replacing AIHOT's SQL-dependent services rather than its rules. */
import type {DatabaseSync,SQLInputValue,SQLOutputValue} from 'node:sqlite';
import {createHash,randomUUID} from 'node:crypto';
import {Time,Edition,Reports} from 'dsh-hotstream-core';
import {projectDigest} from './story-copy.ts';
import {HeatRepository} from './heat.ts';
import {ReportData} from './report-data.ts';
import {CHRONICLE_KINDS,selectTopicChronicle,selectTopicHighlights,type ChronicleReport,type ChronicleTopic} from 'dsh-hotstream-core/publication/topic-chronicle';
import {belongsToTopic,topicMembershipTags} from 'dsh-hotstream-core/publication/topics';
import {publicCitationUrl} from 'dsh-hotstream-core/lib/url';
import {publisherOwnsUrl} from 'dsh-hotstream-core/content/provenance';
import * as Material from 'dsh-hotstream-core/content/materials';
import * as Writing from 'dsh-hotstream-core/editorial/writing';
import * as Relate from 'dsh-hotstream-core/events/relate';
import type {StorageOperations,Article,ArticleWork,AnalysisStep,Source,RuntimeState,EnqueueJob,Publication,PageQuery,EventCandidate,Story,Json,OwnedJob,HeatEntry,Report,Topic} from 'dsh-hotstream-contracts/runtime';
type Row=Record<string,SQLOutputValue>;
const encode=(value:unknown)=>JSON.stringify(value);const decode=(value:unknown):unknown=>JSON.parse(String(value));
export type BusinessKey='mediaReference'|'uiMonitor'|'uiArticle'|'uiFeed'|'uiGroups'|'uiReportIndex'|'uiReport'|'compileHistory'|'candidatesPage'|'reportCheck'|'storyDigestWork'|'splitStory'|'correctionState'|'mutationHistory'|'sourceReproject'|'storyDigest'|'work'|'collection'|'extraction'|'analysis'|'candidates'|'grouping'|'page'|'detail'|'marks'|'override'|'correctEvent'|'mergeStories'|'story'|'stories'|'heat'|'topics'|'seedTopics'|'reports'|'report'|'reportMaterial'|'saveReport'|'rerun'|'vectorGet'|'vectorPut'|'collectionBatch'|'translation'|'chronicle'|'evaluations'|'evaluationSave'|'sourceFailure'|'nextWake'|'maintenance'|'materialsKnown'|'dailyEdition'|'periodEntries'|'reportRevisions'|'reportRegenerate'|'preferenceGet'|'preferenceSave'|'reportMissing';
interface RuntimePort {state():RuntimeState;transaction<T>(fn:()=>T):T;enqueue(input:EnqueueJob):unknown;}
export class BusinessDatabase {
 constructor(private readonly db:DatabaseSync,private readonly runtime:RuntimePort){
  db.function('hotstream_topic_membership',{deterministic:true},(document,definition)=>Number(belongsToTopic(decode(document) as Publication,decode(definition) as Topic)));
 }
 private get(sql:string,...args:SQLInputValue[]):Row|undefined{return this.db.prepare(sql).get(...args);}
 private all(sql:string,...args:SQLInputValue[]):Row[]{return this.db.prepare(sql).all(...args);}
 private run(sql:string,...args:SQLInputValue[]):number{return Number(this.db.prepare(sql).run(...args).changes);}
 private source(id:string):Source|null{const row=this.get('SELECT * FROM sources WHERE id=?',id);return row===undefined?null:{...decode(row.document) as Source,createdAt:row.created_at===null?null:Number(row.created_at),enabled:row.enabled===1,revision:Number(row.revision),lastOkAt:row.last_ok_at===null?null:Number(row.last_ok_at),nextDueAt:row.next_due_at===null?null:Number(row.next_due_at)};}
 private article(id:string):Article|null{const row=this.get('SELECT * FROM articles WHERE id=?',id);if(row===undefined)return null;const source=this.source(String(row.source_id));if(source===null)return null;return {...decode(row.document) as Article,id:String(row.id),source,sourceId:String(row.source_id),revision:Number(row.revision),processingState:String(row.processing_state),groupingStatus:String(row.grouping_status)};}
 private steps(id:string,revision:number):AnalysisStep[]{return this.all('SELECT * FROM analyses WHERE article_id=? AND input_revision=? ORDER BY created_at,rowid',id,revision).map(r=>({articleId:id,inputRevision:Number(r.input_revision),configRevision:Number(r.config_revision),stage:String(r.stage),slot:String(r.slot),runKey:String(r.run_key),provider:String(r.provider),model:String(r.model),promptHash:String(r.prompt_hash),result:decode(r.result_json) as Record<string,Json>,receiptIds:decode(r.receipt_ids) as string[],createdAt:Number(r.created_at)}));}
 private work(id:string):ArticleWork|null{const article=this.article(id);const state=this.runtime.state();if(article===null||!state.settings)return null;const override=this.get('SELECT mode,fact_id FROM grouping_overrides WHERE article_id=?',id);return {groupingOverride:override?{mode:override.mode as 'standalone'|'assign',factId:override.fact_id===null?null:String(override.fact_id)}:null,activeRun:String(this.get('SELECT active_run FROM articles WHERE id=?',id)?.active_run??'initial'),activeConfigRevision:Number(this.get('SELECT active_config_revision FROM articles WHERE id=?',id)?.active_config_revision??0),manualRevision:Number(this.get('SELECT revision FROM grouping_controls WHERE article_id=?',id)?.revision??0),article,steps:this.steps(id,article.revision),settings:state.settings,epoch:state.epoch,configRevision:state.revision};}
 private owned(input:OwnedJob):Row|undefined{return this.get("SELECT * FROM jobs WHERE id=? AND lease_owner=? AND epoch=? AND epoch=(SELECT epoch FROM plugin_state WHERE id=1) AND state='running' AND lease_until>?",input.jobId,input.owner,input.epoch,input.now);}
 private done(input:OwnedJob,result:unknown):void{const row=this.owned(input);if(row===undefined)throw new Error('Job lease no longer owns this transaction');this.run("UPDATE jobs SET state='succeeded',lease_owner=NULL,lease_until=NULL,result=? WHERE id=?",encode(result),input.jobId);this.run("UPDATE job_attempts SET finished_at=?,outcome='succeeded' WHERE job_id=? AND attempt=?",input.now,input.jobId,row.attempts!);}
 private next(parent:Row,article:Article,kind:string,now:number):void{const payload=decode(parent.payload) as Record<string,Json>;const rerun=typeof payload.rerun==='string'?payload.rerun:'initial';this.runtime.enqueue({kind,subject:article.id,key:`${parent.epoch}:${article.id}@${article.revision}:${kind}:c${parent.config_revision}:${rerun}`,epoch:Number(parent.epoch),inputRevision:article.revision,configRevision:Number(parent.config_revision),payload:{...payload,sourceSnapshot:payload.sourceSnapshot??JSON.parse(encode(article.source)) as Json,articleId:article.id},priority:article.backfill?10:90,maxAttempts:5,dueAt:now});}
 private completeReceipts(ids:string[],epoch:number,now:number):void{for(const id of ids){const row=this.get('SELECT state,epoch FROM receipts WHERE id=?',id);if(row===undefined||row.epoch!==epoch||!['received','completed'].includes(String(row.state)))throw new Error('Business commit requires a durable response receipt');this.run("UPDATE receipts SET state='completed',updated_at=? WHERE id=?",now,id);this.run("UPDATE receipt_attempts SET outcome='completed' WHERE receipt_id=? AND attempt=(SELECT attempt FROM receipts WHERE id=?) AND outcome='received'",id,id);}}
 private writeArticle(article:Article):void{
  const document={...article,source:undefined};
  this.run(`INSERT INTO articles(id,source_id,identity_key,url,title,revision,content_hash,published_at,published_at_claim,discovered_at,timeline_at,backfill,body_status,processing_state,grouping_status,document) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET source_id=excluded.source_id,title=excluded.title,revision=excluded.revision,content_hash=excluded.content_hash,body_status=excluded.body_status,processing_state=excluded.processing_state,grouping_status=excluded.grouping_status,document=excluded.document`,article.id,article.sourceId,article.identityKey,article.url,article.title,article.revision,article.contentHash,article.publishedAt,article.publishedAtClaim,article.discoveredAt,article.timelineAt,Number(article.backfill),article.bodyStatus,article.processingState,article.groupingStatus,encode(document));
 }
 private revise(article:Article,patch:Partial<Article>,now:number):Article{
  const oldStories=this.all('SELECT DISTINCT f.story_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=?',article.id).map(row=>String(row.story_id));const next={...article,...patch};const hash=Material.contentHash(next);if(hash===article.contentHash)return next;
  if(Material.sameBarringLoss(article.title,next.title)&&Material.sameBarringLoss(article.bodyText,next.bodyText)&&Material.sameBarringLoss(article.excerpt,next.excerpt))return article;
  const seen=this.get('SELECT 1 FROM article_revisions WHERE article_id=? AND content_hash=?',article.id,hash);if(seen)return article;
  next.contentHash=hash;next.revision++;next.processingState='new';next.groupingStatus='pending';
  this.writeArticle(next);this.run('INSERT INTO article_revisions VALUES(?,?,?,?,?)',next.id,next.revision,hash,encode({...next,source:undefined}),now);
  this.run('DELETE FROM story_signals WHERE article_id=?',next.id);this.run('DELETE FROM fact_articles WHERE article_id=? AND manual=0',next.id);this.project(next.id,now);for(const id of oldStories)this.invalidateStory(id,now);return next;
 }
 private collection(input:StorageOperations['collection']['input'],finish=true):StorageOperations['collection']['output']{return this.runtime.transaction(()=>{
  const parent=this.owned(input);const source=this.source(input.sourceId);if(parent===undefined||source===null||!source.enabled||source.revision!==input.sourceRevision)return {committed:false,created:0,revised:0};
  let created=0,revised=0;
  for(const candidate of input.items){const key=candidate.identityKey??Material.identityKeyFor({sourceId:source.id,url:candidate.url,title:candidate.title,xPost:candidate.xPost as never,via:'fetch'});const row=this.get('SELECT id FROM articles WHERE identity_key=?',key);let article:Article;
   if(row===undefined){const timeline=Material.decideTimeline(candidate.publishedAt===null?null:new Date(candidate.publishedAt),new Date(input.observedAt??input.now),candidate.backfillReason);article={...candidate,id:randomUUID(),sourceId:source.id,identityKey:key,publishedAt:timeline.publishedAt?.getTime()??null,publishedAtClaim:candidate.publishedAt,discoveredAt:input.observedAt??input.now,timelineAt:timeline.timelineAt.getTime(),backfill:timeline.backfill,backfillReason:timeline.backfillReason,revision:1,contentHash:Material.contentHash(candidate),source,processingState:'new',groupingStatus:'pending'};this.writeArticle(article);this.run('INSERT INTO article_revisions VALUES(?,?,?,?,?)',article.id,1,article.contentHash,encode({...article,source:undefined}),input.now);created++;
   }else{article=this.article(String(row.id))!;if(article.sourceId===source.id){const next=this.revise(article,{title:candidate.title,excerpt:candidate.excerpt??article.excerpt,bodyText:candidate.bodyText??article.bodyText,bodyHtml:candidate.bodyHtml??article.bodyHtml,bodyStatus:candidate.bodyText?candidate.bodyStatus:article.bodyStatus,raw:candidate.raw??article.raw},input.now);if(next.revision!==article.revision)revised++;article=next;this.writeArticle(article);}}
   this.run('INSERT OR IGNORE INTO article_discoveries VALUES(?,?,?,?)',article.id,source.id,'fetch',input.now);this.run('INSERT INTO source_observations VALUES(?,?,?,?,?,?) ON CONFLICT(source_id,external_key) DO UPDATE SET observed_at=excluded.observed_at',source.id,key,article.id,candidate.url,candidate.publishedAt,input.now);
   const publishers=this.all("SELECT * FROM sources WHERE json_extract(document,'$.tier')='T1'").map(row=>this.source(String(row.id))!).filter(s=>s.config.publisherUrlPrefixes!==undefined||s.kind==='web_list'&&!!this.get('SELECT 1 FROM article_discoveries WHERE article_id=? AND source_id=?',article.id,s.id)).filter(s=>publisherOwnsUrl({id:s.id,kind:s.kind,config:s.config},article.url));
   if(publishers.length===1&&publishers[0]!.id!==article.sourceId){const publisher=publishers[0]!;const previous=article.sourceId;const unjudged=this.steps(article.id,article.revision).length===0;article={...article,sourceId:publisher.id,source:publisher,author:source.id===publisher.id?candidate.author:null,processingState:article.source.participationMode!=='editorial'&&publisher.participationMode==='editorial'&&unjudged?'new':article.processingState};this.writeArticle(article);this.run('INSERT INTO audit_events VALUES(?,?,?,?,1)',randomUUID(),'article.attribution',input.now,encode({articleId:article.id,from:previous,to:publisher.id}));this.project(article.id,input.now);}
   if(article.processingState==='new'&&article.source.participationMode!=='isolated'){this.run('UPDATE articles SET active_run=?,active_config_revision=? WHERE id=?','initial',parent.config_revision!,article.id);this.next(parent,article,article.source.participationMode==='hot_signal'?'group':article.bodyStatus==='pending'&&!article.xPost?'extract':'prefilter',input.now);}
  }
  const document={...source,cursor:input.cursor,health:'ok',lastError:null,lastOkAt:input.now};this.run('UPDATE sources SET last_ok_at=?,fail_count=0,document=? WHERE id=?',input.now,encode(document),source.id);this.run('INSERT INTO fetch_runs(id,source_id,started_at,finished_at,status,found_count,new_count) VALUES(?,?,?,?,?,?,?)',randomUUID(),source.id,Number(parent.created_at),input.now,'ok',input.foundCount??input.items.length,created);this.completeReceipts(input.receiptIds,input.epoch,input.now);if(finish)this.done(input,{created,revised});return {committed:true,created,revised};
 });}
 private extraction(input:StorageOperations['extraction']['input']):boolean{return this.runtime.transaction(()=>{const parent=this.owned(input);const article=this.article(input.id);if(parent===undefined||article===null)return false;if(article.revision!==input.revision){this.done(input,{stale:true});return false;}const updated=this.revise(article,{bodyText:input.bodyText??article.bodyText,bodyHtml:input.bodyHtml??article.bodyHtml,media:input.media?[...new Map([...article.media,...input.media].map(raw=>[String((raw as Record<string,Json>).url),raw])).values()].slice(0,12):article.media,bodyStatus:input.status},input.now);updated.bodyStatus=input.status;this.writeArticle(updated);this.next(parent,updated,'prefilter',input.now);this.completeReceipts(input.receiptIds,input.epoch,input.now);this.done(input,{revision:updated.revision});return true;});}
 private analysis(input:StorageOperations['analysis']['input']):boolean{return this.runtime.transaction(()=>{
  const parent=this.owned(input);if(parent===undefined)return false;const step=input.step;const article=this.article(step.articleId);if(article===null)return false;
  const analysisId=randomUUID();this.run('INSERT OR IGNORE INTO analyses(id,article_id,input_revision,stage,slot,run_key,config_revision,prompt_hash,industry_version,provider,model,receipt_ids,result_json,created_at,applied) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)',analysisId,article.id,step.inputRevision,step.stage,step.slot,step.runKey,step.configRevision,step.promptHash,step.industryVersion??'ai@1',step.provider,step.model,encode(step.receiptIds),encode(step.result),step.createdAt);this.completeReceipts(step.receiptIds,input.epoch,input.now);
  const active=this.get('SELECT active_run,active_config_revision FROM articles WHERE id=?',article.id)!;if(article.revision!==step.inputRevision||Number(active.active_config_revision)>0&&(active.active_run!==step.runKey||Number(active.active_config_revision)!==step.configRevision)){this.done(input,{stale:true});return true;}
  this.run('UPDATE analyses SET applied=1 WHERE id=?',analysisId);
  if(step.stage==='prefilter'){
   if(step.result.label==='BLOCK'){article.processingState='blocked';this.writeArticle(article);this.project(article.id,input.now);}else{this.next(parent,article,'score1',input.now);this.next(parent,article,'structure',input.now);}
  }else if(step.stage==='score1')this.next(parent,article,'score2',input.now);
  if(['score1','score2','structure'].includes(step.stage)){const steps=this.steps(article.id,article.revision).filter(s=>s.configRevision===step.configRevision&&s.runKey===step.runKey);if(steps.some(s=>s.stage==='score1')&&steps.some(s=>s.stage==='score2')&&steps.some(s=>s.stage==='structure'))this.next(parent,article,'writing',input.now);}
  if(step.stage==='writing'){const oldStories=this.all('SELECT DISTINCT f.story_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=?',article.id).map(row=>String(row.story_id));article.groupingStatus='pending';this.run('DELETE FROM fact_articles WHERE article_id=? AND manual=0',article.id);this.run('DELETE FROM story_signals WHERE article_id=?',article.id);article.processingState='analyzed';this.writeArticle(article);this.project(article.id,input.now);for(const id of oldStories)this.invalidateStory(id,input.now);this.next(parent,article,'group',input.now);}
  this.done(input,{stage:step.stage});return true;
 });}
 private normalized(article:Article):Record<string,Json>|null{const row=this.get("SELECT result_json FROM analyses WHERE article_id=? AND input_revision=? AND stage='writing' AND applied=1 ORDER BY created_at DESC,rowid DESC LIMIT 1",article.id,article.revision);if(!row)return null;const value=decode(row.result_json) as Record<string,Json>;return value.normalized as Record<string,Json>??value;}
 private project(id:string,now:number):void{
  const article=this.article(id);if(article===null)return;const normalized=this.normalized(article);const manual=this.get('SELECT * FROM editorial_overrides WHERE article_id=?',id);const fields=(manual?decode(manual.fields):{}) as Record<string,Json>;const value={...normalized,...fields};
  const title=typeof fields.title==='string'?fields.title:typeof value.titleZh==='string'?value.titleZh:typeof value.title==='string'?value.title:Writing.looksZh(article.title)?article.title:'';const summary=typeof fields.summary==='string'?fields.summary:typeof value.summaryZh==='string'?value.summaryZh:typeof value.summary==='string'?value.summary:'';
  const visibility=article.source.participationMode==='isolated'?'withdrawn':manual?.visibility??'public';const eligible=article.source.participationMode==='editorial'&&value.relevance==='pass'&&!!title&&!!summary;
  const candidate=eligible&&value.selected===true&&article.source.tier!=='EXCLUDE_MP';const grouped=article.groupingStatus==='complete';const row=this.get('SELECT selection_adds_value FROM articles WHERE id=?',id);const addsValue=row?.selection_adds_value!==0;
  const member=this.get("SELECT fa.fact_id,f.story_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=? AND fa.role IN('primary','report') ORDER BY fa.manual DESC,fa.role LIMIT 1",id);
  const subjects=Array.isArray(value.subjects)?value.subjects.filter((t):t is string=>typeof t==='string'):[];
  const tags=Array.isArray(fields.tags)?fields.tags.filter((t):t is string=>typeof t==='string'):[...new Set([...Array.isArray(value.tags)?value.tags.filter((t):t is string=>typeof t==='string'):[],...subjects.map(subject=>'entity:'+subject)])];
  const document:Publication={id,revision:article.revision,visibility:visibility as Publication['visibility'],eligible,selected:candidate&&grouped&&addsValue,selectionCandidate:candidate,seat:true,title,originalTitle:article.title,summary,reason:typeof value.reasonZh==='string'?value.reasonZh:null,category:typeof value.category==='string'?value.category:null,tags,subjects,score:typeof value.score==='number'?value.score:null,url:article.url,sourceId:article.sourceId,sourceName:article.source.name,firstParty:article.source.tier==='T1',publishedAt:article.publishedAt,discoveredAt:article.discoveredAt,timelineAt:article.timelineAt,backfill:article.backfill,body:null,bodyHtml:null,translatedHtml:null,media:[],translatedBody:null,translationComplete:null,storyId:member?.story_id===null||!member?null:String(member.story_id),factId:member?String(member.fact_id):null,groupingStatus:article.groupingStatus,bookmarked:false,readAt:null};
  const prior=this.get('SELECT selected,visible_after FROM publications WHERE article_id=?',id);const released=prior?.selected===1?prior.visible_after??now:document.selected?now:null;
  this.run(`INSERT INTO publications(article_id,input_revision,visibility,eligible,selected,selection_candidate,seat,story_id,fact_id,title,summary,category,score,publication_time,visible_after,body_mode,document) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET input_revision=excluded.input_revision,visibility=excluded.visibility,eligible=excluded.eligible,selected=excluded.selected,selection_candidate=excluded.selection_candidate,seat=excluded.seat,story_id=excluded.story_id,fact_id=excluded.fact_id,title=excluded.title,summary=excluded.summary,category=excluded.category,score=excluded.score,publication_time=excluded.publication_time,visible_after=excluded.visible_after,body_mode=excluded.body_mode,document=excluded.document`,id,article.revision,String(visibility),Number(eligible),Number(document.selected),Number(candidate),1,document.storyId,document.factId,title,summary,document.category,document.score,article.timelineAt,released,article.source.siteFulltext?'full':'summary',encode(document));
  this.run('DELETE FROM publication_search WHERE article_id=?',id);if(visibility!=='withdrawn'&&eligible)this.run('INSERT INTO publication_search VALUES(?,?,?,?)',id,title,summary,article.source.siteFulltext&&visibility==='public'?article.bodyText??'':'');
  if(document.factId)this.seats(document.factId);
 }
 private seats(factId:string):void{
  const rows=this.all("SELECT p.*,s.document source_document FROM publications p JOIN sources s ON s.id=json_extract(p.document,'$.sourceId') WHERE p.fact_id=? AND p.selected=1 AND p.visibility!='withdrawn'",factId);
  rows.sort((a,b)=>{const x=decode(a.source_document) as Source,y=decode(b.source_document) as Source;const order=['T1','T1_5','T2','EXCLUDE_MP'];return order.indexOf(x.tier)-order.indexOf(y.tier)||Number(b.score??0)-Number(a.score??0)||Number(a.publication_time)-Number(b.publication_time)||String(a.article_id).localeCompare(String(b.article_id));});
  for(let index=0;index<rows.length;index++)this.run('UPDATE publications SET seat=? WHERE article_id=?',Number(index===0),rows[index]!.article_id!);
 }
 private read(id:string,now=Date.now(),full=false):Publication|null{
  const row=this.get('SELECT p.*,'+(full?'a.document':'NULL')+' article_document,a.revision article_revision,a.body_status article_body_status,s.document source_document,m.bookmarked,m.read_at FROM publications p JOIN articles a ON a.id=p.article_id JOIN sources s ON s.id=a.source_id LEFT JOIN user_marks m ON m.article_id=p.article_id WHERE p.article_id=?',id);
  if(!row||row.visibility==='withdrawn'||row.eligible!==1||row.input_revision!==row.article_revision||Number(row.visible_after??0)>now)return null;
  const document=decode(row.document) as Publication;const article=full?decode(row.article_document) as Article:{revision:Number(row.article_revision),bodyText:null,bodyHtml:null,media:[]};const source=decode(row.source_document) as Source;
  if(source.participationMode!=='editorial')return null;
  const canReadBody=full&&source.siteFulltext&&row.visibility==='public'&&row.article_body_status==='ok';
  const translation=full?this.get('SELECT * FROM translations WHERE article_id=? AND lang=? AND revision=?',id,'zh',article.revision):undefined;const translated=translation?decode(translation.document) as {text:string;html:string}:null;
  return {...document,bodyHtml:canReadBody?article.bodyHtml??null:null,translatedHtml:canReadBody?translated?.html??null:null,media:canReadBody?readingMedia(article.media,article.bodyHtml??null,document.url).map((item,index)=>({index,kind:item.kind,alt:item.alt})):[],url:publicCitationUrl(document.url),translatedBody:canReadBody?translated?.text??null:null,translationComplete:canReadBody&&translation?translation.complete===1:null,selected:row.selected===1,seat:row.seat===1,visibility:row.visibility as Publication['visibility'],sourceName:source.name,firstParty:source.tier==='T1',body:canReadBody?article.bodyText:null,bookmarked:row.bookmarked===1,readAt:row.read_at===null||row.read_at===undefined?null:Number(row.read_at)};
 }
 private bookmark(id:string):Publication|null{const current=this.read(id);if(current)return current;const row=this.get('SELECT p.document,m.read_at,m.bookmarked FROM user_marks m JOIN publications p ON p.article_id=m.article_id WHERE m.article_id=? AND m.bookmarked=1',id);if(!row)return null;const item=decode(row.document) as Publication;return {...item,title:'',originalTitle:'',summary:'',reason:null,category:null,tags:[],subjects:[],score:null,visibility:'withdrawn',eligible:false,selected:false,selectionCandidate:false,seat:false,body:null,bodyHtml:null,translatedHtml:null,media:[],translatedBody:null,translationComplete:null,storyId:null,factId:null,bookmarked:true,readAt:row.read_at===null?null:Number(row.read_at)};}
 private page(query:PageQuery):StorageOperations['page']['output']{
  const conditions=["p.visibility!='withdrawn'","p.eligible=1","p.input_revision=a.revision","coalesce(p.visible_after,0)<=?","json_extract(s.document,'$.participationMode')='editorial'"];const args:SQLInputValue[]=[Date.now()];let searchJoin='';
  if(query.view==='selected')conditions.push('p.selected=1',"p.visibility='public'");if(query.view==='bookmarks'){conditions.splice(0,conditions.length,'m.bookmarked=1');args.splice(0,args.length);}if(query.category){conditions.push('p.category=?');args.push(query.category);}
  if(query.topic){const row=this.get('SELECT definition FROM topics WHERE id=?',query.topic);if(!row)return {items:[],total:0};const topic=decode(row.definition) as Topic;const tags=topicMembershipTags(topic);if(query.view!=='bookmarks')conditions.push('p.selected=1','p.seat=1',"p.visibility='public'");if(!tags.length)conditions.push('0=1');else{conditions.push(`EXISTS (SELECT 1 FROM json_each(json_extract(p.document,'$.tags')) t WHERE t.value IN (${tags.map(()=>'?').join(',')}))`);args.push(...tags);if(topic.entityId){conditions.push('hotstream_topic_membership(p.document,?)=1');args.push(String(row.definition));}}}
  const text=query.query.trim();if(text){if(query.view==='bookmarks')conditions.push("p.visibility!='withdrawn'");if([...text].length>=3){searchJoin='JOIN publication_search search ON search.article_id=p.article_id';conditions.push("publication_search MATCH ?","(json_extract(s.document,'$.siteFulltext')=1 AND p.visibility='public' OR instr(lower(p.title),lower(?))>0 OR instr(lower(p.summary),lower(?))>0)");args.push('"'+text.replace(/"/g,'""')+'"',text,text);}else{conditions.push("(instr(lower(p.title),lower(?))>0 OR instr(lower(p.summary),lower(?))>0 OR (json_extract(s.document,'$.siteFulltext')=1 AND p.visibility='public' AND instr(json_extract(a.document,'$.bodyText'),?)>0))");args.push(text,text,text);}}
  const base=`FROM publications p JOIN articles a ON a.id=p.article_id JOIN sources s ON s.id=a.source_id LEFT JOIN user_marks m ON m.article_id=p.article_id ${searchJoin} WHERE ${conditions.join(' AND ')}`;
  const total=Number(this.get(`SELECT count(*) n ${base}`,...args)?.n??0);const ids=this.all(`SELECT p.article_id ${base} ORDER BY ${text&&searchJoin?'bm25(publication_search),':''}p.publication_time DESC,p.article_id LIMIT ? OFFSET ?`,...args,query.limit,query.offset);
  return {items:ids.flatMap(r=>{const item=query.view==='bookmarks'?this.bookmark(String(r.article_id)):this.read(String(r.article_id));return item?[item]:[];}),total};
 }

 private factStamp(id:string):string {
  const fact=this.get('SELECT f.*,s.merged_into,coalesce(c.revision,0) story_control FROM facts f JOIN stories s ON s.id=f.story_id LEFT JOIN story_controls c ON c.story_id=s.id WHERE f.id=?',id);
  const members=this.all('SELECT fa.*,a.revision,s.revision source_revision,coalesce(c.revision,0) manual_revision,p.visibility,p.title,p.summary FROM fact_articles fa JOIN articles a ON a.id=fa.article_id JOIN sources s ON s.id=a.source_id LEFT JOIN grouping_controls c ON c.article_id=a.id LEFT JOIN publications p ON p.article_id=a.id WHERE fa.fact_id=? ORDER BY a.id',id);
  return createHash('sha256').update(encode({fact,members})).digest('hex');
 }
 private command<T>(id:string|undefined,kind:string,subject:string,reason:string,request:unknown,now:number,work:()=>T):T {
  const state=this.runtime.state();if(!state.initialized||state.deleting)throw new Error('Initialize first');
  const commandId=id??randomUUID(),requestHash=createHash('sha256').update(encode({kind,request,reason,epoch:state.epoch})).digest('hex');
  const prior=this.get('SELECT * FROM mutation_history WHERE command_id=?',commandId);
  if(prior){if(prior.kind!==kind||prior.request_hash!==requestHash)throw new Error('Command identity conflict');return decode(prior.result_json) as T;}
  const before=kind.startsWith('story')?this.story(subject):this.correctionState(subject);
  const result=work();const after=kind.startsWith('story')?this.story(subject):this.correctionState(subject);
  this.run('INSERT INTO mutation_history(command_id,kind,subject_id,reason,before_json,after_json,at,request_hash,result_json) VALUES(?,?,?,?,?,?,?,?,?)',commandId,kind,subject,reason,encode(before),encode(after),now,requestHash,encode(result));return result;
 }
 private correctionState(id:string):import('dsh-hotstream-contracts').CorrectionState|null {
  const article=this.article(id);if(!article)return null;const override=this.get('SELECT * FROM editorial_overrides WHERE article_id=?',id);const member=this.get("SELECT f.id,f.story_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=? AND fa.role!='mention' LIMIT 1",id);
  return {id,inputRevision:article.revision,editorialRevision:Number(override?.version??0),groupingRevision:Number(this.get('SELECT revision FROM grouping_controls WHERE article_id=?',id)?.revision??0),visibility:override?.visibility as 'public'|'summary-only'|'withdrawn'|null??null,fields:override?decode(override.fields) as Record<string,Json>:{},factId:member?String(member.id):null,storyId:member?String(member.story_id):null};
 }
 private protectStory(id:string,now:number):void {this.run('INSERT INTO story_controls VALUES(?,1,1,?) ON CONFLICT(story_id) DO UPDATE SET revision=revision+1,manual=1,updated_at=excluded.updated_at',id,now);}
 private invalidateStory(id:string,now:number):void {
  const row=this.get('SELECT document FROM stories WHERE id=?',id);if(!row)return;const document=decode(row.document) as Record<string,Json>;
  this.run('UPDATE stories SET version=version+1,document=? WHERE id=?',encode({...document,digest:null,latest:null}),id);
  const state=this.runtime.state();const story=this.story(id);if(story?.articles.length&&state.settings)this.runtime.enqueue({kind:'digest',subject:story.id,key:`${state.epoch}:digest:${story.id}@${story.version}:${state.dataRevision}`,epoch:state.epoch,inputRevision:story.version,configRevision:state.revision,payload:{settings:JSON.parse(encode(state.settings)) as Json},priority:30,maxAttempts:3,dueAt:now});
 }
 private signal(article:Article,storyId:string):void {
  if(article.backfill||article.source.participationMode==='isolated'||this.normalized(article)?.scope==='composite')return;
  this.run('INSERT OR REPLACE INTO story_signals VALUES(?,?,?,?,?,?)',storyId,article.id,article.source.signalGroupId?'group:'+article.source.signalGroupId:article.source.ownerEntityId?'owner:'+article.source.ownerEntityId:'source:'+article.source.id,article.source.id,article.source.participationMode==='editorial'?'editorial':'signal',article.publishedAt??article.discoveredAt);
 }
 private digestWork(id:string):Record<string,Json>|null {
  const story=this.story(id);if(!story?.articles.length)return null;const reports=story.articles.filter(p=>p.visibility==='public').sort((a,b)=>a.timelineAt-b.timelineAt).map(p=>{const fact=this.get('SELECT frame_json FROM facts WHERE id=?',p.factId??'');const frame=fact?decode(fact.frame_json) as Record<string,Json>:{};return {id:p.id,title:p.title,summary:p.summary,source_name:p.sourceName,first_party:p.firstParty,at:p.timelineAt,fact_id:p.factId??'',fact_subject:frame.subject??null,fact_action:frame.action??null,fact_object:frame.object??null,fact_conditions:frame.conditions??null,evidence:frame.evidence??null,structured_fact:frame};});
  const inputsHash=createHash('sha256').update(encode(reports)).digest('hex');const last=this.get('SELECT * FROM story_digests WHERE story_id=? ORDER BY version DESC LIMIT 1',story.id);const known=last?decode(last.article_ids) as string[]:[];
  return {id:story.id,title:story.title,version:story.version,digest:story.digest,reports,inputsHash,knownIds:known,corrected:!!last&&(known.some(id=>!reports.some(p=>p.id===id))||known.length===reports.length),cachedDigest:last?.inputs_hash===inputsHash?String(last.digest):null};
 }
 private enqueueDigest(parent:Row,storyId:string,now:number):void {const story=this.story(storyId);if(!story?.articles.length)return;const payload=decode(parent.payload) as Record<string,Json>;this.runtime.enqueue({kind:'digest',subject:storyId,key:`${parent.epoch}:digest:${storyId}@${story.version}:${parent.id}`,epoch:Number(parent.epoch),inputRevision:story.version,configRevision:Number(parent.config_revision),payload:{settings:payload.settings??null,authorizationId:payload.authorizationId??null,articleId:payload.articleId??String(parent.subject)},priority:30,maxAttempts:3,dueAt:now});}
 private relatedStories(now:number):void {
  const ties=new Map<string,Set<string>>();for(const row of this.all('SELECT gd.* FROM grouping_decisions gd WHERE gd.created_at>? AND NOT EXISTS(SELECT 1 FROM grouping_decisions later WHERE later.article_id=gd.article_id AND (later.created_at>gd.created_at OR later.created_at=gd.created_at AND later.rowid>gd.rowid))',now-14*86400000)){
   const article=this.article(String(row.article_id));if(!article||this.normalized(article)?.scope==='composite')continue;const own=this.correctionState(article.id)?.storyId;if(!own)continue;const detail=decode(row.evidence_json) as Record<string,Json>;
   for(const raw of Array.isArray(detail.decisions)?detail.decisions:[]){const decision=raw as Record<string,Json>;if(!Relate.firmlyTied(String(decision.relation) as Relate.Relation,Number(decision.confidence)))continue;const other=this.get('SELECT story_id FROM facts WHERE id=?',String(decision.factId));if(!other||other.story_id===own)continue;const ids=[own,String(other.story_id)].sort(),key=ids.join('|');const set=ties.get(key)??new Set<string>();set.add(article.id);ties.set(key,set);}
  }for(const [key,articles]of ties){if(articles.size<2)continue;const [a,b]=key.split('|');if(!a||!b)continue;for(const [x,y]of [[a,b],[b,a]])if(this.get('SELECT id FROM stories WHERE id=? AND merged_into IS NULL',x!))this.run('INSERT OR IGNORE INTO story_links VALUES(?,?,?)',x!,y!,'related');}
 }
 private correctEvent(i:StorageOperations['correctEvent']['input']):boolean {return this.command(i.commandId,'event-correction',i.id,i.reason,{id:i.id,mode:i.mode,factId:i.factId,expectedRevision:i.expectedRevision},i.now,()=>{
  const article=this.article(i.id);if(!article)throw new Error('Article missing');const before=this.correctionState(i.id)!;if(i.expectedRevision!==undefined&&before.groupingRevision!==i.expectedRevision)throw new Error('Grouping override revision conflict');
  const state=this.runtime.state(),revision=before.groupingRevision+1;
  this.run('INSERT INTO grouping_controls VALUES(?,?,?) ON CONFLICT(article_id) DO UPDATE SET revision=excluded.revision,updated_at=excluded.updated_at',i.id,revision,i.now);
  this.run('DELETE FROM grouping_overrides WHERE article_id=?',i.id);this.run('DELETE FROM fact_articles WHERE article_id=?',i.id);this.run('DELETE FROM story_signals WHERE article_id=?',i.id);
  if(i.mode!=='regroup')this.run('INSERT INTO grouping_overrides VALUES(?,?,?,?,?,?)',i.id,i.mode,i.factId,i.reason,revision,i.now);
  article.groupingStatus=i.mode==='standalone'?'complete':'pending';
  if(i.mode==='assign'){if(!i.factId)throw new Error('Assign requires fact id');const fact=this.get('SELECT f.* FROM facts f JOIN stories s ON s.id=f.story_id WHERE f.id=? AND s.merged_into IS NULL',i.factId);if(!fact)throw new Error('Active fact required');this.run('INSERT INTO fact_articles VALUES(?,?,?,?,?,?)',i.factId,i.id,article.source.tier==='T1'?'primary':'report',1,i.reason,article.revision);this.signal(article,String(fact.story_id));article.groupingStatus='complete';this.protectStory(String(fact.story_id),i.now);}
  this.writeArticle(article);this.run('UPDATE articles SET selection_adds_value=1 WHERE id=?',i.id);this.project(i.id,i.now);
  if(before.storyId)this.invalidateStory(before.storyId,i.now);const after=this.correctionState(i.id);if(after?.storyId&&after.storyId!==before.storyId)this.invalidateStory(after.storyId,i.now);
  if(i.mode==='regroup')this.runtime.enqueue({kind:'group',subject:i.id,key:`${state.epoch}:${i.id}:manual-regroup:${i.commandId??randomUUID()}`,epoch:state.epoch,inputRevision:article.revision,configRevision:state.revision,payload:{settings:JSON.parse(encode(state.settings)) as Json,sourceSnapshot:JSON.parse(encode(article.source)) as Json},priority:100,maxAttempts:5,dueAt:i.now});return true;
 });}
 private splitStory(i:StorageOperations['splitStory']['input']):boolean{return this.command(i.commandId,'story-split',i.id,i.reason,{id:i.id,expectedRevision:i.expectedRevision,articleIds:i.articleIds},i.now,()=>{
  const origin=this.story(i.id);if(!origin||origin.id!==i.id||origin.version!==i.expectedRevision)throw new Error('Story revision conflict');const ids=[...new Set(i.articleIds)];if(ids.length!==i.articleIds.length||ids.some(id=>!origin.articles.some(article=>article.id===id))||ids.length===origin.articles.length)throw new Error('Split requires a proper subset of this story');
  const articles=ids.map(id=>this.article(id)!);const newId=randomUUID(),first=articles[0]!,title=this.read(first.id)?.title??first.title;
  this.run('INSERT INTO stories VALUES(?,?,?,?,NULL,?,?,?,?)',newId,newId,title,'active',1,Math.min(...articles.map(a=>a.timelineAt)),Math.max(...articles.map(a=>a.timelineAt)),encode({digest:null,latest:null}));
  const facts=new Map<string,string>();for(const article of articles){const oldFact=origin.facts.find(f=>f.articleIds.includes(article.id));if(!oldFact)throw new Error('Split fact missing');let factId=facts.get(oldFact.id);if(!factId){const old=this.get('SELECT * FROM facts WHERE id=?',oldFact.id)!;factId=randomUUID();facts.set(oldFact.id,factId);this.run('INSERT INTO facts VALUES(?,?,?,?,?,?,?,?)',factId,factId,newId,old.title!,old.occurred_at!,1,1,old.frame_json!);}
   this.correctEvent({id:article.id,mode:'assign',factId,expectedRevision:this.correctionState(article.id)!.groupingRevision,reason:i.reason,now:i.now});
  }this.protectStory(i.id,i.now);this.protectStory(newId,i.now);this.invalidateStory(i.id,i.now);this.invalidateStory(newId,i.now);return true;
 });}

 private candidates(id:string,now:number):EventCandidate[]{
  const article=this.article(id);if(!article)return [];const norm=this.normalized(article);const text=Relate.reportText(String(norm?.titleZh??article.title),String(norm?.summaryZh??article.excerpt??''));
  const rows=this.all("SELECT f.id fact_id,f.story_id,f.title fact_title,a.id article_id,fa.role FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id JOIN stories s ON s.id=f.story_id JOIN articles a ON a.id=fa.article_id WHERE s.merged_into IS NULL AND a.discovered_at>? AND fa.role IN('primary','report') AND a.id!=?",now-14*86400000,id);
  const byFact=new Map<string,EventCandidate>();for(const row of rows){const other=this.article(String(row.article_id));if(!other)continue;const normalized=this.normalized(other);if(normalized?.scope==='composite')continue;const publication=this.read(other.id,now);const report={title:publication?.title??String(normalized?.titleZh??other.title),summary:publication?.summary??String(normalized?.summaryZh??other.excerpt??''),source:other.source.name,firstParty:other.source.tier==='T1',at:other.publishedAt??other.discoveredAt,scope:String(normalized?.scope??'unknown') as 'single'|'composite'|'unknown'};const score=Relate.lexicalSimilarity(text,Relate.reportText(report.title,report.summary));const key=String(row.fact_id);const old=byFact.get(key);const root=this.get('SELECT f.id FROM facts f JOIN fact_articles fa ON fa.fact_id=f.id JOIN articles a ON a.id=fa.article_id WHERE f.story_id=? AND fa.role IN(?,?) ORDER BY coalesce(a.published_at,a.discovered_at),f.id LIMIT 1',row.story_id!,'primary','report');if(!old||score>old.score)byFact.set(key,{stamp:this.factStamp(key),factId:key,storyId:String(row.story_id),factTitle:String(row.fact_title),members:(old?.members??0)+1,storyRoot:root?.id===row.fact_id,score,report,selected:publication?.selected??false,selectedReport:publication?.selected?report:old?.selectedReport??null});else old.members++;}
  return [...byFact.values()].sort((a,b)=>b.score-a.score).slice(0,12);
 }
 private grouping(input:StorageOperations['grouping']['input']):boolean{return this.runtime.transaction(()=>{
  const parent=this.owned(input);const article=this.article(input.id);if(!parent||!article)return false;if(article.revision!==input.revision){this.done(input,{stale:true});return false;}
  const active=this.work(article.id);const writing=active?.steps.filter(step=>step.stage==='writing'&&(active.activeConfigRevision===0||step.configRevision===active.activeConfigRevision&&step.runKey===active.activeRun)).at(-1);if(input.sourceRevision!==undefined&&article.source.revision!==input.sourceRevision||input.analysisIdentity&&(!writing||writing.configRevision!==input.analysisIdentity.configRevision||writing.runKey!==input.analysisIdentity.runKey||writing.promptHash!==input.analysisIdentity.promptHash)){this.completeReceipts(input.receiptIds,input.epoch,input.now);this.done(input,{staleAnalysisOrSource:true});return false;}
  const control=Number(this.get('SELECT revision FROM grouping_controls WHERE article_id=?',input.id)?.revision??0);if(input.manualRevision!==undefined&&control!==input.manualRevision){this.completeReceipts(input.receiptIds,input.epoch,input.now);this.done(input,{manualDecisionChanged:true});return false;}
  if((input.candidateVersions??[]).some(candidate=>this.factStamp(candidate.factId)!==candidate.stamp)){this.completeReceipts(input.receiptIds,input.epoch,input.now);const payload=decode(parent.payload) as Record<string,Json>;if(Number(payload.candidateRefreshes??0)<2)this.runtime.enqueue({kind:'group',subject:article.id,key:`${input.epoch}:${article.id}@${article.revision}:candidate-refresh:${randomUUID()}`,epoch:input.epoch,inputRevision:article.revision,configRevision:Number(parent.config_revision),payload:{...payload,requests:{},candidateRefreshes:Number(payload.candidateRefreshes??0)+1},priority:90,maxAttempts:3,dueAt:input.now});this.done(input,{candidatesChanged:true});return false;}
  for(const merge of input.merges??[])this.mergeStories({...merge,now:input.now});
  const manual=this.get('SELECT * FROM grouping_overrides WHERE article_id=?',input.id);const normalized=this.normalized(article);const historical=Material.isHistorical({backfill:article.backfill,published_at:article.publishedAt===null?null:new Date(article.publishedAt),discovered_at:new Date(article.discoveredAt)});let factId:string|null=null,storyId:string|null=null;
  const sourceMode=article.source.participationMode;const composite=normalized?.scope==='composite'||input.decisions.some(d=>d.relation==='ROUNDUP');
  if(manual?.mode==='assign'){const fact=this.get('SELECT * FROM facts WHERE id=?',manual.fact_id!);if(fact){factId=String(fact.id);storyId=String(fact.story_id);}}
  else if(!manual&&!historical&&!composite&&sourceMode!=='isolated'){
   const matches=input.decisions.filter(d=>d.relation==='SAME_OCCURRENCE'&&d.confidence>=0.78||(sourceMode==='hot_signal'&&d.relation==='SAME_STORY'&&d.confidence>=0.8)).sort((a,b)=>b.confidence-a.confidence);
   const target=matches[0]?this.get('SELECT * FROM facts WHERE id=?',matches[0].factId):undefined;
   if(target){factId=String(target.id);storyId=String(target.story_id);}
   else if(sourceMode==='editorial'&&normalized?.fact){
    const development=input.decisions.filter(d=>d.relation==='SAME_STORY').sort((a,b)=>b.confidence-a.confidence).find(d=>this.candidates(article.id,input.now).some(c=>c.factId===d.factId&&c.storyRoot));
    const story=development?this.get('SELECT story_id FROM facts WHERE id=?',development.factId):undefined;storyId=story?String(story.story_id):randomUUID();const frame=normalized.fact as Record<string,Json>;const title=String(frame.title??normalized.titleZh??article.title);
    if(!story)this.run('INSERT INTO stories VALUES(?,?,?,?,NULL,?,?,?,?)',storyId,storyId,title,'active',1,article.publishedAt??article.discoveredAt,article.publishedAt??article.discoveredAt,encode({digest:null,latest:null,frame}));
    factId=randomUUID();this.run('INSERT INTO facts VALUES(?,?,?,?,?,?,?,?)',factId,factId,storyId,title,typeof frame.occurredAt==='string'?Date.parse(frame.occurredAt)||null:null,1,0,encode(frame));
   }
  }
  if(!manual)this.run('DELETE FROM fact_articles WHERE article_id=? AND manual=0',article.id);
  this.run('DELETE FROM story_signals WHERE article_id=?',article.id);
  if(composite&&!manual)for(const decision of input.decisions.filter(decision=>Relate.firmlyTied(decision.relation,decision.confidence))){if(this.get('SELECT id FROM facts WHERE id=?',decision.factId))this.run('INSERT OR IGNORE INTO fact_articles VALUES(?,?,?,?,?,?)',decision.factId,article.id,'mention',0,decision.note,article.revision);}
  if(factId&&storyId){this.run('INSERT INTO fact_articles VALUES(?,?,?,?,?,?) ON CONFLICT(fact_id,article_id) DO UPDATE SET role=excluded.role,grouping_revision=excluded.grouping_revision',factId,article.id,sourceMode==='hot_signal'?'mention':article.source.tier==='T1'?'primary':'report',Number(!!manual),null,article.revision);
   this.run('INSERT INTO story_signals VALUES(?,?,?,?,?,?)',storyId,article.id,article.source.signalGroupId?'group:'+article.source.signalGroupId:article.source.ownerEntityId?'owner:'+article.source.ownerEntityId:'source:'+article.source.id,article.source.id,sourceMode==='editorial'?'editorial':'signal',article.publishedAt??article.discoveredAt);
   this.run('UPDATE stories SET latest_at=max(coalesce(latest_at,0),?),version=version+1 WHERE id=?',article.publishedAt??article.discoveredAt,storyId);
  }
  article.groupingStatus='complete';this.writeArticle(article);this.run('UPDATE articles SET selection_adds_value=? WHERE id=?',Number(manual!==undefined||input.selection.addsValue),article.id);
  this.run('INSERT INTO grouping_decisions VALUES(?,?,?,?,?,?,?,?,?,?)',randomUUID(),article.id,article.revision,factId,storyId,composite?'ROUNDUP':input.decisions.find(d=>d.factId===factId)?.relation??'NEW',manual?'manual':'model',input.receiptIds[0]??null,encode({decisions:input.decisions,selection:input.selection}),input.now);
  this.completeReceipts(input.receiptIds,input.epoch,input.now);this.project(article.id,input.now);if(storyId&&article.source.participationMode==='editorial'){for(const row of this.all("SELECT a.id FROM articles a JOIN sources s ON s.id=a.source_id WHERE json_extract(s.document,'$.participationMode')='hot_signal' AND a.discovered_at>? AND NOT EXISTS(SELECT 1 FROM story_signals ss WHERE ss.article_id=a.id) LIMIT 100",input.now-14*86400000)){const signal=this.article(String(row.id));if(signal){const payload=decode(parent.payload) as Record<string,Json>;this.runtime.enqueue({kind:'group',subject:signal.id,key:`${input.epoch}:${signal.id}@${signal.revision}:signal-rematch:${storyId}`,epoch:input.epoch,inputRevision:signal.revision,configRevision:Number(parent.config_revision),payload,priority:50,maxAttempts:3,dueAt:input.now});}}}const publication=this.read(article.id,input.now);if(publication?.selected&&article.source.siteFulltext)this.next(parent,article,'translate',input.now);if(storyId&&article.source.participationMode==='editorial')this.enqueueDigest(parent,storyId,input.now);this.relatedStories(input.now);this.done(input,{factId,storyId});return true;
 });}
 private mergeStories(i:StorageOperations['mergeStories']['input']):boolean {
  const merge=()=>{if(i.survivor===i.other)throw new Error('Cannot merge a story into itself');const survivor=this.get('SELECT * FROM stories WHERE id=? AND merged_into IS NULL',i.survivor),other=this.get('SELECT * FROM stories WHERE id=? AND merged_into IS NULL',i.other);if(!survivor||!other)throw new Error('Active stories required');if(i.expectedSurvivor!==undefined&&Number(survivor.version)!==i.expectedSurvivor||i.expectedOther!==undefined&&Number(other.version)!==i.expectedOther)throw new Error('Story revision conflict');
   if(!i.commandId&&this.get('SELECT story_id FROM story_controls WHERE story_id IN(?,?) AND manual=1',i.survivor,i.other))return false;
   this.run('UPDATE facts SET story_id=?,version=version+1 WHERE story_id=?',i.survivor,i.other);this.run('INSERT OR IGNORE INTO story_signals SELECT ?,article_id,participant_key,source_id,kind,observed_at FROM story_signals WHERE story_id=?',i.survivor,i.other);this.run('DELETE FROM story_signals WHERE story_id=?',i.other);
   this.run('UPDATE stories SET merged_into=?,version=version+1 WHERE id=?',i.survivor,i.other);this.run('UPDATE stories SET first_report_at=min(coalesce(first_report_at,?),?),latest_at=max(coalesce(latest_at,0),?) WHERE id=?',other.first_report_at??i.now,other.first_report_at??i.now,other.latest_at??i.now,i.survivor);this.run('INSERT OR REPLACE INTO story_aliases VALUES(?,?,?)',other.public_id!,i.survivor,i.now);
   this.run('DELETE FROM story_links WHERE (story_id=? AND other_id=?) OR (story_id=? AND other_id=?)',i.survivor,i.other,i.other,i.survivor);
   if(i.commandId){this.protectStory(i.survivor,i.now);for(const row of this.all("SELECT article_id,fact_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE f.story_id=? AND fa.role!='mention'",i.survivor)){const article=this.article(String(row.article_id));if(!article)continue;const rev=this.correctionState(article.id)!.groupingRevision+1;this.run('INSERT INTO grouping_controls VALUES(?,?,?) ON CONFLICT(article_id) DO UPDATE SET revision=excluded.revision,updated_at=excluded.updated_at',article.id,rev,i.now);this.run('INSERT INTO grouping_overrides VALUES(?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET mode=excluded.mode,fact_id=excluded.fact_id,reason=excluded.reason,revision=excluded.revision,created_at=excluded.created_at',article.id,'assign',row.fact_id!,i.reason??'',rev,i.now);}}
   for(const row of this.all('SELECT article_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE f.story_id=?',i.survivor))this.project(String(row.article_id),i.now);this.invalidateStory(i.survivor,i.now);return true;
  };return i.commandId?this.command(i.commandId,'story-merge',i.survivor,i.reason??'',{survivor:i.survivor,other:i.other,expectedSurvivor:i.expectedSurvivor,expectedOther:i.expectedOther},i.now,merge):merge();
 }
 private story(id:string):Story|null{let row=this.get('SELECT * FROM stories WHERE id=? OR public_id=?',id,id);if(!row){const alias=this.get('SELECT story_id FROM story_aliases WHERE public_id=?',id);if(alias)row=this.get('SELECT * FROM stories WHERE id=?',alias.story_id!);}if(!row)return null;if(row.merged_into!==null)return this.story(String(row.merged_into));const document=decode(row.document) as {digest:string|null;latest:string|null};const facts=this.all('SELECT * FROM facts WHERE story_id=? ORDER BY coalesce(occurred_at,0),id',row.id!).map(f=>({id:String(f.id),title:String(f.title),articleIds:this.all("SELECT fa.article_id FROM fact_articles fa JOIN articles a ON a.id=fa.article_id WHERE fa.fact_id=? AND fa.role IN('primary','report') ORDER BY a.timeline_at,fa.article_id",f.id!).map(a=>String(a.article_id)).filter(a=>this.read(a)!==null)}));const visibleFacts=facts.filter(f=>f.articleIds.length>0);const ids=[...new Set(visibleFacts.flatMap(f=>f.articleIds))];const articles=ids.flatMap(id=>{const item=this.read(id);return item?[item]:[];}).sort((a,b)=>a.timelineAt-b.timelineAt||a.id.localeCompare(b.id));const copy=projectDigest(document.digest??null,articles,articles.map(item=>this.article(item.id)?.bodyText??''));return {id:String(row.id),publicId:String(row.public_id),title:String(row.title),status:String(row.status),version:Number(row.version),mergedInto:null,digestFallback:copy.fallback,digest:copy.digest,latest:document.latest??null,firstReportAt:row.first_report_at===null?null:Number(row.first_report_at),latestAt:row.latest_at===null?null:Number(row.latest_at),facts:visibleFacts,articles,links:this.all('SELECT other_id FROM story_links WHERE story_id=?',row.id!).map(r=>String(r.other_id)),heatSeries:new HeatRepository(this.db,(id,at)=>this.read(id,at),()=>null).series(String(row.id),Date.now())};}
 private heat(now:number,compute:boolean,epoch:number):HeatEntry[]{
  if(compute){if(this.runtime.state().epoch!==epoch)throw new Error('Stale runtime epoch');return new HeatRepository(this.db,(id,at)=>this.read(id,at),id=>this.story(id)).ranking(now);}
  const row=this.get('SELECT entries FROM hot_rankings WHERE published=1 ORDER BY computed_at DESC LIMIT 1');return row?(decode(row.entries) as HeatEntry[]).filter(entry=>(this.story(entry.storyId)?.articles.length??0)>0):[];
 }
 private ui():UiQueries{return new UiQueries(this.db,()=>this.runtime.state(),id=>this.read(id),id=>this.bookmark(id),row=>this.filterReport(this.reportRow(row)));}
 private compileHistory(input:StorageOperations['compileHistory']['input']):StorageOperations['compileHistory']['output']{return this.runtime.transaction(()=>{
  const state=this.runtime.state();if(!state.initialized||state.deleting||!state.settings)throw new Error('Initialize first');if(state.revision!==input.revision)throw new Error('Configuration revision conflict');
  const hash=createHash('sha256').update(encode({revision:input.revision,epoch:state.epoch,mode:'historical'})).digest('hex');const old=this.get('SELECT * FROM command_receipts WHERE command_id=?',input.commandId);if(old){const result=decode(old.result) as {hash:string;value:StorageOperations['compileHistory']['output']};if(old.kind!=='compile-history'||old.epoch!==state.epoch||result.hash!==hash)throw new Error('Command identity conflict');return result.value;}
  const active=Number(this.get("SELECT count(*) n FROM jobs WHERE epoch=? AND kind='report' AND json_extract(payload,'$.historical')=1 AND state IN('queued','running','retry_wait','blocked')",state.epoch)?.n??0);
  const latest=Reports.dueDaily(new Date(input.now));const data=new ReportData(this.db,(id,at)=>this.read(id,at));
  const days=this.all("SELECT DISTINCT date(a.published_at/1000,'unixepoch','+1 day') period FROM publications p JOIN articles a ON a.id=p.article_id JOIN sources s ON s.id=a.source_id WHERE p.selected=1 AND p.visibility='public' AND p.eligible=1 AND a.published_at IS NOT NULL AND json_extract(s.document,'$.participationMode')='editorial' ORDER BY period").map(row=>String(row.period)).filter(key=>key<=latest).slice(-366);
  const daily=days.filter(key=>!this.get("SELECT id FROM reports WHERE kind='daily' AND period_key=?",key)).filter(key=>{const end=Time.beijingMidnight(key).getTime()+8*3600000;return Edition.arrangeDaily(data.daily(key,end-86400000,end,true,input.now).entries).main.length>0;}).map(key=>({kind:'daily' as const,key}));
  const periods:Array<{kind:'weekly'|'monthly';key:string}>=[];
  if(!daily.length){const saved=this.all("SELECT period_key FROM reports WHERE kind='daily' ORDER BY period_key").map(row=>String(row.period_key));for(const kind of ['weekly','monthly'] as const){const limit=kind==='weekly'?Reports.dueWeekly(new Date(input.now)):Reports.dueMonthly(new Date(input.now));for(const key of [...new Set(saved.map(day=>kind==='weekly'?Time.isoWeekLabel(day):day.slice(0,7)))].sort()){if(key>limit||this.get('SELECT id FROM reports WHERE kind=? AND period_key=?',kind,key))continue;const range=kind==='weekly'?Time.isoWeekRange(key):Time.monthRange(key);if(range&&data.period(range.start,range.end,input.now,true).entries.length)periods.push({kind,key});}}}
  const candidates=[...daily,...periods];let enqueued=0;if(!active)for(const edition of candidates.slice(0,8)){this.runtime.enqueue({kind:'report',subject:edition.kind+':'+edition.key,key:`report-history:${state.epoch}:${edition.kind}:${edition.key}`,epoch:state.epoch,inputRevision:0,configRevision:state.revision,payload:{...edition,historical:true,settings:JSON.parse(encode(state.settings)) as Json,compilationCommandId:input.commandId},priority:100,maxAttempts:3,dueAt:input.now});enqueued++;}
  const value={enqueued,remaining:candidates.length,active,complete:candidates.length===0&&active===0};this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',input.commandId,'compile-history',state.epoch,input.now,encode({hash,value}));return value;
 });}
 private reportMaterialHash(kind:string,key:string):string {const rows=kind==='daily'?this.all("SELECT p.article_id,p.input_revision,p.selected,p.visibility,p.visible_after,p.title,p.summary FROM publications p WHERE date(max(p.publication_time,coalesce(p.visible_after,p.publication_time))/1000,'unixepoch','+1 day')=? ORDER BY p.article_id",key):this.all("SELECT id,revision,content FROM reports WHERE kind='daily' AND period_key>=? AND period_key<=? ORDER BY period_key",...(kind==='weekly'?Object.values(Time.isoWeekRange(key)??{}):Object.values(Time.monthRange(key)??{})) as string[]);return createHash('sha256').update(encode(rows)).digest('hex');}
 private reportRow(row:Row):Report{return {id:String(row.id),kind:row.kind as Report['kind'],key:String(row.period_key),timeZone:String(row.time_zone),windowStart:Number(row.window_start),windowEnd:Number(row.window_end),createdAt:Number(row.created_at),revision:Number(row.revision),content:decode(row.content) as Record<string,Json>,coverage:(decode(row.content) as Record<string,Json>).coverage&&((decode(row.content) as Record<string,Json>).coverage as Record<string,Json>).complete===false?'incomplete':'evidence-based'};}
 private filterReport(report:Report):Report{
  let changed=false;const allowed=new Set<string>();
  const filter=(value:Json):Json=>{if(Array.isArray(value))return value.flatMap(item=>{const result=filter(item);return result===null?[]:[result];});if(value!==null&&typeof value==='object'){const id=value.itemId??value.articleId;if(typeof id==='string'){const publication=this.read(id);if(!publication||publication.visibility!=='public'){changed=true;return null;}allowed.add(id);if(value.title!==undefined&&(value.title!==publication.title||value.summary!==publication.summary))changed=true;return {...Object.fromEntries(Object.entries(value).map(([key,item])=>[key,filter(item)])),title:publication.title,summary:publication.summary,sourceName:publication.sourceName,sourceUrl:publication.url,body:null};}return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,filter(item)]));}return value;};
  const content=filter(report.content) as Record<string,Json>;const sections=Array.isArray(content.sections)?content.sections:[];const main=sections.flatMap(section=>section&&typeof section==='object'&&!Array.isArray(section)&&Array.isArray(section.items)?section.items:[]).filter((item):item is Record<string,Json>=>!!item&&typeof item==='object'&&!Array.isArray(item));
  if(typeof content.leadItemId==='string'){const lead=this.read(content.leadItemId);if(lead&&lead.visibility==='public'){content.lead={title:lead.title,leadParagraph:lead.summary};if(typeof content.headline==='string')content.headline=lead.title;}else{changed=true;const replacement=main[0];content.leadItemId=replacement?.itemId??null;content.lead=replacement?{title:replacement.title??'',leadParagraph:replacement.summary??''}:null;content.headline=replacement?.title??null;}}
  if(Array.isArray(content.highlights))content.highlights=content.highlights.filter(value=>typeof value!=='string'||allowed.has(value));
  if(changed){content.overview=null;for(const section of sections)if(section&&typeof section==='object'&&!Array.isArray(section))section.intro=null;content.correctedAtRead=true;}
  if(content.metrics&&typeof content.metrics==='object'&&!Array.isArray(content.metrics)&&report.kind==='daily')content.metrics={...content.metrics,totalEvents:main.length,firstPartyEvents:main.filter(item=>item.firstParty===true).length,sourcesCount:new Set(main.flatMap(item=>[String(item.sourceId??''),...Array.isArray(item.related)?item.related.map(raw=>raw&&typeof raw==='object'&&!Array.isArray(raw)?String(raw.sourceId??''):''):[]]).filter(Boolean)).size};
  return {...report,content};
 }

 handlers():{[K in BusinessKey]:(i:StorageOperations[K]['input'])=>StorageOperations[K]['output']}{return {
  materialsKnown:i=>i.keys.flatMap(key=>{const row=this.get('SELECT identity_key,id,title,body_status,discovered_at,document FROM articles WHERE identity_key=?',key);if(!row)return [];const document=decode(row.document) as Article;return [{key:String(row.identity_key),id:String(row.id),title:String(row.title),bodyStatus:String(row.body_status),discoveredAt:Number(row.discovered_at),raw:document.raw}];}),
  candidatesPage:i=>{const filter="s.kind='rss' AND s.deleted_at IS NULL AND (instr(lower(a.title),lower(?))>0 OR instr(lower(s.name),lower(?))>0)";const total=Number(this.get('SELECT count(*) n FROM articles a JOIN sources s ON s.id=a.source_id WHERE '+filter,i.query,i.query)?.n??0);const items=this.all('SELECT a.*,s.name source_name,coalesce(p.selected,0) selected FROM articles a JOIN sources s ON s.id=a.source_id LEFT JOIN publications p ON p.article_id=a.id WHERE '+filter+' ORDER BY coalesce(a.published_at,a.discovered_at) DESC,a.id LIMIT ? OFFSET ?',i.query,i.query,i.limit,i.offset).map(row=>({id:String(row.id),sourceId:String(row.source_id),sourceName:String(row.source_name),title:String(row.title),url:publicCitationUrl(String(row.url)),publishedAt:row.published_at===null?null:Number(row.published_at),discoveredAt:Number(row.discovered_at),revision:Number(row.revision),bodyStatus:String(row.body_status),processingState:String(row.processing_state),groupingStatus:String(row.grouping_status),backfill:row.backfill===1,selected:row.selected===1,error:this.get("SELECT error FROM jobs WHERE subject=? AND state IN('failed','blocked') ORDER BY created_at DESC LIMIT 1",row.id!)?.error as string|null??null}));return {items,total};},
  work:i=>this.work(i.id),collection:i=>this.collection(i),extraction:i=>this.extraction(i),analysis:i=>this.analysis(i),candidates:i=>this.candidates(i.id,i.now),grouping:i=>this.grouping(i),page:i=>this.page(i),detail:i=>this.read(i.id,Date.now(),true),
  marks:i=>{const p=this.get('SELECT * FROM publications WHERE article_id=?',i.id);if(!p)return false;this.run('INSERT INTO user_marks VALUES(?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET bookmarked=coalesce(?,bookmarked),read_at=CASE WHEN ? THEN ? ELSE read_at END',i.id,Number(i.bookmarked??false),i.read?i.now:null,encode({title:p.title}),i.bookmarked===null?null:Number(i.bookmarked),Number(i.read),i.now);return true;},
  override:i=>this.command(i.commandId,'editorial-correction',i.id,i.reason,{id:i.id,expectedRevision:i.expectedRevision,visibility:i.visibility,fields:i.fields},i.now,()=>{const article=this.article(i.id);if(!article)throw new Error('Article missing');const current=this.get('SELECT * FROM editorial_overrides WHERE article_id=?',i.id);if(Number(current?.version??0)!==i.expectedRevision)throw new Error('Editorial override revision conflict');const allowed=new Set(['title','summary','titleZh','summaryZh','category','tags','score','selected','relevance']);if(Object.keys(i.fields).some(k=>!allowed.has(k)))throw new Error('Unsupported editorial field');this.run('INSERT INTO editorial_overrides VALUES(?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET version=excluded.version,visibility=excluded.visibility,fields=excluded.fields,reason=excluded.reason,updated_at=excluded.updated_at',i.id,i.expectedRevision+1,i.visibility,encode({...current?decode(current.fields) as Record<string,Json>:{},...i.fields}),i.reason,i.now);const story=this.correctionState(i.id)?.storyId;this.project(i.id,i.now);if(story)this.invalidateStory(story,i.now);return true;}),
  correctEvent:i=>this.correctEvent(i),splitStory:i=>this.splitStory(i),correctionState:i=>this.correctionState(i.id),
  mutationHistory:i=>this.all('SELECT command_id,kind,subject_id,reason,before_json,after_json,at FROM mutation_history ORDER BY at DESC LIMIT ? OFFSET ?',i.limit,i.offset).map(row=>({commandId:String(row.command_id),kind:String(row.kind),subjectId:String(row.subject_id),reason:String(row.reason),before:row.before_json===null?null:decode(row.before_json) as Json,after:row.after_json===null?null:decode(row.after_json) as Json,at:Number(row.at)})),
  storyDigestWork:i=>this.digestWork(i.id),
  storyDigest:i=>{if(!this.owned(i))return false;const work=this.digestWork(i.id);this.completeReceipts(i.receiptIds,i.epoch,i.now);if(!work||work.version!==i.revision||work.inputsHash!==i.inputsHash){this.done(i,{stale:true});return false;}const row=this.get('SELECT document FROM stories WHERE id=?',i.id)!;const doc=decode(row.document) as Record<string,Json>;const version=i.revision+1;this.run('INSERT INTO story_digests VALUES(?,?,?,?,?,?,?,?)',i.id,version,i.digest,i.latest,i.receiptIds[0]??null,encode((work.reports as Record<string,Json>[]).map(r=>r.id)),i.inputsHash,i.now);this.run('UPDATE stories SET document=?,version=? WHERE id=?',encode({...doc,digest:i.digest,latest:i.latest}),version,i.id);this.done(i,{version});return true;},
  sourceReproject:i=>{for(const row of this.all('SELECT id FROM articles WHERE source_id=?',i.id)){const id=String(row.id),article=this.article(id)!;this.run('DELETE FROM story_signals WHERE article_id=?',id);const member=this.correctionState(id);if(member?.storyId)this.signal(article,member.storyId);this.project(id,i.now);if(member?.storyId&&i.refreshDigest!==false)this.invalidateStory(member.storyId,i.now);}return true;},
  mergeStories:i=>this.mergeStories(i),
  story:i=>this.story(i.id),stories:i=>this.all('SELECT id FROM stories WHERE merged_into IS NULL ORDER BY latest_at DESC LIMIT ? OFFSET ?',i.limit,i.offset).flatMap(r=>{const story=this.story(String(r.id));return story&&story.articles.length?[story]:[];}),heat:i=>this.heat(i.now,i.compute,i.epoch),
  topics:()=>this.all('SELECT definition FROM topics ORDER BY position,id').map(r=>{const topic=decode(r.definition) as Topic;return {...topic,tags:[...topicMembershipTags(topic)]};}),seedTopics:i=>this.runtime.transaction(()=>{let position=0;for(const topic of i.topics)this.run('INSERT OR IGNORE INTO topics VALUES(?,?,?,?)',topic.id,topic.kind,position++,encode(topic));return true;}),
  reportRevisions:i=>this.all('SELECT revision,reason,generated_at FROM report_revisions WHERE report_id=? ORDER BY revision DESC',i.id).map(row=>({revision:Number(row.revision),reason:row.reason===null?null:String(row.reason),generatedAt:Number(row.generated_at)})),
  reportRegenerate:i=>this.runtime.transaction(()=>{if(this.get('SELECT command_id FROM report_commands WHERE command_id=?',i.commandId))return true;const report=this.get('SELECT * FROM reports WHERE id=?',i.id);const state=this.runtime.state();if(!report||Number(report.revision)!==i.expectedRevision)throw new Error('Report revision conflict');if(!state.initialized||!state.settings)throw new Error('Initialize first');this.run('INSERT INTO report_commands VALUES(?,?,?,?,?)',i.commandId,i.id,i.expectedRevision,i.reason,i.now);this.runtime.enqueue({kind:'report',subject:String(report.kind)+':'+String(report.period_key),key:`report:${state.epoch}:${report.kind}:${report.period_key}:rerun:${i.commandId}`,epoch:state.epoch,inputRevision:i.expectedRevision,configRevision:state.revision,payload:{historical:(decode(report.content) as {generator?:{historical?:boolean}}).generator?.historical===true,kind:String(report.kind),key:String(report.period_key),reportId:i.id,expectedRevision:i.expectedRevision,reason:i.reason,commandId:i.commandId,settings:JSON.parse(encode(state.settings)) as Json},priority:100,maxAttempts:3,dueAt:i.now});return true;}),
  preferenceGet:()=>{const row=this.get("SELECT value FROM user_preferences WHERE key='ui'");return row?decode(row.value) as import('dsh-hotstream-contracts').PreferenceResult:{revision:0,values:{}};},
  preferenceSave:i=>{const old=this.get('SELECT * FROM command_receipts WHERE command_id=?',i.commandId);if(old){if(old.kind!=='preferences')throw new Error('Command identity conflict');return decode(old.result) as import('dsh-hotstream-contracts').PreferenceResult;}const row=this.get("SELECT value FROM user_preferences WHERE key='ui'");const current=row?decode(row.value) as {revision:number}: {revision:0};if(current.revision!==i.expectedRevision)throw new Error('Preference revision conflict');if(encode(i.values).length>32768)throw new Error('Preference data too large');const result={revision:current.revision+1,values:i.values};this.run("INSERT INTO user_preferences VALUES('ui',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",encode(result));this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',i.commandId,'preferences',this.runtime.state().epoch,i.now,encode(result));return result;},
  reportCheck:i=>{const range=i.kind==='weekly'?Time.isoWeekRange(i.key):i.kind==='monthly'?Time.monthRange(i.key):null;const data=new ReportData(this.db,(id,at)=>this.read(id,at));if(i.kind==='daily'){const end=Time.beijingMidnight(i.key).getTime()+8*3600000;const material=data.daily(i.key,end-86400000,end);if(Edition.arrangeDaily(material.entries).main.length)return false;}else if(range&&data.period(range.start,range.end,i.now).entries.length)return false;this.run('INSERT INTO report_schedule_checks VALUES(?,?,?,?) ON CONFLICT(kind,period_key) DO UPDATE SET material_hash=excluded.material_hash,checked_at=excluded.checked_at',i.kind,i.key,this.reportMaterialHash(i.kind,i.key),i.now);return true;},
  reportMissing:i=>{let keys:string[]=[];if(i.kind==='daily')keys=this.all("SELECT DISTINCT date(max(p.publication_time,coalesce(p.visible_after,p.publication_time))/1000,'unixepoch','+1 day') period FROM publications p JOIN articles a ON a.id=p.article_id WHERE p.visibility='public' AND p.eligible=1 AND a.backfill=0 ORDER BY period").map(row=>String(row.period));else{const days=this.all("SELECT period_key FROM reports WHERE kind='daily' AND coalesce(json_extract(content,'$.generator.historical'),0)=0 ORDER BY period_key").map(row=>String(row.period_key));keys=days.map(day=>i.kind==='monthly'?day.slice(0,7):Time.isoWeekLabel(day));}return [...new Set(keys)].filter(key=>key<=i.latest&&!this.get('SELECT id FROM reports WHERE kind=? AND period_key=?',i.kind,key)&&!this.get('SELECT period_key FROM report_schedule_checks WHERE kind=? AND period_key=? AND material_hash=?',i.kind,key,this.reportMaterialHash(i.kind,key))).slice(0,i.limit);},
  mediaReference:i=>{const state=this.runtime.state(),publication=this.read(i.id,Date.now(),true);if(!state.initialized||state.deleting||!publication?.body||publication.visibility!=='public'||publication.revision!==i.revision)return null;const article=this.article(i.id)!;const item=readingMedia(article.media,article.bodyHtml,article.url)[i.index];return item?.kind==='image'?{epoch:state.epoch,url:item.url,cacheDays:state.settings?.retention.cacheDays??7,dnsMode:state.settings?.network.dnsMode??'system',publicProxyUrl:state.settings?.network.publicProxyUrl??null}:null;},
  uiMonitor:i=>readUiMonitor(this.db,this.runtime.state(),i),
  uiArticle:i=>{const item=this.read(i.id,Date.now(),true);if(!item)return {item:null,bodyState:'unavailable',images:[]};const article=this.article(i.id)!;const bodyState=item.visibility!=='public'?'summary-only':!article.source.siteFulltext?'source-disabled':article.bodyStatus==='ok'&&(item.body||item.bodyHtml)?'full':'unavailable';return {item,bodyState,images:bodyState==='full'?readingMedia(article.media,article.bodyHtml,article.url).map((m,index)=>({index,url:m.url,alt:m.alt})):[]};},
  uiFeed:i=>this.ui().feed(i),uiGroups:i=>this.ui().groups(i),uiReportIndex:i=>this.ui().reportIndex(i),uiReport:i=>this.ui().reportView(i),compileHistory:i=>this.compileHistory(i),dailyEdition:i=>{const result=new ReportData(this.db,(id,at)=>this.read(id,at)).daily(i.date,i.start,i.end,i.historical??false,i.asOf??Date.now());return {entries:result.entries.map(entry=>({...entry,sourceIds:[...entry.sourceIds],mentions:[...entry.mentions]}) as unknown as Record<string,Json>),stats:result.stats};},periodEntries:i=>{const result=new ReportData(this.db,(id,at)=>this.read(id,at)).period(i.startDate,i.endDate,i.now,i.historical??false);return {entries:result.entries as unknown as Record<string,Json>[],issues:result.issues};},
  reports:i=>this.all('SELECT * FROM reports WHERE kind=? ORDER BY window_end DESC LIMIT ? OFFSET ?',i.kind,i.limit,i.offset).map(r=>this.filterReport(this.reportRow(r))),report:i=>{const r=this.get('SELECT * FROM reports WHERE id=?',i.id);return r?this.filterReport(this.reportRow(r)):null;},reportMaterial:i=>({items:this.all("SELECT article_id FROM publications WHERE selected=1 AND seat=1 AND publication_time>=? AND publication_time<? ORDER BY score DESC,publication_time",i.start,i.end).flatMap(r=>{const p=this.read(String(r.article_id));return p?[p]:[];}),reports:this.all("SELECT * FROM reports WHERE kind='daily' AND window_end>? AND window_end<=? ORDER BY window_end",i.start,i.end).map(r=>this.filterReport(this.reportRow(r)))}),saveReport:i=>this.runtime.transaction(()=>{const state=this.runtime.state();if(state.epoch!==i.epoch||state.deleting||i.jobId&&!this.owned({jobId:i.jobId,owner:i.owner??'',epoch:i.epoch,now:Date.now()}))throw new Error('Stale report transaction');const command=this.all('SELECT j.payload FROM jobs j WHERE j.id=?',i.jobId??'').map(row=>decode(row.payload) as Record<string,Json>).find(payload=>payload.commandId);if(command){const existing=this.get('SELECT * FROM reports WHERE id=?',String(command.reportId));if(!existing||Number(existing.revision)!==Number(command.expectedRevision))throw new Error('Report revision conflict');this.run('INSERT INTO report_revisions VALUES(?,?,?,?,?)',existing.id!,existing.revision!,existing.content!,existing.created_at!,String(command.reason));this.run('UPDATE reports SET revision=revision+1,content=?,created_at=? WHERE id=?',encode(i.report.content),i.report.createdAt,existing.id!);this.completeReceipts(i.receiptIds,i.epoch,i.report.createdAt);return true;}if(this.runtime.state().epoch!==i.epoch)throw new Error('Stale runtime epoch');const r=i.report;const changed=this.run('INSERT OR IGNORE INTO reports VALUES(?,?,?,?,?,?,?,?,?,?)',r.id,r.kind,r.key,r.timeZone,r.windowStart,r.windowEnd,r.createdAt,r.revision,r.kind==='daily'?'rule':'model',encode(r.content));this.completeReceipts(i.receiptIds,i.epoch,r.createdAt);return changed===1;}),
  vectorGet:i=>{const row=this.get('SELECT vector FROM embeddings WHERE service=? AND model=? AND dimension=? AND text_hash=? LIMIT 1',i.service,i.model,i.dimension,i.hash);if(!row||!(row.vector instanceof Uint8Array))return null;const bytes=Buffer.from(row.vector);return Array.from({length:i.dimension},(_,index)=>bytes.readFloatLE(index*4));},
  vectorPut:i=>{if(this.runtime.state().epoch!==i.epoch||i.vector.length!==i.dimension)throw new Error('Embedding identity or dimension mismatch');const bytes=Buffer.alloc(i.dimension*4);i.vector.forEach((value,index)=>bytes.writeFloatLE(value,index*4));this.run('INSERT OR REPLACE INTO embeddings VALUES(?,?,?,?,?,?)',i.subjectId,i.service,i.model,i.dimension,i.hash,bytes);return true;},
  collectionBatch:i=>this.runtime.transaction(()=>{if(!this.owned(i))return {committed:false,created:0,revised:0};let created=0,revised=0;for(const member of i.members){const result=this.collection({...i,...member},false);if(!result.committed)throw new Error('Shard source changed before commit');created+=result.created;revised+=result.revised;}this.done(i,{created,revised});return {committed:true,created,revised};}),
  translation:i=>this.runtime.transaction(()=>{if(!this.owned(i))return false;const article=this.article(i.id);if(!article||article.revision!==i.revision){this.completeReceipts(i.receiptIds,i.epoch,i.now);this.done(i,{stale:true});return false;}this.run(`INSERT INTO translations VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(article_id,lang) DO UPDATE SET revision=excluded.revision,complete=excluded.complete,receipt_id=excluded.receipt_id,document=excluded.document,created_at=excluded.created_at WHERE translations.origin!='source' AND translations.revision<=excluded.revision`,i.id,'zh',i.revision,Number(i.complete),'model',i.receiptIds[0]??null,encode({title:i.title,html:i.html,text:i.text}),i.now);this.completeReceipts(i.receiptIds,i.epoch,i.now);this.done(i,{translated:true,complete:i.complete});return true;}),
  chronicle:i=>{const row=this.get('SELECT definition FROM topics WHERE id=?',i.id);if(!row)return {topicId:i.id,kinds:CHRONICLE_KINDS,months:[],highlights:[]};const topic=decode(row.definition) as Topic;const company=topic.kind==='company';const entity=topic.entityId;const t:ChronicleTopic={slug:topic.id,group:topic.kind as ChronicleTopic['group'],entityId:entity,terms:company?null:new RegExp(topic.chronicleTerms.map(tag=>tag.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')||topic.name,'i'),orgNames:topic.orgNames};const reports:ChronicleReport[]=[];
   for(const row of this.all("SELECT p.article_id,p.fact_id,f.frame_json,f.occurred_at FROM publications p LEFT JOIN facts f ON f.id=p.fact_id WHERE p.selected=1 AND p.visibility!='withdrawn' AND p.publication_time>?",i.now-400*86400000)){const publication=this.read(String(row.article_id),i.now);if(!publication)continue;if(!belongsToTopic(publication,topic))continue;const article=this.article(publication.id)!;const normalized=this.normalized(article);const frame=row.frame_json===null?{}:decode(row.frame_json) as Record<string,Json>;const factRows=publication.factId?this.all('SELECT a.published_at FROM fact_articles fa JOIN articles a ON a.id=fa.article_id JOIN publications p ON p.article_id=a.id WHERE fa.fact_id=? AND p.selected=1 AND p.visibility!=?',publication.factId,'withdrawn'):[];const times=factRows.flatMap(r=>r.published_at===null?[]:[Number(r.published_at)]);reports.push({id:publication.id,title:publication.title,originalTitle:publication.originalTitle,category:publication.category,tags:[...publication.tags,...publication.subjects.map(s=>'entity:'+s)],score:publication.score,topicSlugs:[topic.id],timelineAt:new Date(publication.timelineAt),publishedAt:publication.publishedAt===null?null:new Date(publication.publishedAt),factPublishedAt:times.length?new Date(Math.min(...times)):null,firstParty:publication.firstParty,owner:article.source.ownerEntityId,factId:publication.factId,factSubject:typeof frame.subject==='string'?frame.subject:null,factAction:typeof frame.action==='string'?frame.action:null,factOccurredAt:row.occurred_at===null?null:new Date(Number(row.occurred_at)),storyPublicId:publication.storyId,sourceCount:factRows.length,scope:typeof normalized?.scope==='string'?normalized.scope:null});}
   return {topicId:topic.id,kinds:CHRONICLE_KINDS,months:selectTopicChronicle(t,reports,{now:new Date(i.now)}),highlights:selectTopicHighlights(t,reports,{now:new Date(i.now)})};},
  evaluations:i=>({runs:this.all('SELECT * FROM selectbench_runs ORDER BY created_at DESC LIMIT ? OFFSET ?',i.limit,i.offset).map(r=>({id:String(r.id),label:String(r.label),sampleSize:Number(r.sample_size),models:decode(r.models) as Json,summary:decode(r.summary) as Json,createdAt:Number(r.created_at)})),results:this.all('SELECT * FROM selectbench_results WHERE run_id IN(SELECT id FROM selectbench_runs ORDER BY created_at DESC LIMIT ? OFFSET ?)',i.limit,i.offset).map(r=>({...decode(r.result) as Record<string,Json>,runId:String(r.run_id),model:String(r.model),caseId:String(r.case_id),gold:String(r.gold),decision:String(r.decision),error:r.error===null?null:String(r.error)}))}),
  evaluationSave:i=>this.runtime.transaction(()=>{if(this.runtime.state().epoch!==i.epoch)throw new Error('Stale evaluation epoch');this.run('INSERT OR IGNORE INTO selectbench_runs VALUES(?,?,?,?,?,?,?,?)',i.id,i.label,new Set(i.results.map(r=>String(r.caseId))).size,null,i.promptVersion,encode(i.models),encode(i.summary),i.now);this.run('UPDATE selectbench_runs SET summary=?,sample_size=? WHERE id=?',encode(i.summary),new Set(i.results.map(result=>String(result.caseId))).size,i.id);for(const r of i.results)this.run('INSERT OR IGNORE INTO selectbench_results VALUES(?,?,?,?,?,?,?,?,?,?,?)',i.id,String(r.model),String(r.caseId),String(r.gold),typeof r.meanScore==='number'?r.meanScore:null,typeof r.score1==='number'?r.score1:null,typeof r.score2==='number'?r.score2:null,String(r.decision),encode(r),encode(r.receiptIds??[]),typeof r.error==='string'?r.error:null);return true;}),
  sourceFailure:i=>{const state=this.runtime.state();const source=this.source(i.id);if(state.epoch!==i.epoch||!source||source.revision!==i.revision)return false;const row=this.get('SELECT fail_count FROM sources WHERE id=?',i.id)!;const failures=Number(row.fail_count)+(i.blocked?0:1);this.run('UPDATE sources SET fail_count=?,next_due_at=?,document=? WHERE id=?',failures,i.retryAt,encode({...source,health:i.blocked?'blocked':failures>=5?'failing':'degraded',lastError:i.error}),i.id);this.run('INSERT INTO fetch_runs(id,source_id,started_at,finished_at,status,error) VALUES(?,?,?,?,?,?)',randomUUID(),i.id,i.now,i.now,i.blocked?'skipped':'failed',i.error);return true;},
  nextWake:()=>({at:(()=>{const row=this.get("SELECT min(due) n FROM(SELECT due_at due FROM jobs WHERE state IN('queued','retry_wait','blocked') AND epoch=(SELECT epoch FROM plugin_state WHERE id=1) AND "+jobAdmissionSql+" UNION ALL SELECT next_due_at due FROM sources WHERE enabled=1 AND deleted_at IS NULL AND kind!='external' AND (SELECT json_extract(settings_json,'$.autoCollectEnabled') FROM plugin_state WHERE id=1)=1)");return row?.n===null||row===undefined?null:Number(row.n);})()}),
  rerun:i=>this.runtime.transaction(()=>this.command(i.commandId,'article-rerun',i.id,'',{id:i.id,scope:i.scope},i.now,()=>{const article=this.article(i.id);const state=this.runtime.state();if(!article)return false;const authorization=this.get('SELECT id FROM model_authorizations WHERE active=1 ORDER BY created_at DESC LIMIT 1');if(!state.initialized||state.deleting||!state.settings)throw new Error('Initialize first');if(i.scope==='translation'){const publication=this.read(i.id,i.now,true);if(!publication?.selected||!publication.body||publication.visibility!=='public')throw new Error('Translation requires selected, permitted full text');const pending=this.get("SELECT id FROM jobs WHERE subject=? AND kind='translate' AND state IN('queued','running','retry_wait','blocked')",i.id);if(pending)throw new Error('Translation is already pending');}const kind=i.scope==='translation'?'translate':i.scope==='grouping'?'group':article.bodyStatus==='pending'?'extract':'prefilter';if(i.scope==='editorial'){this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE subject=? AND kind IN('extract','prefilter','score1','score2','structure','writing','translate','group') AND state IN('queued','retry_wait','blocked')",i.id);this.run('UPDATE articles SET active_run=?,active_config_revision=? WHERE id=?',i.commandId,state.revision,i.id);}this.runtime.enqueue({kind,subject:i.id,key:`${state.epoch}:${i.id}@${article.revision}:${kind}:rerun:${i.commandId}`,epoch:state.epoch,inputRevision:article.revision,configRevision:state.revision,payload:{rerun:i.commandId,settings:JSON.parse(encode(state.settings)) as Json,authorizationId:this.get('SELECT id FROM model_authorizations WHERE epoch=? AND active=1',state.epoch)?.id as string??null,articleId:i.id,sourceSnapshot:JSON.parse(encode(article.source)) as Json},priority:100,maxAttempts:5,dueAt:i.now});return true;})),maintenance:i=>({logs:this.run('DELETE FROM ordinary_run_logs WHERE at<?',i.now-(this.runtime.state().settings?.retention.ordinaryLogDays??30)*86400000),cache:this.run('DELETE FROM cached_responses WHERE expires_at<?',i.now)}),
 };}
}
