import {jobAdmissionSql} from './admission.ts';
import { DatabaseSync, type SQLInputValue } from 'node:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { OptionalDatabase } from './optional.ts';
import { IntegrationDatabase } from './integrations.ts';
import {planXShards,shardHandle} from 'dsh-hotstream-core/sources/shards';
import { BusinessDatabase } from './business.ts';
import { schema } from './migrations/001.ts';
import { schema as recoverySchema } from './migrations/002.ts';
import { schema as receiptJobsSchema } from './migrations/003.ts';
import {schema as coverageSchema} from './migrations/004.ts';
import {schema as manualSchema} from './migrations/005.ts';
import {schema as commandSchema} from './migrations/006.ts';
import {schema as reviewSchema} from './migrations/007.ts';
import {schema as runSchema} from './migrations/008.ts';
import {schema as projectionSchema} from './migrations/009.ts';
import {schema as authorizationSchema} from './migrations/010.ts';
import {schema as monitorActivitySchema} from './migrations/012.ts';
import {schema as confirmationSchema} from './migrations/011.ts';
import {schema as topicSubjectsSchema} from './migrations/013.ts';
import {schema as receiptLinksSchema} from './migrations/014.ts';
import { settingsSchema, sourceSchema, operationSchemas, type DurableJob, type EnqueueJob, type Receipt, type ReceiptAttempt, type RuntimeState, type Source, type StorageOperations, type StorageOperation, type Json, type BudgetPolicy } from 'dsh-hotstream-contracts/runtime';

type Row = Record<string, import('node:sqlite').SQLOutputValue>;
const encode=(value:unknown):string=>JSON.stringify(value);
const decode=(value:unknown):unknown=>JSON.parse(String(value));
export class HotstreamDatabase {
 constructor(readonly db:DatabaseSync) { this.migrate(); }
 dataRevision():number{return Number(this.get('SELECT data_revision FROM plugin_state WHERE id=1')?.data_revision??0);}
 private get(query:string,...args:SQLInputValue[]):Row|undefined{return this.db.prepare(query).get(...args);}
 private all(query:string,...args:SQLInputValue[]):Row[]{return this.db.prepare(query).all(...args);}
 private run(query:string,...args:SQLInputValue[]):number{return Number(this.db.prepare(query).run(...args).changes);}
 private command<T>(id:string|undefined,kind:string,request:unknown,now:number,run:()=>T):T{if(!id)return run();const state=this.state(),hash=createHash('sha256').update(encode(request)).digest('hex'),old=this.get('SELECT * FROM command_receipts WHERE command_id=?',id);if(old){const saved=decode(old.result) as {hash:string;value:T};if(old.kind!==kind||old.epoch!==state.epoch||saved.hash!==hash)throw new Error('Command identity or epoch conflict');return saved.value;}const value=run();this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',id,kind,state.epoch,now,encode({hash,value}));return value;}
 private txDepth=0;
 private transaction<T>(fn:()=>T):T{if(this.txDepth>0)return fn();this.txDepth++;try{return this.outerTransaction(fn);}finally{this.txDepth--;}}
 private outerTransaction<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const result=fn();this.db.exec('COMMIT');return result;}catch(error){try{this.db.exec('ROLLBACK');}catch{/* SQLite can roll back a full-disk transaction itself. */}throw error;}}
 private migrate():void{
  const migrations=[['001',schema],['002',recoverySchema],['003',receiptJobsSchema],['004',coverageSchema],['005',manualSchema],['006',commandSchema],['007',reviewSchema],['008',runSchema],['009',projectionSchema],['010',authorizationSchema],['011',confirmationSchema],['012',monitorActivitySchema],['013',topicSubjectsSchema],['014',receiptLinksSchema]] as const;
  const hasLedger=!!this.get("SELECT name FROM sqlite_master WHERE type='table' AND name='schema_migrations'");
  if(!hasLedger&&this.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'm0_%'").length)throw new Error('Unrecognized Hotstream database without a migration ledger; writing is blocked');
  const appliedRows=hasLedger?this.all('SELECT id,checksum FROM schema_migrations ORDER BY id'):[];
  if(appliedRows.some((row,index)=>row.id!==migrations[index]?.[0]))throw new Error('Unknown or discontinuous Hotstream database version; writing is blocked');
  // Check every existing checksum before applying any new migration.
  for(const [id,sql] of migrations){const applied=appliedRows.find(row=>row.id===id);if(applied&&applied.checksum!==createHash('sha256').update(sql).digest('hex'))throw new Error('Hotstream migration checksum mismatch; writing is blocked');}
  if(!hasLedger)this.db.exec('CREATE TABLE schema_migrations(id TEXT PRIMARY KEY,checksum TEXT NOT NULL,applied_at INTEGER NOT NULL) STRICT;');
  for(const [id,sql] of migrations)if(!this.get('SELECT id FROM schema_migrations WHERE id=?',id))this.transaction(()=>{this.db.exec(sql);this.run('INSERT INTO schema_migrations VALUES(?,?,?)',id,createHash('sha256').update(sql).digest('hex'),Date.now());});
  const health=this.get('PRAGMA quick_check');if(health?.quick_check!=='ok'||this.all('PRAGMA foreign_key_check').length>0)throw new Error('Hotstream database health check failed');
 }
 state():RuntimeState{
  const row=this.get('SELECT * FROM plugin_state WHERE id=1');if(row===undefined)throw new Error('Hotstream control state missing');
  const counts:Record<string,number>={};for(const name of ['articles','stories','reports','receipts','jobs'])counts[name]=Number(this.get(`SELECT count(*) n FROM ${name}`)?.n??0);
  return {deleting:row.deleting===1,dataRevision:Number(row.data_revision),moduleGenerations:decode(row.module_generations) as RuntimeState['moduleGenerations'],initialized:row.initialized===1,epoch:Number(row.epoch),revision:Number(row.revision),settings:row.settings_json===null?null:settingsSchema.parse(decode(row.settings_json)),schemaVersion:Number(this.get('SELECT max(CAST(id AS INTEGER)) n FROM schema_migrations')?.n??0),sourceCount:Number(this.get('SELECT count(*) n FROM sources WHERE deleted_at IS NULL')?.n??0),counts};
 }
 private assertEpoch(epoch:number):RuntimeState{const state=this.state();if(state.epoch!==epoch||!state.initialized||state.deleting)throw new Error('Stale Hotstream runtime epoch');return state;}
 private source(row:Row):Source{return sourceSchema.parse({...decode(row.document) as object,createdAt:row.created_at===null?null:Number(row.created_at),revision:Number(row.revision),enabled:row.enabled===1,lastOkAt:row.last_ok_at===null?null:Number(row.last_ok_at),nextDueAt:row.next_due_at===null?null:Number(row.next_due_at)});}
 private sources():Source[]{return this.all('SELECT * FROM sources WHERE deleted_at IS NULL ORDER BY name,id').map(r=>this.source(r));}
 private putSource(source:Source,now:number,expectedRevision:number):Source{
  const old=this.get('SELECT * FROM sources WHERE id=?',source.id);if((old===undefined?0:Number(old.revision))!==expectedRevision)throw new Error('Source revision conflict');
  if(old?.deleted_at!==null&&old!==undefined)throw new Error('Source was deleted; create a new id');
  const revision=expectedRevision+1;
  const document={...source,createdAt:old?old.created_at===null?null:Number(old.created_at):now,revision,health:'unknown',lastError:null};
  this.run(`INSERT INTO sources(id,name,kind,revision,enabled,deleted_at,next_due_at,last_ok_at,document,created_at) VALUES(?,?,?,?,?,NULL,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,kind=excluded.kind,revision=excluded.revision,enabled=excluded.enabled,next_due_at=excluded.next_due_at,document=excluded.document`,source.id,source.name,source.kind,revision,Number(source.enabled),source.enabled?now:source.nextDueAt,source.lastOkAt,encode(document),document.createdAt);
  return document;
 }
 private enqueue(input:EnqueueJob):DurableJob{
  this.assertEpoch(input.epoch);
  const existing=input.kind==='ingest'?this.get('SELECT * FROM jobs WHERE dedupe_key=? ORDER BY created_at LIMIT 1',input.key):this.get("SELECT * FROM jobs WHERE dedupe_key=? AND state IN('queued','running','retry_wait','blocked','succeeded') ORDER BY created_at DESC LIMIT 1",input.key);
  if(existing!==undefined){if(input.kind==='ingest'){const old=decode(existing.payload) as Record<string,Json>;if(Number(existing.input_revision)!==input.inputRevision||encode(old.items)!==encode(input.payload.items))throw new Error('External request identity conflict');}return this.job(existing);}
  const payload=(input.kind==='monitor'||input.kind==='leaderboard')?{...input.payload,moduleGeneration:this.state().moduleGenerations[input.kind]}:input.payload;
  const id=randomUUID();this.run(`INSERT INTO jobs(id,kind,subject,dedupe_key,epoch,input_revision,config_revision,payload,state,priority,due_at,attempts,max_attempts,created_at) VALUES(?,?,?,?,?,?,?,?,'queued',?,?,0,?,?)`,id,input.kind,input.subject,input.key,input.epoch,input.inputRevision,input.configRevision,encode(payload),input.priority,input.dueAt,input.maxAttempts,input.dueAt);
  return this.job(this.get('SELECT * FROM jobs WHERE id=?',id)!);
 }
 private job(row:Row):DurableJob{return {id:String(row.id),kind:String(row.kind),subject:String(row.subject),key:String(row.dedupe_key),epoch:Number(row.epoch),inputRevision:Number(row.input_revision),configRevision:Number(row.config_revision),payload:decode(row.payload) as Record<string,Json>,state:row.state as DurableJob['state'],priority:Number(row.priority),attempts:Number(row.attempts),maxAttempts:Number(row.max_attempts),dueAt:Number(row.due_at),leaseOwner:row.lease_owner===null?null:String(row.lease_owner),leaseUntil:row.lease_until===null?null:Number(row.lease_until),error:row.error===null?null:String(row.error)};}
 private receipt(row:Row):Receipt{return {id:String(row.id),key:String(row.logical_key),service:String(row.service),state:row.state as Receipt['state'],epoch:Number(row.epoch),requestHash:String(row.request_hash),request:decode(row.request) as Record<string,Json>,response:row.raw_response===null?null:decode(row.raw_response) as Json,usage:row.usage===null?null:decode(row.usage) as Record<string,Json>,auditRef:row.audit_ref===null?null:String(row.audit_ref),attempt:Number(row.attempt),automaticReleases:Number(row.automatic_releases),updatedAt:Number(row.updated_at)};}
 private budget(service:string,policy:BudgetPolicy):void{this.run('INSERT INTO budget_policies VALUES(?,?,?,?) ON CONFLICT(service) DO UPDATE SET per_minute=excluded.per_minute,per_hour=excluded.per_hour,per_day=excluded.per_day',service,policy.perMinute,policy.perHour,policy.per24Hours);}
 private isOwned(id:string,owner:string,epoch:number,now:number):Row|undefined{return this.get("SELECT * FROM jobs WHERE id=? AND epoch=? AND lease_owner=? AND state='running' AND lease_until>? AND epoch=(SELECT epoch FROM plugin_state WHERE id=1)",id,epoch,owner,now);}
 private initialize(input:StorageOperations['initialize']['input']):RuntimeState{return this.transaction(()=>{
  const current=this.state();if(current.deleting)throw new Error('Hotstream clear is still draining');const old=this.get('SELECT * FROM command_receipts WHERE command_id=?',input.commandId);
  if(old!==undefined){if(old.kind!=='initialize'||old.epoch!==current.epoch)throw new Error('Initialization command belongs to a different epoch');return this.state();}
  if(!current.initialized){
   this.run('UPDATE plugin_state SET initialized=1,settings_json=?,revision=revision+1 WHERE id=1',encode(input.settings));
   for(const source of input.sources)this.putSource(source,input.now,0);
   let topicPosition=0;for(const topic of input.topics??[])this.run('INSERT INTO topics VALUES(?,?,?,?)',topic.id,topic.kind,topicPosition++,encode(topic));
   this.budget('llm',input.settings.budgets.llm);for(const service of ['socialdata','dajiala','jina','embedding'])this.budget(service,input.settings.budgets.paidCollectorPerService);
   this.run('INSERT INTO industry_versions VALUES(?,?,?)','ai',1,encode({sourceCommit:'cc66cceb1dc7a0bc147e942e49ff94c9cee418c6',promptVersion:1}));
  }
  const state=this.state();this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',input.commandId,'initialize',state.epoch,input.now,encode(state));return state;
 });}
 private schedule(now:number):number{return this.transaction(()=>{
  const state=this.state();if(!state.initialized||state.settings?.autoCollectEnabled!==true)return 0;
  let count=0;
  // A collection already in flight when the route changed can fail afterwards. Retire only its
  // queued anonymous RSS retry, then let normal scheduling create a new immutable request below.
  for(const source of this.sources().filter(source=>source.kind==='rss'&&source.enabled&&source.lastError&&!String(source.config.feedUrl??'').startsWith('https://r.jina.ai/'))){
   const retired=this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE kind='collect' AND subject=? AND epoch=? AND state IN('queued','retry_wait','blocked') AND coalesce(json_extract(payload,'$.settings.network.publicProxyUrl'),'')<>?",source.id,state.epoch,state.settings.network.publicProxyUrl??'');
   if(retired)this.run('UPDATE sources SET next_due_at=? WHERE id=?',now,source.id);
   const failed=this.get("SELECT id FROM jobs WHERE kind='collect' AND subject=? AND epoch=? AND state='failed' AND coalesce(json_extract(payload,'$.settings.network.publicProxyUrl'),'')<>? ORDER BY created_at DESC LIMIT 1",source.id,state.epoch,state.settings.network.publicProxyUrl??'');
   if(failed&&!this.get("SELECT id FROM jobs WHERE kind='collect' AND subject=? AND epoch=? AND state IN('queued','running','retry_wait','blocked')",source.id,state.epoch)){
    const key=`public-route:${state.epoch}:${failed.id}:${createHash('sha256').update(state.settings.network.publicProxyUrl??'').digest('hex')}`;
    // Keep the terminal failure and its attempt history. One successor per old job / route,
    // including after that successor fails, prevents an unbounded recovery loop.
    if(!this.get('SELECT id FROM jobs WHERE dedupe_key=?',key)){
     this.enqueue({kind:'collect',subject:source.id,key,epoch:state.epoch,inputRevision:source.revision,configRevision:state.revision,payload:{collectAt:now,routeRecoveryOf:String(failed.id),source:JSON.parse(encode(source)) as Json,settings:JSON.parse(encode(state.settings)) as Json},priority:100,maxAttempts:5,dueAt:now});
     this.run('UPDATE sources SET next_due_at=? WHERE id=?',now+source.intervalMinutes*60000,source.id);count++;
    }
   }
  }
  const sources=this.sources().filter(s=>s.enabled);const legacy=sources.map(s=>({id:s.id,kind:s.kind,config:s.config,cursor:s.cursor,participation_mode:s.participationMode}));const shardSources=new Set<string>();
  for(const shard of planXShards(legacy)){for(const id of shard.sourceIds)shardSources.add(id);const members=sources.filter(s=>shard.sourceIds.includes(s.id));if(!members.some(s=>(s.nextDueAt??0)<=now))continue;const existing=this.get("SELECT id FROM jobs WHERE kind='collect-shard' AND subject=? AND epoch=? AND state IN('queued','running','retry_wait','blocked')",shard.key,state.epoch);if(!existing){this.enqueue({kind:'collect-shard',subject:shard.key,key:`collect-shard:${state.epoch}:${shard.key}:${Math.min(...members.map(s=>s.nextDueAt??0))}`,epoch:state.epoch,inputRevision:0,configRevision:state.revision,payload:{sourceIds:shard.sourceIds,collectAt:now,settings:JSON.parse(encode(state.settings)) as Json},priority:100,maxAttempts:5,dueAt:now});count++;}for(const member of members)this.run('UPDATE sources SET next_due_at=? WHERE id=?',now+member.intervalMinutes*60000,member.id);}
  for(const row of this.all('SELECT * FROM sources WHERE enabled=1 AND deleted_at IS NULL AND next_due_at<=? AND kind!=? ORDER BY next_due_at LIMIT 100',now,'external')){
   const source=this.source(row);if(shardSources.has(source.id))continue;const active=this.get("SELECT id FROM jobs WHERE kind='collect' AND subject=? AND epoch=? AND state IN('queued','running','retry_wait','blocked')",source.id,state.epoch);
   if(active===undefined){this.enqueue({kind:'collect',subject:source.id,key:`collect:${state.epoch}:${source.id}:${source.revision}:${Number(row.next_due_at)}`,epoch:state.epoch,inputRevision:source.revision,configRevision:state.revision,payload:{collectAt:now,source:JSON.parse(encode(source)) as Json,settings:JSON.parse(encode(state.settings)) as Json},priority:100,maxAttempts:5,dueAt:now});count++;}
   this.run('UPDATE sources SET next_due_at=? WHERE id=?',now+source.intervalMinutes*60000,source.id);
  }return count;
 });}
 private authorization():import('dsh-hotstream-contracts').ModelAuthorizationResult|null{const row=this.get('SELECT * FROM model_authorizations WHERE active=1 ORDER BY created_at DESC LIMIT 1');return row?{id:String(row.id),provider:String(row.provider),model:String(row.model),articleIds:decode(row.article_ids) as string[],maximum:Number(row.maximum),used:Number(row.used),active:row.active===1}:null;}
 private reserve(input:StorageOperations['reserve']['input']):StorageOperations['reserve']['output']{return this.transaction(()=>{
  this.assertEpoch(input.epoch);let row=this.get('SELECT * FROM receipts WHERE logical_key=?',input.key);
  if(row&&input.jobId&&this.get('SELECT id FROM jobs WHERE id=?',input.jobId))this.run('INSERT OR IGNORE INTO receipt_jobs VALUES(?,?)',row.id!,input.jobId);
  if(row!==undefined){if(row.epoch!==input.epoch||row.request_hash!==input.requestHash||row.service!==input.service)throw new Error('Receipt request identity conflict');const receipt=this.receipt(row);if(receipt.state==='received'||receipt.state==='completed')return {receipt,admitted:false,reusable:true,blockedReason:null,retryAt:null};if(['pending','unknown','reserved'].includes(receipt.state))return {receipt,admitted:false,reusable:false,blockedReason:receipt.state==='unknown'?'unknown-result':'active-request',retryAt:receipt.state==='unknown'&&receipt.automaticReleases===0?receipt.updatedAt+1800000:null};}
  const policy=this.get('SELECT * FROM budget_policies WHERE service=?',input.service);if(policy===undefined)throw new Error('Missing service budget');
  const activeAuthorization=this.authorization();if(activeAuthorization&&input.service!=='llm')return {receipt:row===undefined?null:this.receipt(row),admitted:false,reusable:false,blockedReason:'other-paid-services-not-authorized',retryAt:null};const authorization=input.service==='llm'?activeAuthorization:null;if(authorization){const job=input.jobId?this.get('SELECT payload,subject FROM jobs WHERE id=?',input.jobId):undefined;const payload=job?decode(job.payload) as Record<string,Json>:{};if(!job||!authorization.articleIds.includes(String(job.subject))&&!authorization.articleIds.includes(String(payload.articleId))||payload.authorizationId!==authorization.id||input.request.provider!==authorization.provider||input.request.model!==authorization.model)return {receipt:row===undefined?null:this.receipt(row),admitted:false,reusable:false,blockedReason:'explicit-model-test-scope',retryAt:null};if(authorization.used>=authorization.maximum)return {receipt:row===undefined?null:this.receipt(row),admitted:false,reusable:false,blockedReason:'explicit-model-test-limit',retryAt:null};}
  let retryAt:number|null=null;for(const [column,window] of [['per_minute',60000],['per_hour',3600000],['per_day',86400000]] as const){const limit=Number(policy[column]);if(limit===0)return {receipt:row===undefined?null:this.receipt(row),admitted:false,reusable:false,blockedReason:'service-paused',retryAt:null};const used=this.all('SELECT reserved_at FROM receipt_attempts WHERE service=? AND reserved_at>? AND (sent_at IS NOT NULL OR outcome IS NULL) ORDER BY reserved_at ASC',input.service,input.now-window);if(used.length>=limit)retryAt=Math.max(retryAt??0,Number(used[used.length-limit]!.reserved_at)+window+1);}
  if(retryAt!==null)return {receipt:row===undefined?null:this.receipt(row),admitted:false,reusable:false,blockedReason:'budget-exhausted',retryAt};
  const id=row===undefined?randomUUID():String(row.id);const attempt=row===undefined?1:Number(row.attempt)+1;
  if(row===undefined)this.run("INSERT INTO receipts(id,logical_key,service,state,epoch,request_hash,request,attempt,automatic_releases,updated_at) VALUES(?,?,?,'reserved',?,?,?,?,0,?)",id,input.key,input.service,input.epoch,input.requestHash,encode(input.request),attempt,input.now);
  else this.run("UPDATE receipts SET state='reserved',attempt=?,updated_at=?,error=NULL,raw_response=NULL,usage=NULL,audit_ref=NULL WHERE id=?",attempt,input.now,id);
  if(input.jobId&&this.get('SELECT id FROM jobs WHERE id=?',input.jobId))this.run('INSERT OR IGNORE INTO receipt_jobs VALUES(?,?)',id,input.jobId);
  this.run('INSERT INTO receipt_attempts(id,receipt_id,service,attempt,reserved_at,cost_basis,epoch,request_hash,request) VALUES(?,?,?,?,?,?,?,?,?)',randomUUID(),id,input.service,attempt,input.now,'unknown',input.epoch,input.requestHash,encode(input.request));
  if(authorization){this.run('UPDATE model_authorizations SET used=used+1 WHERE id=?',authorization.id);this.run('UPDATE receipt_attempts SET authorization_id=? WHERE receipt_id=? AND attempt=?',authorization.id,id,attempt);}
  row=this.get('SELECT * FROM receipts WHERE id=?',id)!;return {receipt:this.receipt(row),admitted:true,reusable:false,blockedReason:null,retryAt:null};
 });}
 private recover(now:number,startup=true):StorageOperations['recover']['output']{return this.transaction(()=>{
  const state=this.state();if(startup&&state.deleting){const command=this.get('SELECT clear_command_id FROM plugin_state WHERE id=1');if(!command?.clear_command_id)throw new Error('Deleting state has no clear identity');this.clear(String(command.clear_command_id),now);return {jobs:0,unknown:0,released:0};}let jobs=0;for(const row of this.all("SELECT * FROM jobs WHERE state='running' AND lease_until<=?",now)){
   const outcome=row.epoch===state.epoch?'retry_wait':'cancelled';this.run('UPDATE jobs SET state=?,lease_owner=NULL,lease_until=NULL,due_at=?,error=? WHERE id=?',outcome,now,'Interrupted lease',row.id!);this.run('UPDATE job_attempts SET finished_at=?,outcome=? WHERE job_id=? AND attempt=?',now,'interrupted',row.id!,row.attempts!);jobs++;
  }
  const unknown=startup?this.run("UPDATE receipts SET state='unknown',error='Interrupted dispatch' WHERE state='pending'"):0;
  if(startup)this.run("UPDATE receipt_attempts SET outcome='unknown',finished_at=? WHERE outcome IS NULL AND sent_at IS NOT NULL",now);
  if(startup)this.run("UPDATE receipts SET state='failed',error='Interrupted before dispatch' WHERE state='reserved'");
  const released=this.run("UPDATE receipts SET state='failed',automatic_releases=1,error='One automatic unknown release',updated_at=? WHERE state='unknown' AND automatic_releases=0 AND updated_at<=? AND epoch=? AND NOT EXISTS(SELECT 1 FROM receipt_confirmations c WHERE c.receipt_id=receipts.id AND c.attempt=receipts.attempt)",now,now-1800000,state.epoch);
  return {jobs,unknown,released};
 });}
 private confirmation(id:string,attempt:number):import('dsh-hotstream-contracts').UnknownConfirmation|null{const row=this.get('SELECT * FROM receipt_confirmations WHERE receipt_id=? AND attempt=?',id,attempt);return row?{outcome:row.outcome as 'billed'|'not-billed',reason:String(row.reason),cost:row.cost===null?null:Number(row.cost),currency:row.currency===null?null:String(row.currency),confirmedAt:Number(row.confirmed_at)}:null;}
 private attempt(row:Row):ReceiptAttempt{return {confirmation:this.confirmation(String(row.receipt_id),Number(row.attempt)),id:String(row.id),receiptId:String(row.receipt_id),service:String(row.service),attempt:Number(row.attempt),epoch:Number(row.epoch),requestHash:row.request_hash===null?null:String(row.request_hash),request:row.request===null?null:decode(row.request) as Record<string,Json>,response:row.raw_response===null?null:decode(row.raw_response) as Json,usage:row.usage===null?null:decode(row.usage) as Record<string,Json>,auditRef:row.audit_ref===null?null:String(row.audit_ref),auditSettled:row.audit_settled===1,outcome:row.outcome===null?null:String(row.outcome),reservedAt:Number(row.reserved_at),sentAt:row.sent_at===null?null:Number(row.sent_at),finishedAt:row.finished_at===null?null:Number(row.finished_at),error:row.error===null?null:String(row.error),cost:row.cost===null?null:Number(row.cost),currency:row.currency===null?null:String(row.currency),costBasis:row.cost_basis as ReceiptAttempt['costBasis']};}
 private beginClear(commandId:string,now:number):RuntimeState{
  const saved=this.get('SELECT * FROM command_receipts WHERE command_id=?',commandId);if(saved){if(saved.kind!=='clear')throw new Error('Command identity conflict');return decode(saved.result) as RuntimeState;}
  const control=this.get('SELECT * FROM plugin_state WHERE id=1')!;
  if(control.deleting===1){if(control.clear_command_id!==commandId)throw new Error('Another clear is in progress');return this.state();}
  this.run('UPDATE plugin_state SET epoch=epoch+1,deleting=1,initialized=0,clear_command_id=?,revision=revision+1 WHERE id=1',commandId);
  this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE state IN('queued','running','retry_wait','blocked')");
  this.run("UPDATE receipts SET state='failed',error='Clear before dispatch',updated_at=? WHERE state='reserved'",now);this.run("UPDATE receipt_attempts SET outcome='failed',error='Clear before dispatch',finished_at=? WHERE sent_at IS NULL AND outcome IS NULL",now);this.run("UPDATE receipts SET state='unknown',error='Clear fenced in-flight request',updated_at=? WHERE state='pending'",now);
  this.run("UPDATE receipt_attempts SET outcome='unknown',finished_at=?,error='Clear fenced in-flight request' WHERE outcome IS NULL AND sent_at IS NOT NULL",now);
  return this.state();
 }
 private clear(commandId:string,now:number):RuntimeState{return this.transaction(()=>{
  const old=this.get('SELECT * FROM command_receipts WHERE command_id=?',commandId);if(old!==undefined){if(old.kind!=='clear')throw new Error('Command identity conflict');return decode(old.result) as RuntimeState;}
  this.beginClear(commandId,now);this.run('UPDATE plugin_state SET deleting=0,clear_command_id=NULL,settings_json=NULL WHERE id=1');
  this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE state IN('queued','running','retry_wait','blocked')");
  this.run("UPDATE receipts SET state='unknown',error='Cleared while in flight' WHERE state='pending'");
  // Critical receipts/attempts/commands and their protected audit survive clear to fence late writes.
  for(const table of ['monitor_reviews','story_controls','grouping_controls','report_commands','report_schedule_checks','publication_search','user_marks','embeddings','story_heat_hourly','hot_rankings','report_revisions','reports','story_signals','story_digests','story_aliases','story_links','grouping_decisions','grouping_overrides','publications','fact_articles','facts','stories','editorial_overrides','analyses','translations','source_observations','article_discoveries','article_revisions','articles','fetch_runs','sources','topics','user_preferences','industry_versions','ordinary_run_logs','cached_responses','selectbench_results','selectbench_runs','lb_rankings','lb_runs','lb_scores','lb_aliases','lb_prices','lb_models','lb_fetch_runs','lb_snapshots','lb_calibrations','module_status','monitor_event_posts','monitor_events','monitor_posts','monitor_state'])this.run(`DELETE FROM ${table}`);
  const state=this.state();this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',commandId,'clear',state.epoch,now,encode(state));return state;
 });}
 /** Each operation name has one matching schema and handler; raw SQL never enters this boundary. */
 execute<K extends StorageOperation>(operation:K,raw:StorageOperations[K]['input']):StorageOperations[K]['output']{
  const input=operationSchemas[operation].parse(raw);
  const module=operation.startsWith('lb')?'leaderboard':operation.startsWith('monitor')&&operation!=='monitorCorrect'?'monitor':operation==='moduleStatus'?(input as StorageOperations['moduleStatus']['input']).module:null;
  const guarded=input as {generation?:number;testJobId?:string};
  if(module&&guarded.generation!==undefined){
   const state=this.state(),enabled=module==='leaderboard'?state.settings?.features.leaderboard:state.settings?.features.codexResetMonitor;
   const test=module==='monitor'&&guarded.testJobId?this.get("SELECT epoch,payload,lease_until FROM jobs WHERE id=? AND kind='monitor-test' AND state='running'",guarded.testJobId):undefined;
   const permittedTest=test?.epoch===state.epoch&&Number(test.lease_until)>Date.now()&&(decode(test.payload) as Record<string,Json>).moduleGeneration===guarded.generation;
   if((!enabled&&!permittedTest)||state.moduleGenerations[module]!==guarded.generation||state.deleting)throw new Error('Stale optional module generation');
  }
  const handlers:{[P in StorageOperation]:(value:StorageOperations[P]['input'])=>StorageOperations[P]['output']}={
   ...new IntegrationDatabase(this.db,{state:()=>this.state(),transaction:fn=>this.transaction(fn),enqueue:input=>this.enqueue(input)}).handlers(),
   ...new OptionalDatabase(this.db,{state:()=>this.state(),transaction:fn=>this.transaction(fn)}).handlers(),
   ...new BusinessDatabase(this.db,{state:()=>this.state(),transaction:fn=>this.transaction(fn),enqueue:input=>this.enqueue(input)}).handlers(),
   leaderboardRefresh:i=>this.transaction(()=>this.command(i.commandId,'leaderboard-refresh',{revision:i.revision},i.now,()=>{
    const state=this.state();if(state.revision!==i.revision)throw new Error('Settings revision conflict');if(!state.settings?.features.leaderboard)throw new Error('Enable and save the leaderboard before refreshing');
    if(this.get("SELECT id FROM jobs WHERE kind='leaderboard' AND epoch=? AND state IN('queued','running','retry_wait')",state.epoch))throw new Error('Leaderboard refresh is already active');
    return this.enqueue({kind:'leaderboard',subject:'leaderboard',key:`leaderboard-refresh:${state.epoch}:${i.commandId}`,epoch:state.epoch,inputRevision:0,configRevision:state.revision,payload:{settings:JSON.parse(encode(state.settings)),publicOnly:true,collectAt:i.now},priority:100,maxAttempts:1,dueAt:i.now});
   })),
   findReceipt:i=>{const row=this.get('SELECT * FROM receipts WHERE logical_key=?',i.key);return row?this.receipt(row):null;},freezeJob:i=>this.transaction(()=>{const row=this.isOwned(i.jobId,i.owner,i.epoch,i.now);if(!row)throw new Error('Request snapshot no longer owns its job lease');const payload=decode(row.payload) as Record<string,Json>;const plans=(payload.requests??{}) as Record<string,Json>;const existing=plans[i.stage];if(existing&&typeof existing==='object'&&!Array.isArray(existing))return existing;this.run('UPDATE jobs SET payload=? WHERE id=?',encode({...payload,requests:{...plans,[i.stage]:i.request}}),i.jobId);return i.request;}),
   callSummary:i=>this.all("SELECT r.id,r.epoch,r.service,r.state,r.attempt,r.updated_at,r.request,r.usage,a.cost,a.currency,a.cost_basis,a.audit_settled FROM receipts r LEFT JOIN receipt_attempts a ON a.receipt_id=r.id AND a.attempt=r.attempt WHERE r.epoch=(SELECT epoch FROM plugin_state WHERE id=1) OR r.state='unknown' ORDER BY r.updated_at DESC LIMIT ? OFFSET ?",i.limit,i.offset).map(row=>{const request=decode(row.request) as Record<string,Json>;return {id:String(row.id),epoch:Number(row.epoch),confirmation:this.confirmation(String(row.id),Number(row.attempt)),service:String(row.service),state:String(row.state),attempt:Number(row.attempt),updatedAt:Number(row.updated_at),provider:typeof request.provider==='string'?request.provider:null,model:typeof request.model==='string'?request.model:null,stage:typeof request.stage==='string'?request.stage:null,usage:row.usage===null?null:decode(row.usage) as Record<string,Json>,cost:row.cost===null?null:Number(row.cost),currency:row.currency===null?null:String(row.currency),costBasis:(row.cost_basis??'unknown') as 'actual'|'estimated'|'unknown',auditPending:row.service==='llm'&&row.audit_settled!==1};}),
   credentialChanged:i=>{const ids=this.sources().filter(source=>i.service==='socialdata'?source.kind==='x_search':i.service==='dajiala'?source.kind==='mp_account':i.service==='jina'?String(source.config.url??'').startsWith('https://r.jina.ai/'):false).map(source=>source.id);for(const id of ids){this.run('UPDATE sources SET next_due_at=?,fail_count=0 WHERE id=?',i.now,id);this.run("UPDATE jobs SET state='retry_wait',due_at=?,error=NULL WHERE subject=? AND state='blocked'",i.now,id);}this.run("UPDATE jobs SET state='retry_wait',due_at=?,error=NULL WHERE state='blocked' AND id IN(SELECT j.job_id FROM receipt_jobs j JOIN receipts r ON r.id=j.receipt_id WHERE r.service=?)",i.now,i.service);if(i.service==='socialdata')this.run("UPDATE jobs SET state='retry_wait',due_at=? WHERE kind='monitor' AND state='blocked'",i.now);return true;},
   linkReceipt:i=>{if(!this.get('SELECT id FROM jobs WHERE id=?',i.jobId))return false;return this.run('INSERT OR IGNORE INTO receipt_jobs VALUES(?,?)',i.id,i.jobId)===1;},
   dispatchPlan:i=>{const row=this.get('SELECT request FROM dispatch_plans WHERE logical_key=?',i.key);return row?decode(row.request) as Record<string,Json>:null;},
   freezeDispatch:i=>{this.assertEpoch(i.epoch);if(i.jobId&&i.owner&&!this.isOwned(i.jobId,i.owner,i.epoch,i.now))throw new Error('Dispatch plan lost its job lease');const row=this.get('SELECT * FROM dispatch_plans WHERE logical_key=?',i.key);if(row){if(row.epoch!==i.epoch)throw new Error('Dispatch plan epoch conflict');return decode(row.request) as Record<string,Json>;}this.run('INSERT INTO dispatch_plans VALUES(?,?,?,?,?)',i.key,i.epoch,createHash('sha256').update(encode(i.request)).digest('hex'),encode(i.request),i.now);return i.request;},
   callAttempts:i=>{const total=Number(this.get('SELECT count(*) n FROM receipt_attempts WHERE receipt_id=?',i.id)?.n??0);const columns=i.attempt===null?'id,receipt_id,service,attempt,epoch,request_hash,NULL request,NULL raw_response,usage,audit_ref,audit_settled,outcome,reserved_at,sent_at,finished_at,error,cost,currency,cost_basis':'*';const rows=i.attempt===null?this.all('SELECT '+columns+' FROM receipt_attempts WHERE receipt_id=? ORDER BY attempt LIMIT ? OFFSET ?',i.id,i.limit,i.offset):this.all('SELECT '+columns+' FROM receipt_attempts WHERE receipt_id=? AND attempt=?',i.id,i.attempt);return {id:i.id,offset:i.offset,total,attempts:rows.map(row=>this.attempt(row))};},
   receiptAttempts:i=>this.all('SELECT * FROM receipt_attempts WHERE receipt_id=? ORDER BY attempt LIMIT ? OFFSET ?',i.id,i.limit,i.offset).map(row=>this.attempt(row)),
   auditPending:i=>this.all("SELECT * FROM receipt_attempts WHERE service='llm' AND raw_response IS NOT NULL AND audit_ref IS NOT NULL AND audit_settled=0 ORDER BY reserved_at LIMIT ?",i.limit).map(row=>this.attempt(row)),
   auditRecoverable:i=>this.all("SELECT * FROM receipt_attempts WHERE service='llm' AND raw_response IS NULL AND audit_ref IS NOT NULL AND audit_settled=0 ORDER BY reserved_at LIMIT ? OFFSET ?",i.limit,i.offset).map(row=>this.attempt(row)),
   restoreResponse:i=>{const row=this.get('SELECT * FROM receipt_attempts WHERE receipt_id=? AND attempt=? AND epoch=?',i.id,i.attempt,i.epoch);if(!row||!row.audit_ref)throw new Error('Missing durable request audit');if(row.raw_response!==null){if(String(row.raw_response)!==encode(i.response))throw new Error('Recovered response identity conflict');return true;}this.run("UPDATE receipt_attempts SET raw_response=?,usage=?,outcome='received',finished_at=?,audit_settled=1 WHERE receipt_id=? AND attempt=? AND epoch=?",encode(i.response),encode(i.usage),i.now,i.id,i.attempt,i.epoch);this.run("UPDATE receipts SET state='received',raw_response=?,usage=?,updated_at=?,error=NULL WHERE id=? AND attempt=? AND epoch=?",encode(i.response),encode(i.usage),i.now,i.id,i.attempt,i.epoch);return true;},
   auditComplete:i=>this.run('UPDATE receipt_attempts SET audit_settled=1 WHERE receipt_id=? AND attempt=? AND epoch=? AND raw_response IS NOT NULL',i.id,i.attempt,i.epoch)===1,
   archiveResponse:i=>this.run('UPDATE receipt_attempts SET raw_response=?,usage=?,finished_at=?,outcome=? WHERE receipt_id=? AND attempt=? AND epoch=? AND raw_response IS NULL',encode(i.response),encode(i.usage),i.now,'late-response',i.id,i.attempt,i.epoch)===1,
   beginClear:i=>this.beginClear(i.commandId,i.now),
   confirmUnknown:i=>{const request={id:i.id,attempt:i.attempt,outcome:i.outcome,reason:i.reason,cost:i.cost,currency:i.currency};const saved=this.get('SELECT * FROM command_receipts WHERE command_id=?',i.commandId);if(saved){if(saved.kind!=='confirm-unknown'||encode(decode(saved.result))!==encode(request))throw new Error('Command identity conflict');return true;}const row=this.get('SELECT * FROM receipts WHERE id=?',i.id);if(!row||row.state!=='unknown'||Number(row.attempt)!==i.attempt)throw new Error('Unknown attempt revision conflict');if(this.confirmation(i.id,i.attempt))throw new Error('Attempt already confirmed');if((i.cost===null)!==(i.currency===null)||i.outcome==='not-billed'&&i.cost!==null&&i.cost!==0)throw new Error('Billing evidence is inconsistent');this.run('INSERT INTO receipt_confirmations VALUES(?,?,?,?,?,?,?,?)',i.commandId,i.id,i.attempt,i.outcome,i.reason,i.cost,i.currency,i.now);this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',i.commandId,'confirm-unknown',row.epoch!,i.now,encode(request));return true;},
   confirmRetry:i=>{const request={id:i.id,attempt:i.attempt};const old=this.get('SELECT * FROM command_receipts WHERE command_id=?',i.commandId);if(old){if(old.kind!=='confirm-retry'||encode(decode(old.result))!==encode(request))throw new Error('Command identity conflict');return true;}const row=this.get('SELECT * FROM receipts WHERE id=?',i.id);if(!row||row.state!=='unknown'||Number(row.attempt)!==i.attempt)throw new Error('Unknown attempt revision conflict');this.assertEpoch(Number(row.epoch));this.run("UPDATE receipts SET state='failed',error='Explicit retry authorized',updated_at=? WHERE id=?",i.now,i.id);this.run("UPDATE jobs SET due_at=?,state='retry_wait' WHERE state='blocked' AND epoch=? AND id IN(SELECT job_id FROM receipt_jobs WHERE receipt_id=?)",i.now,row.epoch!,i.id);this.run('INSERT INTO command_receipts VALUES(?,?,?,?,?)',i.commandId,'confirm-retry',row.epoch!,i.now,encode(request));return true;},
   retireModelAuthorization:i=>this.command(i.commandId,'retire-model-test',{id:i.id,reason:i.reason},i.now,()=>{const record=this.get('SELECT * FROM model_authorizations WHERE id=?',i.id);if(!record)throw new Error('Model test authorization missing');this.run('UPDATE model_authorizations SET active=0 WHERE id=?',i.id);return true;}),
   modelAuthorization:()=>this.authorization(),authorizeModels:i=>{const state=this.state();this.assertEpoch(state.epoch);const old=this.get('SELECT * FROM model_authorizations WHERE id=?',i.commandId);if(old){if(old.provider!==i.route.provider||old.model!==i.route.model||Number(old.maximum)!==i.maximum||encode(decode(old.article_ids))!==encode(i.articleIds))throw new Error('Authorization identity conflict');return this.authorization()!;}if(this.authorization())throw new Error('A cumulative model test authorization already exists');if(!state.settings||new Set(i.articleIds).size!==i.articleIds.length||i.articleIds.some(id=>!this.get("SELECT a.id FROM articles a JOIN sources s ON s.id=a.source_id WHERE a.id=? AND s.kind='rss'",id)))throw new Error('Choose existing RSS candidates');this.run('INSERT INTO model_authorizations VALUES(?,?,?,?,?, ?,0,?,1)',i.commandId,state.epoch,i.route.provider,i.route.model,encode(i.articleIds),i.maximum,i.now);const settings=settingsSchema.parse({...state.settings,autoCollectEnabled:false,processing:{enabled:true},concurrency:{collect:3,model:1,grouping:1},model:{...i.route,stageOverrides:{}},budgets:{llm:{perMinute:20,perHour:200,per24Hours:1000},paidCollectorPerService:{perMinute:0,perHour:0,per24Hours:0}}});this.run('UPDATE plugin_state SET settings_json=?,revision=revision+1 WHERE id=1',encode(settings));this.budget('llm',settings.budgets.llm);for(const service of ['socialdata','dajiala','jina','embedding'])this.budget(service,settings.budgets.paidCollectorPerService);for(const id of i.articleIds){const article=this.get('SELECT * FROM articles WHERE id=?',id)!;const source=this.source(this.get('SELECT * FROM sources WHERE id=?',article.source_id!)!);this.run('UPDATE articles SET active_run=?,active_config_revision=? WHERE id=?',i.commandId,state.revision+1,id);this.enqueue({kind:article.body_status==='pending'?'extract':'prefilter',subject:id,key:`model-test:${state.epoch}:${i.commandId}:${id}`,epoch:state.epoch,inputRevision:Number(article.revision),configRevision:state.revision+1,payload:{settings:JSON.parse(encode(settings)) as Json,authorizationId:i.commandId,articleId:id,rerun:i.commandId,sourceSnapshot:JSON.parse(encode(source)) as Json},priority:100,maxAttempts:3,dueAt:i.now});}return this.authorization()!;},
   state:()=>this.state(),initialize:i=>this.initialize(i),configure:i=>this.transaction(()=>this.command(i.commandId,'configure',{revision:i.revision,settings:i.settings},i.now,()=>{const state=this.state();if(!state.initialized||state.deleting||state.revision!==i.revision)throw new Error('Settings revision conflict');const beforeIndustry={...state.settings!.industry,revision:0},nextIndustry={...i.settings.industry,revision:0};i.settings={...i.settings,industry:{...i.settings.industry,revision:state.settings!.industry.revision+(encode(beforeIndustry)===encode(nextIndustry)?0:1)}};const generations={...state.moduleGenerations};for(const [module,feature]of [['leaderboard','leaderboard'],['monitor','codexResetMonitor']] as const)if(state.settings?.features[feature]!==i.settings.features[feature]){generations[module]++;this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE kind=? AND state IN('queued','running','retry_wait','blocked')",module);}this.run('UPDATE plugin_state SET settings_json=?,revision=revision+1,module_generations=? WHERE id=1',encode(i.settings),encode(generations));this.run('INSERT OR IGNORE INTO industry_versions VALUES(?,?,?)',i.settings.industry.name+'@'+String(state.revision+1),state.revision+1,encode(i.settings.industry));if(state.settings?.network.dnsMode!==i.settings.network.dnsMode){this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE kind IN('collect','collect-shard','extract') AND state IN('queued','retry_wait','blocked')");this.run("UPDATE sources SET next_due_at=? WHERE enabled=1 AND deleted_at IS NULL AND kind!='external'",i.now);}
   if(state.settings?.network.publicProxyUrl!==i.settings.network.publicProxyUrl){
    // A changed public route restarts failed anonymous RSS collection as a new frozen task.
    // Running jobs, extraction/model attempts and their saved responses are left intact.
    for(const source of this.sources().filter(source=>source.kind==='rss'&&source.enabled&&source.lastError&&!String(source.config.feedUrl??'').startsWith('https://r.jina.ai/'))){
     this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL WHERE kind='collect' AND subject=? AND state IN('queued','retry_wait','blocked')",source.id);
     this.run('UPDATE sources SET next_due_at=? WHERE id=?',i.now,source.id);
    }
   }
   this.budget('llm',i.settings.budgets.llm);for(const service of ['socialdata','dajiala','jina','embedding'])this.budget(service,i.settings.budgets.paidCollectorPerService);if(encode(state.settings?.budgets)!==encode(i.settings.budgets))this.run("UPDATE jobs SET state='retry_wait',due_at=?,error=NULL WHERE state='blocked' AND (error LIKE '%service-paused%' OR error LIKE '%budget-exhausted%')",i.now);return this.state();})), sources:()=>this.sources(),saveSource:i=>this.transaction(()=>this.command(i.commandId,'source-save',{source:i.source,expectedRevision:i.expectedRevision},i.now,()=>{if(!this.state().initialized)throw new Error('Initialize first');const previous=this.get('SELECT * FROM sources WHERE id=?',i.source.id);const oldSource=previous?this.source(previous):null;const fields=['name','kind','tier','ownerEntityId','signalGroupId','participationMode','firstParty','tags','config'] as const;const refreshDigest=!oldSource||fields.some(key=>encode(oldSource[key])!==encode(i.source[key]));const saved=this.putSource(i.source,i.now,i.expectedRevision);new BusinessDatabase(this.db,{state:()=>this.state(),transaction:fn=>this.transaction(fn),enqueue:input=>this.enqueue(input)}).handlers().sourceReproject({id:saved.id,now:i.now,refreshDigest});return saved;})), removeSource:i=>this.transaction(()=>this.command(i.commandId,'source-remove',{id:i.id,expectedRevision:i.expectedRevision},i.now,()=>{const changed=this.run('UPDATE sources SET enabled=0,deleted_at=?,revision=revision+1 WHERE id=? AND revision=? AND deleted_at IS NULL',i.now,i.id,i.expectedRevision);if(changed!==1)throw new Error('Source revision conflict');return true;})), schedule:i=>this.schedule(i.now),enqueue:i=>this.transaction(()=>this.enqueue(i)),
   claim:i=>this.transaction(()=>{const state=this.state();if(!state.initialized)return null;const row=this.get(`SELECT * FROM jobs WHERE kind IN(${i.kinds.map(()=>'?').join(',')}) AND epoch=? AND state IN('queued','retry_wait','blocked') AND due_at<=? AND ${jobAdmissionSql} ORDER BY priority DESC,due_at,id LIMIT 1`,...i.kinds,state.epoch,i.now);if(row===undefined)return null;if(row.attempts!>=row.max_attempts!&&row.state!=='blocked'){this.run("UPDATE jobs SET state='failed',error='Attempts exhausted' WHERE id=?",row.id!);return null;}this.run("UPDATE jobs SET state='running',lease_owner=?,lease_until=?,attempts=attempts+1 WHERE id=?",i.owner,i.now+i.leaseMs,row.id!);this.run('INSERT INTO job_attempts VALUES(?,?,?,?,NULL,NULL,NULL)',row.id!,Number(row.attempts)+1,i.owner,i.now);return this.job(this.get('SELECT * FROM jobs WHERE id=?',row.id!)!);}),
   renew:i=>this.run("UPDATE jobs SET lease_until=? WHERE id=? AND lease_owner=? AND epoch=? AND epoch=(SELECT epoch FROM plugin_state WHERE id=1) AND state='running' AND lease_until>?",i.now+i.leaseMs,i.id,i.owner,i.epoch,i.now)===1,
   finish:i=>this.transaction(()=>{const row=this.isOwned(i.id,i.owner,i.epoch,i.now);if(row===undefined)return false;this.run("UPDATE jobs SET state='succeeded',result=?,lease_owner=NULL,lease_until=NULL WHERE id=?",encode(i.result),i.id);this.run("UPDATE job_attempts SET finished_at=?,outcome='succeeded' WHERE job_id=? AND attempt=?",i.now,i.id,row.attempts!);return true;}),
   fail:i=>this.transaction(()=>{const row=this.isOwned(i.id,i.owner,i.epoch,i.now);if(row===undefined)return false;const state=i.blocked?'blocked':Number(row.attempts)>=Number(row.max_attempts)?'failed':'retry_wait';this.run('UPDATE jobs SET state=?,error=?,due_at=?,lease_owner=NULL,lease_until=NULL WHERE id=?',state,i.error,i.retryAt,i.id);this.run('UPDATE job_attempts SET finished_at=?,outcome=?,error=? WHERE job_id=? AND attempt=?',i.now,state,i.error,i.id,row.attempts!);return true;}),
   cancelJob:i=>{const row=this.isOwned(i.id,i.owner,i.epoch,i.now);if(!row)return false;this.run("UPDATE jobs SET state='cancelled',lease_owner=NULL,lease_until=NULL,error=? WHERE id=?",i.reason,i.id);this.run("UPDATE job_attempts SET outcome='cancelled',finished_at=?,error=? WHERE job_id=? AND attempt=?",i.now,i.reason,i.id,row.attempts!);return true;},
   jobs:i=>this.all('SELECT * FROM jobs ORDER BY created_at DESC,id LIMIT ? OFFSET ?',i.limit,i.offset).map(r=>this.job(r)),setBudget:i=>{this.budget(i.service,i.policy);return true;},reserve:i=>this.reserve(i),
   sent:i=>this.transaction(()=>{this.assertEpoch(i.epoch);const changed=this.run("UPDATE receipts SET state='pending',audit_ref=?,updated_at=? WHERE id=? AND epoch=? AND state='reserved' AND (? IS NULL OR attempt=?)",i.auditRef,i.now,i.id,i.epoch,i.attempt??null,i.attempt??null);if(changed)this.run('UPDATE receipt_attempts SET sent_at=?,audit_ref=? WHERE receipt_id=? AND attempt=(SELECT attempt FROM receipts WHERE id=?)',i.now,i.auditRef,i.id,i.id);return changed===1;}),
   receive:i=>this.transaction(()=>{this.assertEpoch(i.epoch);const changed=this.run("UPDATE receipts SET state='received',raw_response=?,usage=?,updated_at=? WHERE id=? AND epoch=? AND state='pending' AND (? IS NULL OR attempt=?)",encode(i.response),encode(i.usage),i.now,i.id,i.epoch,i.attempt??null,i.attempt??null);if(changed)this.run("UPDATE receipt_attempts SET outcome='received',raw_response=?,usage=?,finished_at=?,cost=?,currency=?,cost_basis=? WHERE receipt_id=? AND attempt=(SELECT attempt FROM receipts WHERE id=?)",encode(i.response),encode(i.usage),i.now,typeof i.usage.cost==='number'?i.usage.cost:null,typeof i.usage.currency==='string'?i.usage.currency:null,['actual','estimated'].includes(String(i.usage.costBasis))?String(i.usage.costBasis):'unknown',i.id,i.id);return changed===1;}),
   settle:i=>{this.assertEpoch(i.epoch);const changed=this.run("UPDATE receipts SET state=?,error=?,updated_at=? WHERE id=? AND epoch=? AND state IN('received','reserved','pending') AND (? IS NULL OR attempt=?)",i.state,i.error,i.now,i.id,i.epoch,i.attempt??null,i.attempt??null)===1;if(changed)this.run('UPDATE receipt_attempts SET outcome=?,error=?,finished_at=? WHERE receipt_id=? AND attempt=(SELECT attempt FROM receipts WHERE id=?)',i.state,i.error,i.now,i.id,i.id);return changed;},receipts:i=>this.all('SELECT * FROM receipts ORDER BY updated_at DESC,id LIMIT ? OFFSET ?',i.limit,i.offset).map(r=>this.receipt(r)),recover:i=>this.recover(i.now,i.startup),clear:i=>this.clear(i.commandId,i.now),
  };
  // The discriminated operation was parsed against its corresponding schema immediately above.
  const read=new Set(['moduleHealth','monitorTestRead','mediaReference','uiMonitor','uiArticle','uiFeed','uiGroups','uiReportIndex','uiReport','callAttempts','modelAuthorization','candidatesPage','storyDigestWork','correctionState','mutationHistory','callSummary','reportRevisions','preferenceGet','reportMissing','dailyEdition','periodEntries','materialsKnown','state','sources','jobs','receipts','findReceipt','dispatchPlan','receiptAttempts','auditRecoverable','auditPending','work','candidates','page','detail','story','stories','topics','reports','report','reportMaterial','chronicle','evaluations','optionalData','monitorCursor','monitorWork','lbInputs','vectorGet','nextWake']);
  if(read.has(operation))return handlers[operation](input as StorageOperations[K]['input']);
  return this.transaction(()=>{const before=Number(this.get('SELECT total_changes() n')?.n??0);const result=handlers[operation](input as StorageOperations[K]['input']);if(Number(this.get('SELECT total_changes() n')?.n??0)>before)this.run('UPDATE plugin_state SET data_revision=data_revision+1 WHERE id=1');return result;});
 }
}
