/** SQLite current-evidence queries and the locked upstream heat fold. */
import type {DatabaseSync,SQLInputValue,SQLOutputValue} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {foldHeat,heatIndex,heatTrend,HOT_RULE_VERSION,type HeatSignal} from 'dsh-hotstream-core/events/hot';
import {pickRepresentative} from 'dsh-hotstream-core/publication/representative';
import type {Publication,Source,Story,HeatEntry,Json} from 'dsh-hotstream-contracts/runtime';
type Row=Record<string,SQLOutputValue>;
const decode=(value:unknown)=>JSON.parse(String(value));
export class HeatRepository {
 constructor(private readonly db:DatabaseSync,private readonly read:(id:string,at:number)=>Publication|null,private readonly story:(id:string)=>Story|null){}
 private all(sql:string,...params:SQLInputValue[]):Row[]{return this.db.prepare(sql).all(...params);}
 private source(id:string):Source{const row=this.db.prepare('SELECT * FROM sources WHERE id=?').get(id)!;return {...decode(row.document),createdAt:row.created_at===null?null:Number(row.created_at),lastOkAt:row.last_ok_at===null?null:Number(row.last_ok_at)};}
 private signals(from:number,through:number,storyId?:string):Array<HeatSignal&{articleId:string;name:string;tier:string}>{
  const rows=this.all(`SELECT ss.story_id,ss.article_id,ss.observed_at,s.id source_id,s.document,s.created_at FROM story_signals ss JOIN articles a ON a.id=ss.article_id JOIN sources s ON s.id=a.source_id LEFT JOIN publications p ON p.article_id=a.id WHERE ss.observed_at>? AND ss.observed_at<=? AND json_extract(s.document,'$.participationMode')!='isolated' AND coalesce(p.visibility,'public')!='withdrawn' AND NOT EXISTS(SELECT 1 FROM grouping_overrides go WHERE go.article_id=a.id AND go.mode='standalone') AND (json_extract(s.document,'$.participationMode')!='editorial' OR EXISTS(SELECT 1 FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=a.id AND f.story_id=ss.story_id AND fa.role!='mention' AND NOT EXISTS(SELECT 1 FROM analyses an WHERE an.article_id=a.id AND an.input_revision=a.revision AND an.stage='writing' AND json_extract(an.result_json,'$.normalized.scope')='composite'))) ${storyId?'AND ss.story_id=?':''}`,from,through,...storyId?[storyId]:[]);
  return rows.map(row=>{const source=decode(row.document) as Source;return {storyId:String(row.story_id),articleId:String(row.article_id),sourceId:String(row.source_id),name:source.name,tier:source.tier,participantKey:source.signalGroupId?'group:'+source.signalGroupId:source.ownerEntityId?'owner:'+source.ownerEntityId:'source:'+source.id,sourceSince:row.created_at===null?null:Number(row.created_at),at:Number(row.observed_at),editorial:source.participationMode==='editorial'};});
 }
 private behind(at:number,grace:boolean):Set<string>{return new Set(this.all("SELECT id,last_ok_at,document FROM sources WHERE enabled=1 AND deleted_at IS NULL AND kind IN('rss','web_list','json_list','x_search')").filter(row=>{const source=decode(row.document) as Source;return row.last_ok_at===null||Number(row.last_ok_at)<at-(grace?Math.max(source.intervalMinutes*3,90)*60000:0);}).map(row=>String(row.id)));}
 ranking(at:number):HeatEntry[]{
  const signals=this.signals(at-54*3600000,at);const rows=foldHeat(signals,at,this.behind(at,true)).filter(row=>row.participants>=2&&row.editorial>=1);
  const stories=new Map(rows.map(row=>[row.storyId,this.story(row.storyId)]));rows.sort((a,b)=>b.heat-a.heat||(stories.get(b.storyId)?.latestAt??0)-(stories.get(a.storyId)?.latestAt??0));
  const entries:HeatEntry[]=[];for(const row of rows){const story=stories.get(row.storyId);if(!story||story.articles.length===0)continue;const byFact=new Map<string,Publication[]>();for(const item of story.articles){if(item.visibility!=='public'||!item.factId)continue;byFact.set(item.factId,[...(byFact.get(item.factId)??[]),item]);}const facts=[...byFact.values()].sort((a,b)=>new Set(b.map(p=>p.sourceId)).size-new Set(a.map(p=>p.sourceId)).size||Math.min(...a.map(p=>p.timelineAt))-Math.min(...b.map(p=>p.timelineAt))||(a[0]?.factId??'').localeCompare(b[0]?.factId??''));const members=facts[0];if(!members?.length)continue;const selected=members.filter(item=>item.selected);const rep=pickRepresentative((selected.length?selected:members).map(item=>{const source=this.source(item.sourceId);const fact=this.db.prepare('SELECT frame_json FROM facts WHERE id=?').get(item.factId!)!;const frame=decode(fact.frame_json) as Record<string,Json>;return {...item,source_tier:source.tier,publisher_role:typeof source.config.publisherRole==='string'?source.config.publisherRole:null,owner_entity_id:source.ownerEntityId,fact_subject:typeof frame.subject==='string'?frame.subject:null,body_mode:source.siteFulltext?'full' as const:'summary' as const,timeline_at:new Date(item.timelineAt)};}));
   const participants=new Map<string,typeof signals[number]>();for(const signal of signals.filter(signal=>signal.storyId===row.storyId&&signal.at>at-48*3600000)){const old=participants.get(signal.participantKey);if(!old||Number(signal.editorial)>Number(old.editorial)||signal.editorial===old.editorial&&signal.at>old.at)participants.set(signal.participantKey,signal);}
   const firstAt=story.firstReportAt??Math.min(...story.articles.map(p=>p.publishedAt??p.discoveredAt));
   entries.push({storyId:row.storyId,title:story.title,...heatTrend(row,at,firstAt),participants:row.participants,editorialParticipants:row.editorial,coverageComplete:row.uncomparable===0,signalCount:row.signal,reportCount:story.articles.length,sourceNames:[...new Set([...participants.values()].filter(p=>p.editorial).sort((a,b)=>b.at-a.at).map(p=>p.name))].slice(0,8),representativeItemId:rep.id,latestAt:story.latestAt??at,firstReportAt:firstAt});if(entries.length>=10)break;
  }
  this.db.prepare('INSERT INTO hot_rankings VALUES(?,?,?,?,?,1)').run(randomUUID(),at,HOT_RULE_VERSION,JSON.stringify(entries),JSON.stringify({behind:[...this.behind(at,true)]}));this.snapshots(at);return entries;
 }
 private saveHour(hour:number,grace:boolean,onlyRepair=false):void{
  const behind=this.behind(hour,grace);const rows=foldHeat(this.signals(hour-54*3600000,hour),hour,behind);
  for(const row of rows){if(onlyRepair&&row.behind)continue;this.db.prepare('INSERT INTO story_heat_hourly VALUES(?,?,?,?,?,?,?) ON CONFLICT(story_id,hour) DO UPDATE SET heat=excluded.heat,participants=excluded.participants,cohort=excluded.cohort,complete=excluded.complete,coverage_json=excluded.coverage_json').run(row.storyId,hour,heatIndex(row.heat),row.participants,row.editorial,Number(row.behind===0),JSON.stringify({behind:[...behind]}));}
 }
 snapshots(at:number):void{const hour=Math.floor(at/3600000)*3600000;this.saveHour(hour,true);for(const row of this.all('SELECT DISTINCT hour FROM story_heat_hourly WHERE complete=0 AND hour<? AND hour>? ORDER BY hour LIMIT 48',hour,hour-48*3600000))this.saveHour(Number(row.hour),false,true);}
 series(storyId:string,at:number,days=7):Array<{hour:number;heat:number;participants:number}>{const hours=this.all('SELECT hour FROM story_heat_hourly WHERE story_id=? AND complete=1 AND hour>? AND hour<=? ORDER BY hour',storyId,at-days*86400000,at).map(row=>Number(row.hour));if(!hours.length)return [];const from=hours[0]!-48*3600000;const signals=this.signals(from,at,storyId);const late=new Set(signals.filter(signal=>signal.sourceSince===null||signal.sourceSince>from).map(signal=>signal.participantKey));const times=new Map<string,number[]>();for(const signal of signals)if(!late.has(signal.participantKey))times.set(signal.participantKey,[...(times.get(signal.participantKey)??[]),signal.at]);const series=hours.map(hour=>{let heat=0,participants=0;for(const values of times.values()){const last=Math.max(-Infinity,...values.filter(value=>value<=hour&&value>hour-48*3600000));if(last!==-Infinity){heat+=0.5**((hour-last)/3600000/24);participants++;}}return {hour,heat:heatIndex(heat),participants};});return series.some(point=>point.heat>0)?series:[];}
}
