/** Retained report selection over SQLite relations, separate from model prose. */
import type {DatabaseSync,SQLInputValue,SQLOutputValue} from 'node:sqlite';
import {Time} from 'dsh-hotstream-core';
import {pickRepresentative,representativePriority,type RepresentativeIdentity} from 'dsh-hotstream-core/publication/representative';
import type {Publication,Source,Json} from 'dsh-hotstream-contracts/runtime';
import type {ReportEntry,EditionEntry,Candidate} from 'dsh-hotstream-core/reports/edition';
type Row=Record<string,SQLOutputValue>;type View=Publication&RepresentativeIdentity&{sourceKind:string;body_mode:'full'|'summary';timeline_at:Date;};
const decode=(value:unknown)=>JSON.parse(String(value));
const group=<T>(items:T[],key:(item:T)=>string)=>{const result=new Map<string,T[]>();for(const item of items){const id=key(item);result.set(id,[...(result.get(id)??[]),item]);}return result;};
export function citedIn(content:Record<string,Json>):Record<string,Json>[]{const sections=Array.isArray(content.sections)?content.sections:[];const entries=sections.flatMap(section=>section&&typeof section==='object'&&!Array.isArray(section)&&Array.isArray(section.items)?section.items:[]);const all=[...entries,...Array.isArray(content.flashes)?content.flashes:[]].filter((item):item is Record<string,Json>=>!!item&&typeof item==='object'&&!Array.isArray(item));return [...all,...all.flatMap(item=>Array.isArray(item.related)?item.related.filter((x):x is Record<string,Json>=>!!x&&typeof x==='object'&&!Array.isArray(x)):[])];}
export class ReportData {
 constructor(private readonly db:DatabaseSync,private readonly read:(id:string,at:number)=>Publication|null){}
 private all(sql:string,...params:SQLInputValue[]):Row[]{return this.db.prepare(sql).all(...params);}
 private view(id:string,at:number):View|null{const item=this.read(id,at);if(!item||item.visibility!=='public')return null;const sourceRow=this.db.prepare('SELECT document FROM sources WHERE id=?').get(item.sourceId)!;const source=decode(sourceRow.document) as Source;const fact=item.factId?this.db.prepare('SELECT frame_json,story_id FROM facts WHERE id=?').get(item.factId):undefined;const frame=fact?decode(fact.frame_json) as Record<string,Json>:{};const owns=item.factId&&this.db.prepare("SELECT 1 FROM fact_articles fa WHERE fact_id=? AND article_id=? AND role!='mention'").get(item.factId,id);return {...item,factId:owns?item.factId:null,storyId:owns&&fact?.story_id!==null?String(fact?.story_id):null,sourceKind:source.kind,source_tier:source.tier,publisher_role:typeof source.config.publisherRole==='string'?source.config.publisherRole:null,owner_entity_id:source.ownerEntityId,fact_subject:typeof frame.subject==='string'?frame.subject:null,body_mode:source.siteFulltext?'full':'summary',timeline_at:new Date(item.timelineAt)};}
 private entry(row:View):ReportEntry{const official=representativePriority(row)<3;return {itemId:row.id,factId:row.factId,storyPublicId:row.storyId,title:row.title,summary:row.summary,sourceName:row.sourceName,sourceUrl:row.url,sourceId:row.sourceId,firstParty:row.firstParty,role:official?row.sourceKind==='x_search'?'X·官方':'官方':row.sourceKind==='x_search'?'X·KOL':row.sourceKind==='mp_account'?'公众号':'媒体',score:row.score,publishedAt:new Date(row.timelineAt).toISOString()};}
 private signals(at:number):Array<{storyId:string;factId:string|null;articleId:string;key:string;at:number}>{return this.all("SELECT ss.story_id,ss.article_id,ss.observed_at,s.document,p.fact_id FROM story_signals ss JOIN articles a ON a.id=ss.article_id JOIN sources s ON s.id=a.source_id LEFT JOIN publications p ON p.article_id=a.id WHERE ss.observed_at<? AND json_extract(s.document,'$.participationMode')!='isolated' AND coalesce(p.visibility,'public')!='withdrawn' AND NOT EXISTS(SELECT 1 FROM grouping_overrides go WHERE go.article_id=a.id AND go.mode='standalone')",at).flatMap(row=>{const source=decode(row.document) as Source;if(source.participationMode==='editorial'&&!this.db.prepare("SELECT 1 FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=? AND f.story_id=? AND fa.role!='mention'").get(row.article_id!,row.story_id!))return [];return [{storyId:String(row.story_id),factId:row.fact_id===null?null:String(row.fact_id),articleId:String(row.article_id),key:source.signalGroupId?'group:'+source.signalGroupId:source.ownerEntityId?'owner:'+source.ownerEntityId:'source:'+source.id,at:Number(row.observed_at)}];});}
 daily(date:string,start:number,end:number,historical=false,asOf=Date.now()):{entries:EditionEntry[];stats:Record<string,number>}{
  const readAt=historical?asOf:end;
  const keys=new Set<string>();const cited=new Map<string,{key:string;title:string}>();const previousStories=new Map<string,{key:string;title:string}>();
  for(const issue of this.all("SELECT period_key,content FROM reports WHERE kind='daily' AND period_key<? AND period_key>=? ORDER BY period_key DESC",date,Time.addDays(date,-7)))for(const item of citedIn(decode(issue.content))){if(item.factId)keys.add(String(item.factId));if(typeof item.itemId==='string'){keys.add('a:'+item.itemId);if(!cited.has(item.itemId))cited.set(item.itemId,{key:String(issue.period_key),title:String(item.title??'')});}}
  for(const [id,prior]of cited){const item=this.view(id,readAt);if(item?.factId)keys.add(item.factId);if(item?.storyId){const old=previousStories.get(item.storyId);if(!old||old.key<prior.key)previousStories.set(item.storyId,prior);}}
  const selected=historical?this.all("SELECT p.article_id FROM publications p JOIN articles a ON a.id=p.article_id WHERE p.selected=1 AND p.visibility='public' AND a.published_at>=? AND a.published_at<?",start,end).flatMap(row=>{const item=this.view(String(row.article_id),readAt);return item?[item]:[];}):this.all("SELECT p.article_id FROM publications p JOIN articles a ON a.id=p.article_id WHERE p.selected=1 AND p.visibility='public' AND a.backfill=0 AND max(p.publication_time,coalesce(p.visible_after,p.publication_time))>=? AND max(p.publication_time,coalesce(p.visible_after,p.publication_time))<? AND p.publication_time>=?",start,end,start-86400000).flatMap(row=>{const item=this.view(String(row.article_id),end);return item?[item]:[];});
  const signals=this.signals(end);const missed:Array<{key:string;rows:View[];selected:boolean}>=[];
  const activeFacts=historical?[]:this.all("SELECT DISTINCT fa.fact_id FROM fact_articles fa JOIN publications p ON p.article_id=fa.article_id JOIN articles a ON a.id=p.article_id JOIN sources s ON s.id=a.source_id WHERE fa.role!='mention' AND p.visibility='public' AND p.eligible=1 AND a.backfill=0 AND p.publication_time>=? AND p.publication_time<? AND json_extract(s.document,'$.participationMode')='editorial'",start,end);
  for(const fact of activeFacts){const rows=this.all("SELECT p.article_id FROM fact_articles fa JOIN publications p ON p.article_id=fa.article_id JOIN articles a ON a.id=p.article_id JOIN sources s ON s.id=a.source_id WHERE fa.fact_id=? AND fa.role!='mention' AND p.visibility='public' AND p.eligible=1 AND a.backfill=0 AND p.publication_time<? AND json_extract(s.document,'$.participationMode')='editorial' AND json_extract(s.document,'$.tier')!='EXCLUDE_MP'",fact.fact_id!,end).flatMap(row=>{const item=this.view(String(row.article_id),end);return item?[item]:[];});if(rows.some(row=>row.selected)||!rows.some(row=>representativePriority(row)<3))continue;const ids=new Set(rows.map(row=>row.id));const evidence=signals.filter(signal=>ids.has(signal.articleId));if(new Set(evidence.map(signal=>signal.key)).size>=3&&Math.min(...evidence.map(signal=>signal.at))>=start-86400000)missed.push({key:String(fact.fact_id),rows,selected:false});}
  const raw=[...[...group(selected,row=>row.factId??'a:'+row.id)].map(([key,rows])=>({key,rows,selected:true})),...missed];const kept=raw.filter(fact=>!keys.has(fact.key)&&!fact.rows.some(row=>keys.has('a:'+row.id)));
  const facts=kept.map(fact=>{const sources=this.all("SELECT DISTINCT a.source_id FROM fact_articles fa JOIN publications p ON p.article_id=fa.article_id JOIN articles a ON a.id=p.article_id WHERE fa.fact_id=? AND fa.role!='mention' AND p.visibility='public' AND coalesce(p.visible_after,0)<=?",fact.rows[0]!.factId,readAt).map(row=>String(row.source_id));return {...fact,sources:[...new Set([...sources,...fact.rows.map(row=>row.sourceId)])],at:Math.min(...fact.rows.map(row=>row.timelineAt))};});
  const entries=[...group(facts,fact=>fact.rows[0]!.storyId?'s:'+fact.rows[0]!.storyId:'f:'+fact.key).values()].map((fs):EditionEntry=>{
   const ordered=[...fs].sort((a,b)=>b.sources.length-a.sources.length||a.at-b.at||a.key.localeCompare(b.key));const reps=ordered.map(fact=>pickRepresentative(fact.rows));const rep=reps[0]!;const sourceIds=new Set(fs.flatMap(fact=>fact.sources));const previous=rep.storyId?previousStories.get(rep.storyId)??null:null;const score=Math.max(rep.score??0,...fs.filter(fact=>fact.selected).flatMap(fact=>fact.rows.map(row=>row.score??0)));const participants=rep.storyId?new Set(signals.filter(signal=>signal.storyId===rep.storyId&&signal.at>=start).map(signal=>signal.key)).size:sourceIds.size;
   const related=reps.slice(1).map(row=>{const item=this.entry(row);return {itemId:item.itemId,factId:item.factId,storyPublicId:item.storyPublicId,title:item.title,sourceName:item.sourceName,sourceUrl:item.sourceUrl,sourceId:item.sourceId};});const mentions=new Set<string>();if(!rep.storyId)for(const fact of fs)for(const row of fact.rows)for(const mention of this.all('SELECT DISTINCT f.story_id FROM fact_articles fa JOIN facts f ON f.id=fa.fact_id WHERE fa.article_id=? AND f.story_id IS NOT NULL',row.id))mentions.add(String(mention.story_id));
   return {entry:{...this.entry(rep),sources:sourceIds.size,...related.length?{related}:{},...previous?{followUp:previous.key}:{},...fs.every(fact=>!fact.selected)?{fillIn:true}:{}},category:rep.category,tags:rep.tags,storyId:rep.storyId,sourceIds,mentions,authority:representativePriority(rep),previous,importance:score+5*Math.log2(1+participants)+(fs.some(fact=>fact.rows.some(row=>representativePriority(row)<3))?5:0)-(previous?6:0)};
  });entries.sort((a,b)=>b.importance-a.importance||a.entry.itemId.localeCompare(b.entry.itemId));return {entries,stats:{selectedReports:selected.length,facts:raw.length,repeatsSuppressed:raw.length-kept.length,fillIns:kept.filter(fact=>!fact.selected).length,events:entries.length}};
 }
 period(startDate:string,endDate:string,at:number,historical=false):{entries:Candidate[];issues:number}{
  const issues=this.all("SELECT period_key,content FROM reports WHERE kind='daily' AND period_key>=? AND period_key<=?"+(historical?'':" AND coalesce(json_extract(content,'$.generator.historical'),0)=0")+" ORDER BY period_key",startDate,endDate);const carried:Array<{id:string;key:string;sources:number;lead:boolean;highlight:boolean}>=[];
  for(const issue of issues){const content=decode(issue.content) as Record<string,Json>;const highlights=Array.isArray(content.highlights)?content.highlights:[];for(const section of Array.isArray(content.sections)?content.sections:[])if(section&&typeof section==='object'&&!Array.isArray(section)&&Array.isArray(section.items))for(const item of section.items)if(item&&typeof item==='object'&&!Array.isArray(item)&&typeof item.itemId==='string')carried.push({id:item.itemId,key:String(issue.period_key),sources:Number(item.sources)||1,lead:content.leadItemId===item.itemId,highlight:highlights.includes(item.itemId)});}
  const byId=new Map<string,View>();for(const item of carried){const view=this.view(item.id,at);if(view)byId.set(item.id,view);}const events=group(carried.filter(item=>byId.has(item.id)),item=>byId.get(item.id)!.storyId?'s:'+byId.get(item.id)!.storyId:'a:'+item.id);
  const ranked=[...events.values()].map(items=>{const main=byId.get([...items].sort((a,b)=>b.sources-a.sources||a.key.localeCompare(b.key)||representativePriority(byId.get(a.id)!)-representativePriority(byId.get(b.id)!))[0]!.id)!;const rank=Math.max(...items.map(item=>byId.get(item.id)!.score??0))+5*Math.log2(1+Math.max(...items.map(item=>item.sources)))+(items.some(item=>item.lead)?6:0)+(items.some(item=>item.highlight)?3:0)+4*(new Set(items.map(item=>item.key)).size-1);return {candidate:{...this.entry(main),category:main.category,factKey:main.factId??'a:'+main.id},rank};});ranked.sort((a,b)=>b.rank-a.rank||a.candidate.itemId.localeCompare(b.candidate.itemId));return {entries:ranked.map(row=>row.candidate),issues:issues.length};
 }
}
