/** Identical source/evidence fixture for the locked PostgreSQL reference and plugin SQLite. */
export const at=Date.parse('2026-10-04T00:00:00Z');const hour=3600000;
export const sources=[
 {id:'maker',name:'Official maker',tier:'T1',ownerEntityId:'openai',participationMode:'editorial'},
 {id:'media',name:'Independent media',tier:'T2',ownerEntityId:null,participationMode:'editorial'},
 {id:'signal',name:'Signal account',tier:'T2',ownerEntityId:null,participationMode:'hot_signal'},
 {id:'late',name:'New observer',tier:'T2',ownerEntityId:null,participationMode:'hot_signal',createdAt:at-2*hour},
 {id:'person',name:'Verified author',tier:'T2',ownerEntityId:'anthropic',participationMode:'editorial',publisherRole:'person'},
].map(({publisherRole,...source})=>({createdAt:source.createdAt??at-14*86400000,...source,kind:'rss',config:{feedUrl:'https://example.com/'+source.id,publisherRole:publisherRole??null},tags:[],signalGroupId:null,firstParty:source.tier==='T1',intervalMinutes:60,siteFulltext:false,enabled:true,revision:1,cursor:{initializedAt:new Date(at-14*86400000).toISOString()},health:'ok',lastOkAt:at,nextDueAt:at+hour,lastError:null}));
export const stories=[{id:'story-a',pg:1,title:'OpenAI 发布 Fixture',first:at-20*hour,latest:at-hour},{id:'story-b',pg:2,title:'Anthropic 更新 Fixture',first:at-12*hour,latest:at-hour}];
export const facts=[{id:'fact-a',pg:1,storyId:'story-a',title:'OpenAI 发布 Fixture',subject:'OpenAI',action:'发布',object:'Fixture',at:at-20*hour},{id:'fact-b',pg:2,storyId:'story-b',title:'Anthropic 更新 Fixture',subject:'Anthropic',action:'更新',object:'Fixture',at:at-12*hour},{id:'fact-follow',pg:3,storyId:'story-a',title:'OpenAI 更新 Fixture API',subject:'OpenAI',action:'更新',object:'API',at:at-hour}];
export const articles=[
 {id:'a-official',sourceId:'maker',factId:'fact-a',storyId:'story-a',title:'OpenAI 发布 Fixture',score:85,time:at-20*hour,selected:true},
 {id:'a-media',sourceId:'media',factId:'fact-a',storyId:'story-a',title:'独立报道 OpenAI Fixture',score:90,time:at-18*hour,selected:true},
 {id:'a-repeat',sourceId:'maker',factId:'fact-a',storyId:'story-a',title:'OpenAI Fixture 发布说明',score:80,time:at-17*hour,selected:false},
 {id:'a-follow',sourceId:'maker',factId:'fact-follow',storyId:'story-a',title:'OpenAI 更新 Fixture API',score:82,time:at-hour,selected:true},
 {id:'b-person',sourceId:'person',factId:'fact-b',storyId:'story-b',title:'Anthropic 作者介绍 Fixture',score:80,time:at-12*hour,selected:true},
 {id:'b-media',sourceId:'media',factId:'fact-b',storyId:'story-b',title:'Anthropic Fixture 更新报道',score:88,time:at-10*hour,selected:true},
 {id:'b-signal',sourceId:'signal',factId:'fact-b',storyId:'story-b',title:'Anthropic Fixture 讨论',score:null,time:at-2*hour,selected:false,signal:true},
 {id:'b-late',sourceId:'late',factId:'fact-b',storyId:'story-b',title:'Anthropic Fixture 新观察',score:null,time:at-hour,selected:false,signal:true},
 {id:'roundup',sourceId:'media',factId:null,storyId:null,title:'OpenAI 与 Anthropic 动态综述',score:84,time:at-3*hour,selected:true,composite:true},
].map(article=>({...article,summary:article.title+'，详见原始材料。',url:'https://example.com/news/'+article.id,category:'ai-models',tags:['模型发布'],body:'Fixture source evidence.',publishedAt:article.time,discoveredAt:article.time,visibility:'public',eligible:!article.signal,backfill:false}));
export async function seedPostgres(sql){
 await sql`TRUNCATE sources,stories,facts,reports CASCADE`;
 for(const source of sources)await sql`INSERT INTO sources (id,name,kind,config,tags,first_party,owner_entity_id,tier,participation_mode,interval_minutes,enabled,last_ok_at,created_at) VALUES(${source.id},${source.name},${source.kind},${sql.json(source.config)},${source.tags},${source.firstParty},${source.ownerEntityId},${source.tier},${source.participationMode},60,true,${new Date(source.lastOkAt)},${new Date(source.createdAt)})`;
 for(const [index,story]of stories.entries())await sql`INSERT INTO stories(id,public_id,title,first_report_at,latest_at) VALUES(${story.pg},${'00000000-0000-4000-8000-'+String(index+1).padStart(12,'0')}::uuid,${story.title},${new Date(story.first)},${new Date(story.latest)})`;
 for(const fact of facts)await sql`INSERT INTO facts(id,public_id,story_id,title,subject,action,object,occurred_at) VALUES(${fact.pg},${fact.id},${stories.find(story=>story.id===fact.storyId).pg},${fact.title},${fact.subject},${fact.action},${fact.object},${new Date(fact.at)})`;
 for(const article of articles){const source=sources.find(source=>source.id===article.sourceId);await sql`INSERT INTO articles(id,source_id,identity_key,url,title,published_at,discovered_at,timeline_at,body_text,body_status,processing_state,grouping_status,selection_adds_value) VALUES(${article.id},${source.id},${article.url},${article.url},${article.title},${new Date(article.time)},${new Date(article.time)},${new Date(article.time)},${article.body},'ok','analyzed','complete',true)`;const [analysis]=await sql`INSERT INTO analyses(article_id,input_revision,origin,relevance,category,tags,subjects,title_zh,summary_zh,score,selected,output) VALUES(${article.id},1,'model','pass',${article.category},${article.tags},${[]},${article.title},${article.summary},${article.score},${article.selected},${sql.json({scope:article.composite?'composite':'single'})}) RETURNING id`;const fact=article.factId?facts.find(fact=>fact.id===article.factId):null;const story=article.storyId?stories.find(story=>story.id===article.storyId):null;
  await sql`INSERT INTO publications(article_id,analysis_id,visibility,eligible,selected,selection_candidate,title,original_title,summary,category,tags,score,source_id,channel,first_party,url,published_at,discovered_at,timeline_at,selected_ready_at,visible_after,body_mode,story_id,fact_id,seat,sort_at) VALUES(${article.id},${analysis.id},'public',${article.eligible},${article.selected},${article.selected},${article.title},${article.title},${article.summary},${article.category},${article.tags},${article.score},${source.id},'news',${source.tier==='T1'},${article.url},${new Date(article.time)},${new Date(article.time)},${new Date(article.time)},${new Date(article.time)},${new Date(article.time)},'summary',${story?.pg??null},${fact?.pg??null},true,${new Date(article.time)})`;
  if(fact)await sql`INSERT INTO fact_articles(fact_id,article_id,role) VALUES(${fact.pg},${article.id},${article.signal?'mention':source.tier==='T1'?'primary':'report'})`;
  if(story)await sql`INSERT INTO story_signals(story_id,article_id,participant_key,source_id,kind,observed_at) VALUES(${story.pg},${article.id},${source.ownerEntityId?'owner:'+source.ownerEntityId:'source:'+source.id},${source.id},${article.signal?'signal':'editorial'},${new Date(article.time)})`;
 }
 for(const fact of facts.slice(0,2))await sql`INSERT INTO fact_articles(fact_id,article_id,role) VALUES(${fact.pg},'roundup','mention')`;
}
export function seedSqlite(db){
 const run=(query,...args)=>db.prepare(query).run(...args);
 for(const source of sources)run('INSERT INTO sources(id,name,kind,revision,enabled,next_due_at,last_ok_at,document,created_at) VALUES(?,?,?,?,?,?,?,?,?)',source.id,source.name,source.kind,1,1,source.nextDueAt,source.lastOkAt,JSON.stringify(source),source.createdAt);
 for(const story of stories)run('INSERT INTO stories VALUES(?,?,?,?,NULL,?,?,?,?)',story.id,story.id,story.title,'active',1,story.first,story.latest,JSON.stringify({digest:null,latest:null}));
 for(const fact of facts)run('INSERT INTO facts VALUES(?,?,?,?,?,?,?,?)',fact.id,fact.id,fact.storyId,fact.title,fact.at,1,0,JSON.stringify({title:fact.title,subject:fact.subject,action:fact.action,object:fact.object,occurredAt:new Date(fact.at).toISOString()}));
 for(const article of articles){const source=sources.find(source=>source.id===article.sourceId);const document={...article,identityKey:article.url,publishedAtClaim:article.time,timelineAt:article.time,backfillReason:null,revision:1,contentHash:article.id,excerpt:article.summary,bodyText:article.body,bodyHtml:null,bodyStatus:'ok',author:null,language:'zh',media:[],xPost:null,raw:null,processingState:'analyzed',groupingStatus:'complete'};run('INSERT INTO articles(id,source_id,identity_key,url,title,revision,content_hash,published_at,published_at_claim,discovered_at,timeline_at,backfill,body_status,processing_state,grouping_status,selection_adds_value,document) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',article.id,source.id,article.url,article.url,article.title,1,article.id,article.time,article.time,article.time,article.time,0,'ok','analyzed','complete',1,JSON.stringify(document));run('INSERT INTO analyses(id,article_id,input_revision,stage,slot,run_key,config_revision,prompt_hash,industry_version,provider,model,receipt_ids,result_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',article.id+'-analysis',article.id,1,'writing','writing','initial',2,'fixture','ai@1','mock','mock','[]',JSON.stringify({normalized:{relevance:'pass',selected:article.selected,titleZh:article.title,summaryZh:article.summary,score:article.score,category:article.category,tags:article.tags,scope:article.composite?'composite':'single'}}),article.time);
  const publication={...article,revision:1,eligible:article.eligible,selectionCandidate:article.selected,seat:true,originalTitle:article.title,reason:null,subjects:[],sourceName:source.name,firstParty:source.tier==='T1',timelineAt:article.time,body:null,translatedBody:null,translationComplete:null,groupingStatus:'complete',bookmarked:false,readAt:null};run('INSERT INTO publications(article_id,input_revision,visibility,eligible,selected,selection_candidate,seat,story_id,fact_id,title,summary,category,score,publication_time,visible_after,body_mode,document) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',article.id,1,'public',Number(article.eligible),Number(article.selected),Number(article.selected),1,article.storyId,article.factId,article.title,article.summary,article.category,article.score,article.time,article.time,'summary',JSON.stringify(publication));if(article.factId)run('INSERT INTO fact_articles VALUES(?,?,?,?,?,?)',article.factId,article.id,article.signal?'mention':source.tier==='T1'?'primary':'report',0,null,1);if(article.storyId)run('INSERT INTO story_signals VALUES(?,?,?,?,?,?)',article.storyId,article.id,source.ownerEntityId?'owner:'+source.ownerEntityId:'source:'+source.id,source.id,article.signal?'signal':'editorial',article.time);
 }
 for(const fact of facts.slice(0,2))run('INSERT INTO fact_articles VALUES(?,?,?,?,?,?)',fact.id,'roundup','mention',0,null,1);
}
