import {describe,it,expect} from 'vitest';import {readFile} from 'node:fs/promises';import {DatabaseSync} from 'node:sqlite';
import {HotstreamDatabase} from '../../packages/storage-sqlite/lib/types/database.js';import {at,seedSqlite} from './fixture.mjs';
const expected=JSON.parse(await readFile(new URL('./expected.json',import.meta.url),'utf8'));
function fixture(fn){const db=new DatabaseSync(':memory:');const store=new HotstreamDatabase(db);try{seedSqlite(db);fn(store,db);}finally{db.close();}}
describe('locked upstream PostgreSQL reading goldens',()=>{
 it('matches heat, coverage comparison, badges and representative selection',()=>fixture(store=>{const result=store.execute('heat',{epoch:0,now:at,compute:true}).map(entry=>({story:entry.storyId,title:entry.title,heat:entry.heat,trend:entry.trend,trendPct:entry.trendPct,badges:entry.badges,participants:entry.participants,editorial:entry.editorialParticipants,signal:entry.signalCount,representative:entry.representativeItemId,sourceNames:entry.sourceNames}));expect(result).toEqual(expected.heat);}));
 it('matches daily facts, developments, authoritative representatives and roundup relationships',()=>fixture(store=>{const result=store.execute('dailyEdition',{date:'2026-10-04',start:at-86400000,end:at});const entries=result.entries.map(entry=>({id:entry.entry.itemId,title:entry.entry.title,related:(entry.entry.related??[]).map(item=>item.itemId),sources:entry.entry.sources,authority:entry.authority,importance:entry.importance,mentions:[...entry.mentions],fillIn:entry.entry.fillIn??false,previous:entry.previous}));expect(entries).toEqual(expected.daily);expect(result.stats).toEqual(expected.dailyStats);}));
 it('rechecks withdrawals before ranking or choosing new report material',()=>fixture((store,db)=>{db.prepare("UPDATE publications SET visibility='withdrawn' WHERE article_id IN('a-official','a-media','a-repeat','a-follow')").run();expect(store.execute('heat',{epoch:0,now:at,compute:true}).some(entry=>entry.storyId==='story-a')).toBe(false);expect(store.execute('dailyEdition',{date:'2026-10-04',start:at-86400000,end:at}).entries.some(entry=>entry.entry.itemId.startsWith('a-'))).toBe(false);}));
});
