/** Tibo collection, context and recognition. Cursor commits only with the fetched posts. */
import type {Context} from '@deepseek-ai/cordis';
import {MONITOR_TEST_LIMITS} from 'dsh-hotstream-contracts';
import {setTimeout as delay} from 'node:timers/promises';
import {credentialKey} from '@deepseek-ai/dsh-credentials';
import {z} from 'zod';
import {recognitionPrompt,RecognitionSchema,RECOGNIZE_PROMPT_VERSION,type ContextInput,type OpenEventInput} from 'dsh-hotstream-core/monitor/recognize';
import {sha256} from 'dsh-hotstream-core/lib/ids';
import {jsonSchema,settingsSchema,type HotstreamStore,type DurableJob,type Json} from 'dsh-hotstream-contracts/runtime';
import {CallCoordinator,CallBlockedError,parseJson} from '../calls.ts';
import type {PublicNetwork} from '../network.ts';
import {tweetText,type SdTweet} from '../sources/socialdata.ts';
import {ProviderRejectedError} from '../sources/x.ts';
import {redactError} from '../sources/collect.ts';
import {paidHttp} from '../paid-http.ts';
const AUTHOR='thsottiaux';
export class MonitorModule {
 private boundKey:string|undefined;
 constructor(private readonly ctx:Context,private readonly store:HotstreamStore,private readonly calls:CallCoordinator,private readonly network:PublicNetwork,private readonly signal:AbortSignal){}
 async run(job:DurableJob):Promise<Record<string,Json>>{const test=job.kind==='monitor-test';let searchRequests=0,contextRequests=0,recognized=0;await this.enabled(job);const record=await this.ctx.credentials.readRecord(credentialKey('hotstream','socialdata'));if(record?.kind!=='api-key'||!record.key)throw new CallBlockedError('Monitor requires SocialData credential',null);const key=record.key;this.boundKey=key;const initial=await this.store.execute('monitorCursor',{});const liveThrough=typeof initial.scannedThrough==='number'?initial.scannedThrough:null;const lookback=job.payload.lookback===true;const started=Number(job.payload.collectAt??job.dueAt);const since=test?null:lookback?Math.floor((started-48*3600000)/1000):liveThrough===null?null:Math.floor((liveThrough-15*60000)/1000);const query=`from:${AUTHOR}${since===null?'':` since_time:${since}`}`;
  const backlog=z.array(z.object({query:z.string(),cursor:z.string()}).strict()).catch([]).parse(initial.backlog??[]);const all: SdTweet[]=[];const receipts:string[]=[];let cursor:string|null=null;let pages=0;
  let previousPaidAt=0;
  const beforePaid=async()=>{if(test){const limit=settingsSchema.parse(job.payload.settings).budgets.paidCollectorPerService.perMinute;if(!limit)throw new CallBlockedError('SocialData request budget is paused',null);const wait=previousPaidAt?Math.max(0,previousPaidAt+Math.ceil(60000/limit)+25-Date.now()):0;if(wait)await delay(wait,undefined,{signal:this.signal});previousPaidAt=Date.now();}await this.enabled(job);};
  const read=async(q:string,c:string|null)=>{await this.enabled(job);if(test&&searchRequests>=MONITOR_TEST_LIMITS.searchRequests)throw new Error('Monitor test search limit reached');searchRequests++;await beforePaid();const identity={query:q,cursor:c,window:String(Math.floor(started/600000))};const params=new URLSearchParams({query:q,type:'Latest',...c?{cursor:c}:{}});const result=await paidHttp(this.calls,this.store,this.network,job,'socialdata',identity,`https://api.socialdata.tools/twitter/search?${params}`,{headers:{authorization:`Bearer ${key}`,accept:'application/json'},signal:this.signal,timeoutMs:60000,maxBytes:12*1024*1024},raw=>{const tweets=z.object({tweets:z.array(z.unknown()).default([])}).parse(raw).tweets;return {objects:tweets.length,cost:tweets.length*0.0002,currency:'USD',costBasis:'estimated'};});receipts.push(result.receiptId);const data=z.object({tweets:z.array(z.object({id_str:z.string().regex(/^\d+$/),tweet_created_at:z.string(),user:z.object({screen_name:z.string(),name:z.string()}).passthrough()}).passthrough()).default([]),next_cursor:z.string().nullish()}).parse(JSON.parse(result.body));return {tweets:data.tweets as SdTweet[],cursor:data.next_cursor??null};};
  for(;pages<(test?MONITOR_TEST_LIMITS.searchRequests:5);pages++){try{const page=await read(query,cursor);all.push(...page.tweets);cursor=page.cursor;if(!cursor||!page.tweets.length)break;if(pages===4)backlog.push({query,cursor});}catch(error){if(cursor){backlog.push({query,cursor});break;}throw error;}}
  for(let oldPages=0;!test&&backlog.length&&oldPages<2;oldPages++){const item=backlog[0]!;try{const page=await read(item.query,item.cursor);all.push(...page.tweets);if(page.cursor&&page.tweets.length)item.cursor=page.cursor;else backlog.shift();}catch(error){if(error instanceof ProviderRejectedError&&[400,422].includes(error.status)){backlog.shift();continue;}break;}}
  const tweets=[...new Map(all.filter(t=>t.user.screen_name.toLowerCase()===AUTHOR&&!t.retweeted_status).map(t=>[t.id_str,t])).values()];const posts=tweets.filter(t=>Number.isFinite(Date.parse(t.tweet_created_at))).map(t=>({id:t.id_str,author:AUTHOR,publishedAt:Date.parse(t.tweet_created_at),text:tweetText(t),url:`https://x.com/${AUTHOR}/status/${t.id_str}`,context:t.quoted_status?[contextOf(t.quoted_status,'quote')]:[],raw:JSON.parse(JSON.stringify(t)) as Json}));
  const next=test?initial:{...initial,backlog:backlog.slice(-30),...lookback?{lookbackAt:started}:{scannedThrough:started}};
  await this.store.execute('monitorPosts',{epoch:job.epoch,posts:JSON.parse(JSON.stringify(posts)) as Record<string,Json>[],cursor:JSON.parse(JSON.stringify(next)) as Record<string,Json>,receiptIds:receipts,now:Date.now()});
  if(test)await this.store.execute('moduleStatus',{module:'monitor',source:'test',state:{status:'running',jobId:job.id,posts:posts.length},now:Date.now()});
  const pending=await this.store.execute('monitorWork',{limit:test?MONITOR_TEST_LIMITS.modelRequests:50,...test?{postIds:posts.map(post=>post.id)}:{}});
  for(const post of pending){await this.enabled(job);const data=await this.store.execute('optionalData',{module:'monitor',limit:100,offset:0});const open:OpenEventInput[]=data.records.filter(e=>!e.withdrawn).map(e=>({id:String(e.id),kind:e.kind as OpenEventInput['kind'],status:e.status as OpenEventInput['status'],firstPostAt:new Date(typeof (e.presentation as Record<string,Json>|undefined)?.reportedAt==='string'?String((e.presentation as Record<string,Json>).reportedAt):Number(e.createdAt??Date.now())).toISOString(),excerpt:String(e.title??''),schedule:typeof (e.schedule as Record<string,Json>|null)?.label==='string'?String((e.schedule as Record<string,Json>).label):null}));const tweet=post.raw as unknown as SdTweet;const context:ContextInput[]=z.array(z.object({id:z.string(),author:z.string(),relation:z.enum(['reply','quote']),text:z.string(),publishedAt:z.string().nullable()}).passthrough()).parse(post.context??[]);const contextReceipts:string[]=[];
   let parent=tweet.in_reply_to_status_id_str??null;const needsContext=!!parent;let lookedUp=0;for(let depth=0;parent&&depth<2&&(!test||contextRequests<MONITOR_TEST_LIMITS.contextRequests);depth++){await this.enabled(job);contextRequests++;lookedUp++;await beforePaid();const lookup=await paidHttp(this.calls,this.store,this.network,{...job,subject:'post:'+String(post.id)},'socialdata',{tweet:parent,purpose:'monitor-context'},`https://api.socialdata.tools/twitter/tweets/${encodeURIComponent(parent!)}`,{headers:{authorization:`Bearer ${key}`},signal:this.signal,timeoutMs:30000,maxBytes:4*1024*1024},()=>({objects:1,cost:0.0002,currency:'USD',costBasis:'estimated'}),[404]);contextReceipts.push(lookup.receiptId);if(lookup.status===404)break;const parentTweet=JSON.parse(lookup.body) as SdTweet;context.push(contextOf(parentTweet,'reply'));if(parentTweet.quoted_status&&depth===0)context.push(contextOf(parentTweet.quoted_status,'quote'));parent=parentTweet.in_reply_to_status_id_str??null;}
   if(test&&needsContext&&!lookedUp)continue;
   const prompt=recognitionPrompt({id:String(post.id),text:String(post.text),publishedAt:new Date(Number(post.publishedAt)).toISOString(),context,openEvents:open});const frozen=settingsSchema.parse(job.payload.settings);const recognitionJob={...job,key:`monitor:${job.epoch}:${post.id}:${sha256(String(post.text))}:${RECOGNIZE_PROMPT_VERSION}:c${job.configRevision}${test?':test:'+job.id:''}`,subject:String(post.id),inputRevision:1};const answer=await this.calls.model(recognitionJob,frozen,{stage:'monitor',...prompt,maxTokens:2500,temperature:0.1,json:true});const recognition=parseJson(answer.text,RecognitionSchema);await this.store.execute('monitorApply',{epoch:job.epoch,postId:String(post.id),recognition:JSON.parse(JSON.stringify({...recognition,context})) as Record<string,Json>,receiptId:answer.receiptId,now:Date.now()});recognized++;
   // Context receipts are linked to an explicit no-change business commit after the post is durable.
   for(const id of contextReceipts)await this.store.execute('settle',{id,epoch:job.epoch,state:'completed',error:null,now:Date.now()});
  }
  await this.store.execute('moduleStatus',{module:'monitor',source:test?'test':AUTHOR,state:{status:'ok',lastOkAt:Date.now(),posts:posts.length,backlog:backlog.length,lookback,test,...test?{jobId:job.id}:{}},now:Date.now()});
  return {posts:posts.length,recognized,searchRequests,contextRequests,test};
 }
 private async enabled(job:DurableJob):Promise<void>{this.signal.throwIfAborted();const state=await this.store.execute('state',{});const test=job.kind==='monitor-test';if(state.epoch!==job.epoch||state.deleting||!state.initialized||(test?state.settings?.features.codexResetMonitor:!state.settings?.features.codexResetMonitor)||typeof job.payload.moduleGeneration==='number'&&state.moduleGenerations.monitor!==job.payload.moduleGeneration)throw new CallBlockedError('Monitor disabled or replaced',null);if(this.boundKey){const record=await this.ctx.credentials.readRecord(credentialKey('hotstream','socialdata'));if(record?.kind!=='api-key'||record.key!==this.boundKey)throw new CallBlockedError('SocialData credential changed or removed',null);}}
}
function contextOf(tweet:SdTweet,relation:'reply'|'quote'):ContextInput&{url:string}{return {id:tweet.id_str,author:tweet.user.screen_name,text:tweetText(tweet),relation,publishedAt:Number.isFinite(Date.parse(tweet.tweet_created_at))?new Date(tweet.tweet_created_at).toISOString():null,url:`https://x.com/i/status/${tweet.id_str}`};}
