/** Deterministic stage orchestration over durable tasks; no Agent or provider SDK. */
import {buildStoryDigestInput,DigestSchema,DIGEST_SYSTEM,type DigestReport} from 'dsh-hotstream-core/events/digest';
import {publicCitationUrl} from 'dsh-hotstream-core/lib/url';
import {EmbeddingAdapter,cosine} from './embedding.ts';
import {shardHandle,selfThreadHandle,shardQuery} from 'dsh-hotstream-core/sources/shards';
import {createTranslationEngine} from 'dsh-hotstream-core/editorial/translate';
import {Editorial,Writing,Input,Relate,Extract,Sanitize,Material,promptText,promptVersion,promptFrom,Vocabulary} from 'dsh-hotstream-core';
import {settingsSchema,sourceSchema,jsonSchema,collectionItemSchema,type Article,type DurableJob,type HotstreamStore,type Json,type RuntimeSettings,type AnalysisStep,type ArticleWork,type EventCandidate} from 'dsh-hotstream-contracts/runtime';
import {CallCoordinator,parseJson,CallBlockedError} from './calls.ts';
import type {PublicNetwork} from './network.ts';
import type {SourceCollectors} from './sources/collect.ts';
import {z} from 'zod';
export class NewsPipeline {
 constructor(private readonly store:HotstreamStore,private readonly calls:CallCoordinator,private readonly network:PublicNetwork,private readonly collectors:SourceCollectors,private readonly embedding?:EmbeddingAdapter){}
 async run(job:DurableJob,owner:string):Promise<void>{
  const frozen=settingsSchema.parse(job.payload.settings);const industry=frozen.industry;
  const thresholdOf=(tier:string)=>tier==='EXCLUDE_MP'?null:industry.thresholds[tier as keyof typeof industry.thresholds]??Editorial.tierThreshold(tier);
  const systemOf=(name:string,fallback:string)=>industry.promptOverrides[name]?promptFrom(industry.promptOverrides,name,{},industry.name):fallback;const now=()=>({jobId:job.id,owner,epoch:job.epoch,now:Date.now()});
  if(job.kind==='digest'){
   const work=await this.store.execute('storyDigestWork',{id:job.subject});if(!work||work.version!==job.inputRevision){await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{stale:true}});return;}
   let captured=work,digest=typeof work.cachedDigest==='string'?work.cachedDigest:null;const receiptIds:string[]=[];
   if(!digest){const reports=(work.reports as Record<string,Json>[]).map(report=>({...report,at:new Date(Number(report.at))})) as unknown as DigestReport[];const answer=await this.calls.model(job,frozen,{stage:'digest',system:systemOf('story-digest',DIGEST_SYSTEM),user:buildStoryDigestInput({title:String(work.title),digest:typeof work.digest==='string'?work.digest:null},reports,{corrected:work.corrected===true,knownArticleIds:work.knownIds as string[]}),context:{work},maxTokens:1200,temperature:0.3,json:true});receiptIds.push(answer.receiptId);digest=parseJson(answer.text,DigestSchema).digest;if(answer.context?.work)captured=answer.context.work as Record<string,Json>;}
   const reports=captured.reports as Record<string,Json>[];await this.store.execute('storyDigest',{...now(),id:job.subject,revision:Number(captured.version),inputsHash:String(captured.inputsHash),digest,latest:String(reports.at(-1)?.title??''),receiptIds});return;
  }
  if(job.kind==='collect-shard'){
   const all=await this.store.execute('sources',{});const ids=Array.isArray(job.payload.sourceIds)?job.payload.sourceIds.filter((id):id is string=>typeof id==='string'):[];const members=all.filter(s=>ids.includes(s.id)&&s.enabled);if(!members.length){await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{skipped:true}});return;}
   const legacy=members.map(s=>({kind:s.kind,config:s.config,cursor:s.cursor}));const handles=legacy.map(shardHandle).filter((h):h is string=>h!==null);if(handles.length!==members.length)throw new Error('Shard source configuration changed');const xIdAt=(ms:number)=>BigInt(Math.max(0,ms-1288834974657))<<22n;const coverage=members.map(s=>{const own=BigInt(String(s.cursor.lastTweetId));const checked=Date.parse(String(s.cursor.lastOkAt??''));const time=Number.isFinite(checked)?xIdAt(checked-10*60000):own;return own>time?own:time;});const since=coverage.reduce((a,b)=>b<a?b:a);const backlog=[...new Map(members.flatMap(s=>Array.isArray(s.cursor.xBacklog)?s.cursor.xBacklog:[]).map(v=>[JSON.stringify(v),v])).values()];
   const virtual={...members[0]!,id:job.subject,ownerEntityId:null,config:{query:shardQuery(handles,legacy.map(selfThreadHandle).filter((h):h is string=>h!==null))},cursor:{initializedAt:new Date().toISOString(),lastTweetId:String(since),xBacklog:backlog}};const read=await this.collectors.collect(job,virtual);const batch=members.map((source,index)=>({sourceId:source.id,sourceRevision:source.revision,items:read.items.filter(item=>String(item.xPost?.handle??'').toLowerCase()===handles[index]!.toLowerCase()),cursor:{...source.cursor,...read.cursor,lastTweetId:BigInt(String(read.cursor.lastTweetId??source.cursor.lastTweetId))>BigInt(String(source.cursor.lastTweetId))?read.cursor.lastTweetId!:source.cursor.lastTweetId!},receiptIds:read.receiptIds}));await this.store.execute('collectionBatch',{...now(),members:batch});return;
  }
  if(job.kind==='collect'||job.kind==='ingest'){
   // Re-read the source's cursor immediately before dispatch, preserving its frozen config revision.
   const sources=await this.store.execute('sources',{});const source=sources.find(s=>s.id===job.subject);if(!source||!source.enabled||source.revision!==job.inputRevision){await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{skipped:true}});return;}
   const result=job.kind==='ingest'?{items:z.array(collectionItemSchema).parse(job.payload.items),cursor:{...source.cursor,initializedAt:new Date().toISOString()},receiptIds:[]}:await this.collectors.collect(job,source);await this.store.execute('collection',{...now(),sourceId:source.id,sourceRevision:source.revision,...typeof job.payload.observedAt==='number'?{observedAt:job.payload.observedAt}:{},...result});return;
  }
  const work=await this.store.execute('work',{id:job.subject});if(!work||work.article.revision!==job.inputRevision){await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{stale:true}});return;}
  const article={...work.article,source:job.payload.sourceSnapshot?sourceSchema.parse(job.payload.sourceSnapshot):work.article.source};const input=analyzeInput(article);const receipts:string[]=[];const merges:{survivor:string;other:string}[]=[];
  if(job.kind==='extract'){
   let bodyText:string|null=null,bodyHtml:string|null=null;let media:Record<string,Json>[]|undefined;
   if(article.source.kind==='mp_account'){const body=await this.collectors.mpBody(job,article.url);bodyText=body.text;bodyHtml=Sanitize.textToHtml(bodyText);receipts.push(body.receiptId);}else{try{const response=await this.network.fetch(article.url,{timeoutMs:25000});if(response.status===200){const body=Extract.readable(response.text(),response.url);if(body){bodyText=body.text;bodyHtml=body.html;media=body.images;}}}catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;}}
   await this.store.execute('extraction',{...now(),id:article.id,revision:article.revision,bodyText,bodyHtml,...media?{media}:{},status:bodyText?'ok':'unconfirmed',receiptIds:receipts});return;
  }
  if(job.kind==='translate'){
   const publication=await this.store.execute('detail',{id:article.id});if(!publication?.selected||!publication.body){await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{skipped:true}});return;}
   const engine=createTranslationEngine(async(_id,_revision,index,parts,system,attemptTag)=>{const answer=await this.calls.model(job,frozen,{stage:`translate:${index}:${attemptTag??'initial'}`,system:systemOf('translate-body',system),user:JSON.stringify({segments:parts}),maxTokens:Math.min(8000,Math.ceil(parts.join('').length*1.2)+400),temperature:0.2,json:true});receipts.push(answer.receiptId);const value=parseJson(answer.text,z.object({t:z.array(z.string())}));return value.t.length===parts.length?value.t:null;});
   const result=await engine.translateArticle({articleId:article.id,revision:article.revision,channel:article.xPost?'x':'news',language:article.language,body_html:article.bodyHtml,body_text:article.bodyText,x_post:article.xPost as {text?:string}|null,title:publication.title,selected:publication.selected,body_mode:article.source.siteFulltext?'full':'summary',visibility:publication.visibility});
   if(result.html&&result.text)await this.store.execute('translation',{...now(),id:article.id,revision:article.revision,title:publication.title,html:result.html,text:result.text,complete:result.complete===true,receiptIds:receipts});else{for(const id of receipts)await this.store.execute('settle',{id,epoch:job.epoch,state:'completed',error:null,now:Date.now()});await this.store.execute('finish',{id:job.id,owner,epoch:job.epoch,now:Date.now(),result:{status:result.status}});}return;
  }
  if(job.kind==='group'){
   const writing=work.steps.filter(s=>s.stage==='writing'&&(work.activeConfigRevision===0||s.configRevision===work.activeConfigRevision&&s.runKey===work.activeRun)).at(-1);let normalized=writing?.result.normalized as Record<string,Json>|undefined;
   const historical=Material.isHistorical({backfill:article.backfill,published_at:article.publishedAt===null?null:new Date(article.publishedAt),discovered_at:new Date(article.discoveredAt)});
   if(work.groupingOverride){await this.store.execute('grouping',{...now(),id:article.id,revision:article.revision,manualRevision:work.manualRevision,sourceRevision:article.source.revision,...writing?{analysisIdentity:{configRevision:writing.configRevision,runKey:writing.runKey,promptHash:writing.promptHash}}:{},decisions:[],selection:{addsValue:true,reason:'Persistent manual identity'},receiptIds:[]});return;}
   if(historical){await this.store.execute('grouping',{...now(),id:article.id,revision:article.revision,decisions:[],selection:{addsValue:true,reason:'Historical material'},receiptIds:[]});return;}
   let candidates=await this.store.execute('candidates',{id:article.id,now:Date.now()});let manualRevision=work.manualRevision,sourceRevision=article.source.revision,analysisIdentity=writing?{configRevision:writing.configRevision,runKey:writing.runKey,promptHash:writing.promptHash}:undefined;if(job.leaseOwner){const snapshot=await this.store.execute('freezeJob',{...now(),stage:'group-plan',request:JSON.parse(JSON.stringify({candidates,normalized:normalized??null,manualRevision,sourceRevision,analysisIdentity:analysisIdentity??null}))});candidates=snapshot.candidates as unknown as EventCandidate[];normalized=snapshot.normalized as Record<string,Json>|undefined;manualRevision=Number(snapshot.manualRevision);sourceRevision=Number(snapshot.sourceRevision);analysisIdentity=snapshot.analysisIdentity? snapshot.analysisIdentity as typeof analysisIdentity:undefined;}
   if(frozen.embedding.mode==='vector'&&!this.embedding)throw new CallBlockedError('Vector mode requires its configured adapter',null);
   if(frozen.embedding.mode==='vector'&&this.embedding){const queryVector=await this.embedding.vector(job,frozen,Relate.reportText(String(normalized?.titleZh??article.title),String(normalized?.summaryZh??article.excerpt??'')),article.id);if(queryVector)for(const candidate of candidates){const vector=await this.embedding.vector(job,frozen,Relate.reportText(candidate.report.title,candidate.report.summary),'fact:'+candidate.factId);if(vector)candidate.score=cosine(queryVector,vector);}candidates.sort((a,b)=>b.score-a.score);}
   let cands=candidates.map(c=>({...c,report:{...c.report,at:c.report.at===null?null:new Date(c.report.at)},selectedReport:c.selectedReport?{...c.selectedReport,at:c.selectedReport.at===null?null:new Date(c.selectedReport.at)}:null}));
   const query:Relate.ReportView={title:String(normalized?.titleZh??article.title),source:article.source.name,firstParty:article.source.tier==='T1',at:article.publishedAt===null?null:new Date(article.publishedAt),summary:String(normalized?.summaryZh??article.excerpt??''),sourceText:article.bodyText??article.excerpt,scope:normalized?.scope==='single'?'single':normalized?.scope==='composite'?'composite':'unknown'};
   const answer=await this.calls.model(job,frozen,{stage:article.source.participationMode==='hot_signal'?'group-signal':'group',system:article.source.participationMode==='hot_signal'?systemOf('group-signal',Relate.SIGNAL_SYSTEM):systemOf('group-batch',Relate.BATCH_SYSTEM),user:Relate.batchUser(query,cands),context:{candidates:JSON.parse(JSON.stringify(candidates)) as Json},maxTokens:4096,temperature:0.1,json:true});
   if(Array.isArray(answer.context?.candidates))cands=(answer.context.candidates as unknown as typeof candidates).map(c=>({...c,report:{...c.report,at:c.report.at===null?null:new Date(c.report.at)},selectedReport:c.selectedReport?{...c.selectedReport,at:c.selectedReport.at===null?null:new Date(c.selectedReport.at)}:null}));
   const result=article.source.participationMode==='hot_signal'?{...parseJson(answer.text,Relate.SignalSchema),selection:{addsValue:false,reason:'Signal-only source'}}:parseJson(answer.text,Relate.BatchSchema);
   if(!Relate.completeDecisions(result.decisions,cands.length))throw new Error('Identity result does not address every candidate');
   const decisions=result.decisions.map(d=>({factId:cands[Number(d.id.slice(1))-1]!.factId,relation:d.relation,confidence:d.confidence,note:'note' in d?String(d.note):''}));receipts.push(answer.receiptId);
   // A separate pair judgement reviews all proposed joins using source evidence, without the first verdict.
   for(const decision of decisions.filter(d=>d.relation==='SAME_OCCURRENCE'||d.relation==='SAME_STORY')){const candidate=cands.find(c=>c.factId===decision.factId)!;const review=await this.calls.model(job,frozen,{stage:'group-review:'+decision.factId,system:systemOf('group-pair',Relate.PAIR_SYSTEM),user:Relate.pairUser(query,candidate.report),maxTokens:2048,temperature:0.1,json:true});const pair=parseJson(review.text,Relate.PairSchema);receipts.push(review.receiptId);decision.relation=pair.confidence>=Relate.STORY_REVIEW_MIN_CONFIDENCE?pair.relation:'UNRELATED';decision.confidence=pair.confidence;}
   const tied=cands.filter(c=>decisions.some(d=>d.factId===c.factId&&Relate.firmlyTied(d.relation,d.confidence)));const stories=[...new Map(tied.map(c=>[c.storyId,c])).values()];stories.sort((a,b)=>(a.report.at?.getTime()??Infinity)-(b.report.at?.getTime()??Infinity)||a.storyId.localeCompare(b.storyId));const survivor=stories[0];
   if(survivor&&normalized?.scope!=='composite'&&article.source.participationMode==='editorial')for(const other of stories.slice(1)){const first=await this.calls.model(job,frozen,{stage:'story-merge:'+other.storyId,system:systemOf('group-pair',Relate.PAIR_SYSTEM),user:Relate.pairUser(survivor.report,other.report),maxTokens:400,temperature:0,json:true});const verdict=parseJson(first.text,Relate.PairSchema);receipts.push(first.receiptId);if(Relate.firmlyTied(verdict.relation,verdict.confidence)){const review=await this.calls.model(job,frozen,{stage:'story-merge-review:'+other.storyId,system:systemOf('group-pair',Relate.PAIR_SYSTEM),user:Relate.pairUser(other.report,survivor.report),maxTokens:400,temperature:0,json:true});receipts.push(review.receiptId);const second=parseJson(review.text,Relate.PairSchema);if(Relate.firmlyTied(second.relation,second.confidence,Relate.STORY_REVIEW_MIN_CONFIDENCE))merges.push({survivor:survivor.storyId,other:other.storyId});}}
   await this.store.execute('grouping',{...now(),id:article.id,revision:article.revision,candidateVersions:cands.map(c=>({factId:c.factId,stamp:c.stamp})),manualRevision,sourceRevision,...analysisIdentity?{analysisIdentity}:{},merges,decisions,selection:result.selection,receiptIds:receipts});return;
  }
  let system='',user='',result:Record<string,Json>={},temperature=0.2,maxTokens=2048,json=true;
  if(job.kind==='prefilter'){system=systemOf('prefilter',Writing.PREFILTER_SYSTEM);user=Writing.prefilterUser(input);temperature=0;maxTokens=512;}
  else if(job.kind==='score1'||job.kind==='score2'){if(thresholdOf(article.source.tier)===null)result={attentionScore:null,skipped:true};system=systemOf('selection-score',Editorial.SCORE_SYSTEM);user=Editorial.buildScoreInput(input);maxTokens=1024;}
  else if(job.kind==='structure'){system=industry.categories.length?promptFrom(industry.promptOverrides,'structure',{categoryCount:String(industry.categories.length),categoryGuide:industry.categories.map(c=>c.key+'：'+c.guide).join('\n'),categoryTags:industry.categories.map(c=>c.label).join('、'),topicTags:industry.topicTags.join('、'),entityTags:Object.values(industry.entities).map(e=>e.name).join('、'),entities:Object.entries(industry.entities).map(([id,e])=>id+'（'+e.aliases.join('/')+'）').join('，')},industry.name):systemOf('structure',Editorial.STRUCTURE_SYSTEM);user=Input.buildMaterial(input);maxTokens=1600;}
  else if(job.kind==='writing'){
   const steps=work.steps.filter(s=>s.configRevision===job.configRevision&&s.runKey===String(job.payload.rerun??'initial'));const sum=['score1','score2'].map(stage=>Number(steps.filter(s=>s.stage===stage).at(-1)?.result.attentionScore??NaN)).reduce((a,b)=>a+b,0);
   const threshold=thresholdOf(article.source.tier);const understand=sum>=2*(threshold??Infinity)||sum>=2*Editorial.UNDERSTAND_FLOOR;
   const translated=Writing.translateInputOf(input);const main=translated.mainText??translated.title;
   if(Writing.isShortTweetInput(translated)&&!Writing.needsShortTweetTranslation(main)){result={kind:'verbatim',titleZh:main,summaryZh:main,reasonZh:null};}
   else if(!Writing.isShortTweetInput(translated)&&translated.text.trim().length<20){result={kind:'none',titleZh:Writing.looksZh(translated.title)?translated.title:'',summaryZh:'',reasonZh:null};}
   else if(understand){system=systemOf('understand',Writing.UNDERSTAND_SYSTEM);user=Writing.understandUser(input);maxTokens=16384;}
   else{system=systemOf('summarize-article',system);user=Writing.isShortTweetInput(translated)?Writing.buildShortTweetPrompt(translated):article.xPost?Writing.buildLongTweetPrompt(translated):Writing.buildArticlePrompt(translated,new Date(Number(job.payload.collectAt??job.dueAt)));json=false;}
  }else throw new Error(`Unknown news stage ${job.kind}`);
  let answer:Awaited<ReturnType<CallCoordinator['model']>>|undefined;
  if(!Object.keys(result).length){const own=article.xPost?.media;const quoted=article.xPost?.quoted;const media=[...Array.isArray(own)?own:[],...quoted&&typeof quoted==='object'&&!Array.isArray(quoted)&&Array.isArray(quoted.media)?quoted.media:[],...article.media];const first=media.find(m=>m!==null&&typeof m==='object'&&!Array.isArray(m)&&m.kind==='image'&&typeof m.url==='string') as Record<string,Json>|undefined;
   answer=await this.calls.model(job,frozen,{stage:job.kind,system,user,maxTokens,temperature,json,...job.kind==='writing'&&maxTokens===16384&&typeof first?.url==='string'?{imageUrl:first.url}:{}});receipts.push(answer.receiptId);
   switch(job.kind){case 'prefilter':{const value=parseJson(answer.text,Editorial.PrefilterSchema);result={...value,label:value.label==='BLOCK'&&Writing.missingEvidence(input)?'UNKNOWN':value.label};break;}case 'score1':case 'score2':result=parseJson(answer.text,Editorial.ScoreSchema);break;case 'structure':{const data=parseJson(answer.text,industry.categories.length?Editorial.StructureSchema.extend({category:z.string().nullable()}):Editorial.StructureSchema);const normalized=Editorial.normalizeStructure(data as import('zod').infer<typeof Editorial.StructureSchema>,input);if(Object.keys(industry.entities).length)normalized.subjects=data.subjects.filter(id=>id in industry.entities);if(industry.topicTags.length)normalized.tags=[...new Set(data.tags)].filter(tag=>industry.topicTags.includes(tag)||industry.categories.some(category=>category.label===tag));result=JSON.parse(JSON.stringify({...normalized,category:industry.categories.length?industry.categories.find(category=>category.key===data.category)?.key??null:normalized.category})) as Record<string,Json>;break;}case 'writing':{const value=json?parseJson(answer.text,Editorial.UnderstandSchema):Writing.parseTranslateOutput(answer.text);const draft='titleZh' in value?value:{titleZh:'',summaryZh:''};const copy=Writing.finalizeCopy(Writing.translateInputOf(input),draft);result=JSON.parse(JSON.stringify({kind:json?'understand':'summarize',...copy,reasonZh:'editorialJudgment' in value?value.editorialJudgment:null})) as Record<string,Json>;break;}}
  }
  if(job.kind==='writing')result.normalized=normalize({...work,article},job,result,industry.thresholds) as Json;
  const route=frozen.model.stageOverrides[job.kind.replace(/\d+$/,'')]??frozen.model;
  const step:AnalysisStep={industryVersion:industry.name+'@'+industry.revision+':c'+job.configRevision,articleId:article.id,inputRevision:article.revision,configRevision:job.configRevision,stage:job.kind,slot:job.kind,runKey:String(job.payload.rerun??'initial'),provider:answer?.provider??route.provider,model:answer?.model??route.model,promptHash:answer?.promptHash??promptVersion('understand'),result,receiptIds:receipts,createdAt:Date.now()};
  await this.store.execute('analysis',{...now(),step});
 }
}
function normalize(work:ArticleWork,job:DurableJob,result:Record<string,Json>,thresholds:RuntimeSettings['industry']['thresholds']):Record<string,Json>{const tier=work.article.source.tier;const threshold=tier==='EXCLUDE_MP'?null:thresholds[tier];const steps=work.steps.filter(s=>s.configRevision===job.configRevision&&s.runKey===String(job.payload.rerun??'initial'));const last=(stage:string)=>steps.filter(s=>s.stage===stage).at(-1);const pref=last('prefilter')!;const structure=last('structure')!;const scores=['score1','score2'].map(name=>last(name));const run:Editorial.AnalysisRun={prefilter:{label:pref.result.label as 'PASS'|'BLOCK'|'UNKNOWN',reason:String(pref.result.reason??''),model:pref.model,receiptId:0,reused:true},scores:threshold===null?null:{model:scores[0]!.model,threshold:threshold!,values:scores.map(s=>Number(s!.result.attentionScore)),receiptIds:[],reused:true},writing:{kind:result.kind as 'verbatim'|'understand'|'summarize'|'none',model:job.kind,titleZh:String(result.titleZh??''),summaryZh:String(result.summaryZh??''),reasonZh:typeof result.reasonZh==='string'?result.reasonZh:null,receiptIds:[],reused:false},structure:{...structure.result,model:structure.model,receiptId:0,reused:true} as Editorial.AnalysisRun['structure']};return JSON.parse(JSON.stringify({...Editorial.normalizeAnalysis(run),selected:run.prefilter.label!=='BLOCK'&&run.scores!==null&&run.scores.values.length===2&&run.scores.values.reduce((a,b)=>a+b,0)>=2*(threshold??Infinity)})) as Record<string,Json>;}
export function analyzeInput(article:Article):Input.AnalyzeInputArticle{return {id:article.id,revision:article.revision,title:article.title,url:publicCitationUrl(article.url),author:article.author,publishedAt:article.publishedAt===null?null:new Date(article.publishedAt),discoveredAt:new Date(article.discoveredAt),bodyText:article.bodyText,excerpt:article.excerpt,bodyStatus:article.bodyStatus,xPost:article.xPost,media:article.media as Record<string,Json>[],source:{name:article.source.name,kind:article.source.kind,tier:article.source.tier,firstParty:article.source.tier==='T1',tags:article.source.tags,ownerEntityId:article.source.ownerEntityId,fetchesBody:article.source.config.fetchPublicContent===true||article.source.kind==='web_list'}};}
