/** The original issue rules choose membership; a model only writes grounded period prose. */
import {randomUUID} from 'node:crypto';import {Edition,Reports,Time,Taxonomy} from 'dsh-hotstream-core';
import type {DurableJob,HotstreamStore,Json,Report,RuntimeSettings} from 'dsh-hotstream-contracts/runtime';
import {CallCoordinator,parseJson,InvalidModelOutput} from './calls.ts';
import {z} from 'zod';
const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Record<string,Json>;
const windowOf=(kind:'daily'|'weekly'|'monthly',key:string)=>{if(kind==='daily'){const end=Time.beijingMidnight(key).getTime()+8*3600000;return {start:end-86400000,end,range:null};}const range=kind==='weekly'?Time.isoWeekRange(key):Time.monthRange(key);if(!range)throw new Error('Invalid report period');return {start:Time.beijingMidnight(range.start).getTime()-16*3600000,end:Time.beijingMidnight(range.end).getTime()+8*3600000,range};};
export class ReportComposer {
 constructor(private readonly store:HotstreamStore,private readonly calls:CallCoordinator){}
 async compose(job:DurableJob,settings:RuntimeSettings):Promise<void>{
  const historical=job.payload.historical===true,asOf=Date.now();const kind=job.payload.kind as 'daily'|'weekly'|'monthly',key=String(job.payload.key);const {start,end,range}=windowOf(kind,key);const receipts:string[]=[];let content:Record<string,Json>;
  if(kind==='daily'){
   let material=await this.store.execute('dailyEdition',{date:key,start,end,historical,asOf});if(job.leaseOwner)material=await this.store.execute('freezeJob',{jobId:job.id,owner:job.leaseOwner,epoch:job.epoch,now:Date.now(),stage:'report-material',request:json(material)}) as unknown as typeof material;const entries=material.entries.map(raw=>({...raw,sourceIds:new Set(raw.sourceIds as string[]),mentions:new Set(raw.mentions as string[])}) as unknown as Edition.EditionEntry);const issue=Edition.arrangeDaily(entries);if(!issue.main.length)throw new Error('No evidence for this daily issue');const [lead,...rest]=issue.main;const main=issue.main;
   content=json({date:key,lead:{title:lead!.entry.title,leadParagraph:lead!.entry.summary},leadItemId:lead!.entry.itemId,highlights:rest.slice(0,3).map(entry=>entry.entry.itemId),sections:Edition.SECTION_ORDER.map(label=>({label,items:main.filter(entry=>Edition.sectionOf(entry.category)===label).map(entry=>entry.entry)})).filter(section=>section.items.length),flashes:issue.flashes.map(entry=>entry.entry),metrics:{totalEvents:main.length,sourcesCount:new Set(main.flatMap(entry=>[entry.entry.sourceId,...(entry.entry.related??[]).map(item=>item.sourceId)])).size,firstPartyEvents:main.filter(entry=>entry.entry.firstParty).length,...Taxonomy.RELEASE?{modelsReleased:main.filter(entry=>entry.category===Taxonomy.RELEASE?.category&&entry.tags.includes(Taxonomy.RELEASE?.tag??'')&&!entry.previous&&entry.authority<3).length}:{}},windowStart:new Date(start).toISOString(),windowEnd:new Date(end).toISOString(),...historical?{coverage:{complete:false,historical:true,sourceSnapshot:true}}:{},generator:{version:'aihot-report-rules-v1',historical,compiledAt:new Date(asOf).toISOString(),...material.stats,...issue.stats}});
  }else{
   let material=await this.store.execute('periodEntries',{startDate:range!.start,endDate:range!.end,now:asOf,historical});if(job.leaseOwner)material=await this.store.execute('freezeJob',{jobId:job.id,owner:job.leaseOwner,epoch:job.epoch,now:Date.now(),stage:'report-material',request:json(material)}) as unknown as typeof material;const selected=(material.entries as unknown as Edition.Candidate[]).slice(0,kind==='weekly'?20:30);if(!selected.length)throw new Error('No daily entries for this period');const sections=Edition.SECTION_ORDER.map(label=>({label,items:selected.filter(entry=>Edition.sectionOf(entry.category)===label)})).filter(section=>section.items.length);const corpus=[range!.start+' '+range!.end,...selected.map(entry=>entry.title+' '+entry.summary)].join('\n');let written:{overview:string;sections:Record<string,string>}={overview:'',sections:{}};
   try{const answer=await this.calls.model(job,settings,{stage:'report-period',...Reports.periodPrompt(kind,range!.start,range!.end,sections),...settings.industry.promptOverrides['report-period']?{system:settings.industry.promptOverrides['report-period']!}:{},maxTokens:2500,temperature:0.3,json:true});receipts.push(answer.receiptId);written=parseJson(answer.text,Reports.PeriodSchema);}catch(error){const state=await this.store.execute('state',{});if(state.epoch!==job.epoch||state.deleting||!(error instanceof z.ZodError||error instanceof InvalidModelOutput||error instanceof SyntaxError))throw error;}
   const usable=(text:string,max:number)=>{const fitted=Reports.fitted(text,max);return fitted&&Reports.grounded(fitted,corpus)?fitted:null;};const expected=kind==='weekly'?7:Number(range!.end.slice(-2));const lead=selected[0]!;
   content=json({kind,key,lead:{title:lead.title,leadParagraph:lead.summary},leadItemId:lead.itemId,overview:usable(written.overview,kind==='weekly'?240:340),sections:sections.map(section=>({...section,intro:section.items.length>=3?usable(written.sections[section.label]??'',90):null})),storyOrder:selected.map(entry=>({itemId:entry.itemId,factId:entry.factId,storyPublicId:entry.storyPublicId})),highlights:selected.slice(1,4).map(entry=>entry.itemId),coverage:{dailyIssues:material.issues,expectedDailyIssues:expected,complete:!historical&&material.issues>=expected,historical,sourceSnapshot:historical},windowStart:new Date(start).toISOString(),windowEnd:new Date(end).toISOString(),generator:{version:'aihot-report-rules-v1',historical,compiledAt:new Date(asOf).toISOString()}});
  }
  const report:Report={id:randomUUID(),kind,key,timeZone:'Asia/Shanghai',windowStart:start,windowEnd:end,createdAt:Date.now(),revision:1,content,coverage:historical?'incomplete':'evidence-based'};await this.store.execute('saveReport',{...job.leaseOwner?{jobId:job.id,owner:job.leaseOwner}:{},epoch:job.epoch,report,receiptIds:receipts});
 }
 async due(epoch:number,revision:number,settings:RuntimeSettings,now:number):Promise<void>{
  let left=8;for(const kind of ['daily','weekly','monthly'] as const){const latest=kind==='daily'?Reports.dueDaily(new Date(now)):kind==='weekly'?Reports.dueWeekly(new Date(now)):Reports.dueMonthly(new Date(now));const periods=await this.store.execute('reportMissing',{kind,latest,limit:64});
   for(const key of [...new Set(periods)].sort()){if(left<=0)return;const {start,end,range}=windowOf(kind,key);const material=kind==='daily'?await this.store.execute('dailyEdition',{date:key,start,end}):await this.store.execute('periodEntries',{startDate:range!.start,endDate:range!.end,now});if(!material.entries.length||kind==='daily'&&!Edition.arrangeDaily(material.entries.map(raw=>({...raw,sourceIds:new Set(raw.sourceIds as string[]),mentions:new Set(raw.mentions as string[])})) as unknown as Edition.EditionEntry[]).main.length){await this.store.execute('reportCheck',{kind,key,now});continue;}await this.store.execute('enqueue',{kind:'report',subject:kind+':'+key,key:`report:${epoch}:${kind}:${key}`,epoch,inputRevision:0,configRevision:revision,payload:{kind,key,settings:json(settings)},priority:30,maxAttempts:3,dueAt:now});left--;}
  }
 }
}
function nextMonth(key:string):string{const [year,month]=key.split('-').map(Number);return month===12?`${year!+1}-01`:`${year}-${String(month!+1).padStart(2,'0')}`;}
