/** The pinned UI's presentation contracts are fed only with the native public read projection. */
import type {Publication,UiFeedResult,UiReportResult,HeatEntry,Story} from 'dsh-hotstream-contracts';
import type {FeedItemSummary,TimelineResponse,ReportDetail,ReportCitation,ReportNavigationEntry,HotEntryView,HotStripEntry,TimelineFilters,HeatPoint} from '../contracts/site.ts';
import type {CategoryKey} from '../contracts/taxonomy.ts';
import type {Json} from 'dsh-hotstream-contracts';
const object=(v:Json|undefined):Record<string,Json>=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const iso=(n:number|null)=>n===null?null:new Date(n).toISOString();
export function feedItem(p:Publication,channel:'news'|'x'='news',sameEvent:{id:string;title:string}|null=null):FeedItemSummary{return {id:p.id,title:p.title,summary:p.summary,reason:p.reason,source:{name:p.sourceName},publishedAt:iso(p.publishedAt),timelineAt:iso(p.timelineAt)!,category:p.category as CategoryKey|null,tags:p.tags,score:p.score,selected:p.selected,channel,x:channel==='x'?{authorName:p.sourceName,handle:'',avatarUrl:null,media:[],quoted:null}:null,sameEvent};}
export function timeline(data:UiFeedResult,filters:TimelineFilters,hot:HeatEntry[]=[]):TimelineResponse{return {filters,cards:data.cards.map(card=>({key:card.key,anchorAt:iso(card.anchorAt)!,item:feedItem(card.item,card.channel,card.sameEvent),group:card.group})),dayCounts:Object.fromEntries(data.dayCounts.map(day=>[day.day,day.count])),nextCursor:data.nextCursor,hot:hot.map((entry,index)=>hotStrip(entry,index+1))};}
export function hotStrip(e:HeatEntry,rank:number):HotStripEntry{return {rank,title:e.title,heat:e.heat,trend:e.trend,storyPublicId:e.storyId,itemId:e.representativeItemId,participants:e.sourceNames.map(name=>({name,kind:'editorial',iconUrl:null})),participantCount:e.participants};}
export function hotEntry(e:HeatEntry,rank:number):HotEntryView{return {...hotStrip(e,rank),story:{publicId:e.storyId,title:e.title},trendPct:e.trendPct,badges:e.badges,sourceCount:e.sourceNames.length,sourceNames:e.sourceNames,spark:[],summary:null,latest:null,cover:null};}
export function heatPoints(s:Story):HeatPoint[]{return s.heatSeries.map(p=>({...p,hour:new Date(p.hour).toISOString()}));}
export function reportNavigation(data:UiReportResult):ReportNavigationEntry[]{return data.index.items.map(e=>({key:e.key,title:e.title,issueNumber:e.issueNumber,count:e.count}));}
function citation(raw:Json):ReportCitation {const c=object(raw);return {itemId:typeof c.itemId==='string'?c.itemId:null,title:String(c.title??''),summary:typeof c.summary==='string'?c.summary:null,sourceName:String(c.sourceName??''),sourceUrl:String(c.sourceUrl??''),sourceIconUrl:null,firstParty:c.firstParty===true,publishedAt:typeof c.publishedAt==='string'?c.publishedAt:null,available:typeof c.itemId==='string',...typeof c.sources==='number'?{otherSources:Math.max(0,c.sources-1)}:{},...typeof c.followUp==='string'?{followUp:c.followUp}:{},...Array.isArray(c.related)?{related:c.related.map(citation)}:{}};}
export function reportView(data:UiReportResult):ReportDetail|null {const r=data.report;if(!r)return null;const c=r.content,lead=object(c.lead),sections=(Array.isArray(c.sections)?c.sections:[]).map(raw=>{const s=object(raw);return {label:String(s.label??''),summary:typeof s.intro==='string'?s.intro:null,items:(Array.isArray(s.items)?s.items:[]).map(citation)};});const all=sections.flatMap(s=>s.items),highlightIds=new Set(Array.isArray(c.highlights)?c.highlights:[]);return {kind:r.kind,key:r.key,issueNumber:data.issueNumber??1,title:String(lead.title??r.key),generatedAt:iso(r.createdAt)!,lead:lead.title?{title:String(lead.title),leadParagraph:String(lead.leadParagraph??'')}:null,leadItemId:typeof c.leadItemId==='string'?c.leadItemId:null,overview:typeof c.overview==='string'?c.overview:null,highlights:all.filter(e=>highlightIds.has(e.itemId)),sections,flashes:(Array.isArray(c.flashes)?c.flashes:[]).map(citation),cover:null,metrics:data.metrics,readingMinutes:data.readingMinutes,prev:data.prev,next:data.next};}
