/** Pinned board table/tabs/marks over saved native snapshots. Reading never computes a board. */
import {useMemo,useState} from 'react';
import {Checkbox} from '@deepseek-ai/dsh-client-ui-primitives';
import {Button,Input} from '../../admin/Controls.tsx';
import {HealthBanner} from '../../admin/Integrations.tsx';
import type {Json,OptionalData} from 'dsh-hotstream-contracts';
import type {NewsProps} from '../../NewsPanel.tsx';
import {leaderboardPrice} from '../../leaderboard-prices.ts';
import {leaderboardRecords} from '../../leaderboard-records.ts';
import {OperationsPanel} from '../../NewsPanel.tsx';
import {useNative} from './context.tsx';
import {Link} from './navigation.tsx';
import {BoardTable,SORTS,type SortKey} from '../features/leaderboard/BoardTable.tsx';
import {BoardTabs} from '../features/leaderboard/BoardTabs.tsx';
import {BrandMark} from '../features/leaderboard/BrandMark.tsx';
import {listPrice,pct,score,shortStamp} from '../features/leaderboard/format.ts';
import {Sheet} from '../components/ui/Sheet.tsx';
import {EmptyState,RailSection} from '../components/ui/Page.tsx';
import {Badge} from '../components/ui/Badge.tsx';
import type {LbBoardEntry,LbBrand} from '../contracts/leaderboard.ts';
const obj=(v:Json|undefined):Record<string,Json>=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const str=(v:Json|undefined):string|null=>typeof v==='string'?v:null;
const num=(v:Json|undefined):number|null=>typeof v==='number'&&Number.isFinite(v)?v:null;
const iso=(v:Json|undefined)=>typeof v==='number'?new Date(v).toISOString():str(v);
// Pinned backend/leaderboard/registry.ts: family marks precede provider marks.
const FAMILY_MARKS:Array<[RegExp,string]>=[[/^claude/,'anthropic.svg'],[/^(gemini|gemma)/,'google.svg'],[/^(qwen|qwq)/,'qianwen.svg'],[/^kimi/,'moonshot.svg'],[/^grok/,'xai.svg'],[/^deepseek/,'deepseek.svg'],[/^(hy-|hunyuan)/,'tencent.svg'],[/^(seed|doubao)/,'bytedance.svg'],[/^(glm|chatglm)/,'z-ai.svg'],[/^mimo/,'xiaomi-mimo.svg']];
const PROVIDER_MARKS:Record<string,string>={openai:'openai.svg',meta:'meta.svg',minimax:'minimax.svg',mistral:'mistral.svg',nvidia:'nvidia.svg','z-ai':'z-ai.svg','thinking-machines':'thinking-machines.png'};
function brand(row:Record<string,Json>):LbBrand{const slug=str(row.slug)??String(row.modelId),file=FAMILY_MARKS.find(([r])=>r.test(slug))?.[1]??PROVIDER_MARKS[str(row.providerSlug)??''];return {src:file?'/assets/model-providers/'+file:null,monogram:(str(row.provider)??str(row.name)??'?').replace(/[^\p{L}\p{N}]/gu,'').slice(0,1).toUpperCase(),raster:!!file?.endsWith('.png')};}
export function boardEntries(data:OptionalData):LbBoardEntry[]{
 const fx=num(obj(obj(data.state.summary).fx).rate);
 return leaderboardRecords(data.records).map(row=>{const price=leaderboardPrice(row.price,fx);
 return {rank:num(row.rank)??0,score:num(row.score),sourceCount:num(row.source_count)??0,coverage:num(row.coverage)??0,model:{slug:str(row.slug)??String(row.modelId),name:str(row.name)??'',provider:str(row.provider),releasedAt:iso(row.releasedAt),brand:brand(row)},price,access:{domestic:obj(row.access).domestic===true,weightsUrl:str(obj(row.access).weightsUrl)}};
 });
}
function Sources({data}:{data:OptionalData}){
 const {text}=useNative(),snapshots=Array.isArray(data.state.snapshots)?data.state.snapshots.map(obj):[];
 return <><h2 className="mb-5 text-[22px] font-semibold">{text('来源与覆盖')}</h2>{data.sources.length===0?<EmptyState title={text('尚无快照')}/>:<div className="grid gap-4 md:grid-cols-2">{data.sources.map(source=>{const snap=snapshots.find(s=>s.source_key===source.source),row=source,url=str(snap?.source_url??row.sourceUrl),name=str(snap?.source_name)??String(source.source??'—');return <section key={String(source.source??'unknown')} className="card p-5"><div className="flex justify-between gap-4"><h3 className="text-[16px] font-semibold">{name}</h3><Badge tone={row.status==='ok'?'accent':'amber'}>{text(({ok:'已更新',failed:'更新失败',blocked:'未配置',disabled:'已关闭','waiting-for-evidence':'证据不足',partial:'部分可用'} as Record<string,string>)[String(row.status)]??'待核实')}</Badge></div><p className="mt-3 text-[12px] text-ink-4">{text('最近成功更新')} · {shortStamp(iso(snap?.fetched_at??row.lastOkAt))}</p><p className="mt-2 text-[13px] text-ink-3">{str(snap?.license??row.license)}</p>{row.error&&<p className="mt-3 text-[13px] text-hot" role="alert">{String(row.error)}</p>}{url&&<a className="mt-4 inline-block text-[13px] text-accent" href={url} target="_blank" rel="noopener noreferrer">{text('原文')} →</a>}</section>;})}</div>}</>;
}
function ModelDetail({entry}:{entry:LbBoardEntry}){const {text,state}=useNative();return <><Link to={state.optionalFilter.board==='overall'?'/leaderboard':'/leaderboard/category/'+state.optionalFilter.board} className="text-[13px] text-ink-3">← {text('模型榜')}</Link><div className="my-6 flex items-center gap-4"><BrandMark brand={entry.model.brand} size={48}/><div><h1 className="text-[28px] font-bold">{entry.model.name}</h1><p className="mt-2 text-[13px] text-ink-4">{entry.model.provider} · {entry.model.releasedAt?.slice(0,10)??'—'}</p></div></div><div className="grid gap-8 md:grid-cols-3"><RailSection title={text('相对评分')}><strong className="mono text-[30px]">{score(entry.score)}</strong></RailSection><RailSection title={text('证据覆盖')}><strong className="mono text-[30px]">{pct(entry.coverage)}</strong><p className="mt-2 text-[13px] text-ink-4">{entry.sourceCount} {text('个来源')}</p></RailSection><RailSection title={text('官方价格')}>{entry.price?<><p className="text-[14px]">{text('输入')} {listPrice(entry.price.input,entry.price.currency)} · {text('输出')} {listPrice(entry.price.output,entry.price.currency)} · {text('缓存')} {listPrice(entry.price.cached,entry.price.currency)}</p>{entry.price.verifiedOn&&<p className="mt-2 text-[12px] text-ink-4">{text('价格核验日期')} · {entry.price.verifiedOn}</p>}<p className="mt-2 text-[12px] text-ink-4">{text('每百万 Token')} · {entry.price.note}</p>{entry.price.officialUrl&&<a className="mt-3 block text-accent" href={entry.price.officialUrl} target="_blank" rel="noopener noreferrer">{text('价格来源')}</a>}</>:text('尚无价格记录')}</RailSection></div>{entry.access.weightsUrl&&<a className="mt-6 inline-block text-accent" href={entry.access.weightsUrl} target="_blank" rel="noopener noreferrer">{text('开放权重')} →</a>}</>;}
function PriceEvidence({data}:{data:OptionalData}){const {text}=useNative(),fx=obj(obj(data.state.summary).fx),rate=num(fx.rate),url=str(fx.sourceUrl);return <p className="mb-5 text-[12px] leading-relaxed text-ink-4">{text('价格为标准 API 档位，每百万 Token；缓存为命中价。')}{rate!==null&&rate>0?<> {text('人民币换算')}：1 USD = {rate} CNY · {str(fx.asOf)} · {url?<a href={url} target="_blank" rel="noopener noreferrer" className="text-accent">{str(fx.sourceName)??'Frankfurter'}</a>:str(fx.sourceName)}</>:<> {text('人民币汇率暂不可用；已知美元价格显示为待换算，原价可在模型详情查看。')}</>}</p>;}
export function LeaderboardPage({props}:{props:NewsProps}){
 const {state,face,text}=useNative(),[sort,setSort]=useState<SortKey>('rank'),[dir,setDir]=useState<1|-1>(1),[sortSheet,setSortSheet]=useState(false),[manage,setManage]=useState(false),data=state.optional,health=state.moduleHealth?.leaderboard;
 const entries=useMemo(()=>data?boardEntries(data):[],[data]);if(!data)return <EmptyState title={text('加载中…')}/>;
 const path=state.path.split('?')[0]!,slug=/^\/leaderboard\/([^/]+)$/.exec(path)?.[1],entry=slug?entries.find(e=>e.model.slug===slug):null;
 const content=path==='/leaderboard/sources'?<Sources data={data}/>:path==='/leaderboard/rules'?<section className="max-w-[760px]"><h2 className="mb-5 text-[22px] font-semibold">{text('方法说明')} · {String(data.state.version??'v17')}</h2><p className="prose">{text('榜单使用已保存的来源成绩、固定校准尺度与机构覆盖规则，计算相对排序。分数用于当前榜单内比较，不是模型的通用能力百分比。')}</p><p className="mt-4 text-[14px] text-ink-3">{text('未知成绩与价格保持缺失。美元价格仅在该次计算保存了汇率时换算成人民币。')}</p><Link to="/leaderboard/sources" className="mt-5 inline-block text-accent">{text('来源与覆盖')} →</Link></section>:entry?<ModelDetail entry={entry}/>:<><BoardTabs/><div className="my-5 flex flex-wrap items-center gap-5"><Checkbox checked={state.optionalFilter.domestic} onChange={domestic=>face.setOptionalFilter({domestic})} label={text('国产模型')}/><Checkbox checked={state.optionalFilter.openWeights} onChange={openWeights=>face.setOptionalFilter({openWeights})} label={text('开放权重')}/><Input aria-label={text('搜索模型')} placeholder={text('搜索模型')} value={state.optionalFilter.query} onChange={e=>face.setOptionalFilter({query:e.target.value})}/></div>{entries.length?<BoardTable entries={entries} board={state.optionalFilter.board} sort={sort} dir={dir} onSort={(key,d)=>{setSort(key);setDir(d);}} onSortSheet={()=>setSortSheet(true)}/>:<EmptyState title={health?.status==='failed'?text('榜单更新失败'):data.total?text('暂无符合条件的内容'):text('尚未形成可发布榜单')}/>}<div className="mt-5 flex justify-center gap-4"><Button disabled={!state.offset||state.busy} onClick={()=>face.pageOffset(Math.max(0,state.offset-100))}>{props.t('previousPage')}</Button><span className="text-[13px] text-ink-4">{data.total?state.offset+1:0}–{Math.min(state.offset+100,data.total)} / {data.total}</span><Button disabled={state.offset+100>=data.total||state.busy} onClick={()=>face.pageOffset(state.offset+100)}>{props.t('nextPage')}</Button></div></>;
 return <><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[28px] font-bold">{text('模型榜')}</h1><p className="mt-2 text-[12px] text-ink-4">{text('最近成功更新')} · {shortStamp(iso(data.state.generatedAt))}</p></div><nav className="flex gap-4 text-[13px] text-ink-3"><Link to="/leaderboard/sources">{text('来源与覆盖')}</Link><Link to="/leaderboard/rules">{text('方法说明')}</Link><button onClick={()=>setManage(true)}>{text('筛选与管理')}</button></nav></header><HealthBanner health={health} face={props} title={text('来源更新状态')} actions={<Button disabled={!data.enabled||state.busy||health?.status==='running'||health?.status==='queued'} onClick={()=>{void props.refreshLeaderboard();}}>{text(health?.status==='running'||health?.status==='queued'?'更新中…':'刷新公开来源')}</Button>}/>{!data.enabled&&<div className="well rounded-panel p-5 mb-6"><h2 className="text-[15px] font-semibold">{text('模块已关闭')}</h2><p className="mt-2 text-[13px] text-ink-3">{text('只读历史快照')}</p><Link to="/settings" className="mt-3 inline-block text-accent">{text('设置')} →</Link></div>}<PriceEvidence data={data}/>{content}<Sheet open={sortSheet} onClose={()=>setSortSheet(false)} title={text('排序')}><div className="flex flex-col gap-2">{SORTS.map(s=><button key={s.key} className="p-3 text-left" onClick={()=>{setSort(s.key);setDir(1);setSortSheet(false);}}>{text(s.label)}</button>)}</div></Sheet><Sheet open={manage} onClose={()=>setManage(false)} title={text('筛选与管理')}><OperationsPanel state={state} face={props} section="optional"/></Sheet></>;
}
