/** Source Link/Form hooks backed by the native controller, with no browser history or HTTP loader. */
import {forwardRef,type AnchorHTMLAttributes,type FormHTMLAttributes,type ReactNode} from 'react';
import {routeLocation,useNative} from './context.tsx';
import {scrollToAnchor} from '../components/ui/OutlineSheet.tsx';
export interface LinkProps extends Omit<AnchorHTMLAttributes<HTMLAnchorElement>,'href'> {to:string;prefetch?:string|undefined;viewTransition?:boolean|undefined;replace?:boolean|undefined;preventScrollReset?:boolean|undefined;reloadDocument?:boolean|undefined;}
export const Link=forwardRef<HTMLAnchorElement,LinkProps>(function Link({to,prefetch,viewTransition,replace,preventScrollReset,reloadDocument,onClick,children,...props},ref){const {face,scroll,root}=useNative();const anchor=to.startsWith('#');return <a {...props} ref={ref} href={anchor?to:'#hotstream'+to} data-hotstream-route={anchor?undefined:to} onClick={e=>{onClick?.(e);if(!e.defaultPrevented){e.preventDefault();if(anchor){try{scrollToAnchor(decodeURIComponent(to.slice(1)),root,scroll);}catch{}return;}if(scroll)face.recordScroll(scroll.scrollTop);face.navigateUrl(to,replace);}}}>{children}</a>;});
export function useLocation(){return routeLocation(useNative().state);}
export function useNavigate(){const {face}=useNative();return (to:string|number,options?:{replace?:boolean|undefined;preventScrollReset?:boolean|undefined;viewTransition?:boolean|undefined})=>typeof to==='number'?face.goBack():face.navigateUrl(to,options?.replace);}
export function useNavigation(){const {state}=useNative();return {state:state.busy?'loading':'idle',location:state.busy?routeLocation(state):undefined};}
export function useRevalidator(){const {state,face}=useNative();return {state:state.busy?'loading':'idle',revalidate:async()=>{face.loadNews();}};}
export function useSearchParams():[URLSearchParams,(params:URLSearchParams|Record<string,string>,options?:{replace?:boolean|undefined})=>void]{const {state,face}=useNative(),location=routeLocation(state);return [new URLSearchParams(location.search),(params,options)=>face.navigateUrl(location.pathname+'?'+new URLSearchParams(params).toString(),options?.replace)];}
export function Form({method,action,onSubmit,children,...props}:FormHTMLAttributes<HTMLFormElement>){const {state,face}=useNative();return <form {...props} onSubmit={event=>{event.preventDefault();onSubmit?.(event);const data=new FormData(event.currentTarget),params=new URLSearchParams();for(const [key,value]of data)if(typeof value==='string'&&value)params.append(key,value);face.navigateUrl((action??routeLocation(state).pathname)+'?'+params);}}>{children}</form>;}
export function NavLink({children,className,to,...props}:Omit<LinkProps,'children'|'className'>&{children:ReactNode|((state:{isActive:boolean})=>ReactNode);className?:string|((state:{isActive:boolean})=>string)}){const location=useLocation(),isActive=location.pathname===to;return <Link {...props} to={to} className={typeof className==='function'?className({isActive}):className}>{typeof children==='function'?children({isActive}):children}</Link>;}
