/** DSH Slots supplies every controller/locale prop; source pages live inside one native UI owner. */
import {useEffect,useLayoutEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import type {NewsProps} from '../../NewsPanel.tsx';
import {OperationsPanel} from '../../NewsPanel.tsx';
import {FormNavigationModal} from '../../admin/SettingsPage.tsx';
import {NativeProvider} from './context.tsx';
import {clearSnapshots} from '../lib/restore.ts';
import {setUiLanguage,uiText} from './locale.ts';
import {sourceClasses} from './style.ts';
import {Sidebar} from '../components/shell/Sidebar.tsx';
import {ThemeSwitch} from '../components/shell/ThemeSwitch.tsx';
import {NavigationProgress} from '../components/shell/Chrome.tsx';
import {IconBolt,IconFlame,IconDoc,IconUser,IconArrowLeft} from '../components/icons.tsx';
import {Link} from './navigation.tsx';
import {scrollToAnchor} from '../components/ui/OutlineSheet.tsx';
import {ViewBoundary} from './ViewBoundary.tsx';
import {LeaderboardPage} from './LeaderboardPage.tsx';
import {MonitorPage} from './MonitorPage.tsx';
import {SignalRiver} from '../features/about/SignalRiver.tsx';
import {SearchOverlay} from '../features/search/SearchOverlay.tsx';
import {EmptyState} from '../components/ui/Page.tsx';
import {FeedPage,ReportPage,ArticlePage,HotPage,EventPage,TopicsPage} from './ReadingPages.tsx';
import layout from './Layout.module.css';
import {Button} from '@deepseek-ai/dsh-client-ui-primitives';
const adminItems=[{to:'/admin',label:'概览'},{to:'/admin/sources',label:'信源管理'},{to:'/admin/content',label:'内容与事件'},{to:'/admin/runs',label:'任务与调用'},{to:'/admin/audit',label:'调用审计'},{to:'/admin/selectbench',label:'精选评测'},{to:'/settings',label:'设置'}];
export function SourcePanel(props:NewsProps){
 const state=props.useNews(s=>s),handoff=props.useDiagnostics(s=>s),[root,setRoot]=useState<HTMLDivElement|null>(null),[scroll,setScroll]=useState<HTMLDivElement|null>(null),[height,setHeight]=useState(800);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const restored=useRef<string|null>(null);
 const english=props.t('back')==='Back';setUiLanguage(english);const scheme=state.appearance==='host'?state.hostScheme:state.appearance;
 useEffect(()=>{const stop=props.mountNews();props.refresh();return()=>{stop();if(timer.current)clearTimeout(timer.current);};},[props.mountNews,props.refresh]);
 useEffect(()=>{if(!root)return;const observer=new ResizeObserver(()=>setHeight(root.clientHeight));observer.observe(root);setHeight(root.clientHeight);return()=>observer.disconnect();},[root]);
 useLayoutEffect(()=>{if(scroll&&!state.busy&&state.runtime&&restored.current!==state.routeKey){restored.current=state.routeKey;scroll.scrollTop=state.navigationScroll;}},[scroll,state.busy,state.runtime,state.routeKey,state.navigationScroll]);
 useEffect(()=>{clearSnapshots();},[state.runtime?.state.epoch]);
 const value=useMemo(()=>({state,face:props,scroll,root,scheme,text:uiText}),[state,props,scroll,root,scheme]);
 const management=['sources','settings','admin'].includes(state.page),isReport=['daily','weekly','monthly'].includes(state.page)&&!state.path.startsWith('/items/');
 const content=!state.runtime?<EmptyState title={props.t('uninitializedReading')}/>:!state.runtime.state.initialized?<OperationsPanel state={state} face={props} section="initialize"/>:state.path.startsWith('/items/')?<ArticlePage key={state.path} props={props}/>:state.path.startsWith('/story/')||state.page==='events'?<EventPage/>:['daily','weekly','monthly'].includes(state.page)?<ReportPage props={props}/>:state.page==='hot'?<HotPage/>:state.page==='topics'?<TopicsPage props={props}/>:['selected','all','bookmarks'].includes(state.page)?<FeedPage props={props}/>:management?<OperationsPanel state={state} face={props} section={state.page==='sources'?'sources':state.page==='settings'?'settings':'admin'}/>:state.page==='monitor'?<MonitorPage props={props}/>:state.page==='leaderboard'?<LeaderboardPage props={props}/>:<About props={props}/>;
 return <div ref={setRoot} className={sourceClasses.root} data-hotstream-root="main" data-hotstream-panel="news" data-theme={scheme} lang={english?'en':'zh-CN'} style={{'--hs-height':height+'px'} as CSSProperties}><NativeProvider value={value}><div className={layout.shell}>{management?<AdminSidebar/>:<Sidebar changelogVersion={null}/>}<div ref={setScroll} className={layout.main} data-hotstream-scroll onClickCapture={e=>{const target=e.target instanceof Element?e.target.closest('a'):null,href=target?.getAttribute('href');if(href?.startsWith('#')&&!href.startsWith('#hotstream')){e.preventDefault();try{scrollToAnchor(decodeURIComponent(href.slice(1)),root,scroll);}catch{}}}} onScroll={()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{if(scroll)props.recordScroll(scroll.scrollTop);},250);}}><NavigationProgress active={state.busy}/>{management&&<div className={layout.adminMobileHeader}><div className={layout.adminMobileTop}><ReturnToReading/><ThemeSwitch/></div><nav className={layout.adminMobileNav} aria-label={uiText('管理')}>{adminItems.map(item=><AdminLink key={item.to} {...item}/>)}</nav></div>}{(state.error||handoff.error)&&<div role="alert" className={layout.notice+' '+layout.error}>{state.error??handoff.error}</div>}{handoff.handoffDone&&<div role="status" className={layout.notice}>{props.t('handoffDone')}</div>}<main className={layout.content+(isReport?' '+layout.reportContent:'')}><ViewBoundary>{content}</ViewBoundary></main></div><div className={layout.status}><span>{uiText(state.runtime?.state.settings?.autoCollectEnabled?'自动采集中':'自动采集已暂停')}</span><button onClick={props.loadNews} aria-label={uiText('刷新')}>↻</button></div><nav className={layout.mobileNav} aria-label={props.t('newsTitle')}>{[{path:'/',label:'精选',Icon:IconBolt},{path:'/hot',label:'热点',Icon:IconFlame},{path:'/daily',label:'日报',Icon:IconDoc},{path:'/settings',label:'更多',Icon:IconUser}].map(({path,label,Icon})=><Link key={path} to={path} aria-current={state.path===path?'page':undefined}><Icon size={19}/>{uiText(label)}</Link>)}</nav></div><SearchOverlay/><FormNavigationModal state={state} face={props}/></NativeProvider></div>;
}
function ReturnToReading(){return <Link to="/" className={layout.adminReturn}><IconArrowLeft size={16}/><span>返回阅读</span></Link>;}
function AdminSidebar(){return <aside className={layout.adminNav} aria-label={uiText('管理')}><Link to="/" className={layout.adminBrand} aria-label={uiText('Hotstream 首页')}><IconFlame size={21}/> Hotstream</Link><ReturnToReading/><div className="mb-2 mt-6 px-3 text-[11px] text-ink-4">管理</div>{adminItems.map(item=><AdminLink key={item.to} {...item}/>)}<div className="mt-6 border-t border-line pt-5"><ThemeSwitch/></div></aside>;}
import {useNative} from './context.tsx';
function AdminLink({to,label}:{to:string;label:string}){const {state}=useNative();return <Link to={to} aria-current={state.path===to?'page':undefined}>{label}</Link>;}
function OptionalSurface({props}:{props:NewsProps}){const {state,text,face}=useNative(),on=state.page==='leaderboard'?state.runtime?.state.settings?.features.leaderboard:state.runtime?.state.settings?.features.codexResetMonitor;return <><h1 className="text-[24px] font-semibold mb-5">{props.t(state.page==='leaderboard'?'leaderboardPage':'monitorPage')}</h1>{!on&&<div className="well rounded-panel p-5 mb-6"><h2 className="text-[15px] font-semibold">{text('模块已关闭')}</h2><p className="mt-2 text-[13px] text-ink-3">{text('启用方式见设置')}</p><Link to="/settings" className="mt-3 inline-block text-accent">{text('设置')} →</Link></div>}<OperationsPanel state={state} face={props} section="optional"/></>;}
function About({props}:{props:NewsProps}){const {state,text}=useNative(),[focus,setFocus]=useState<number|null>(null);const sources=useMemo(()=>state.sources.filter(s=>s.enabled).map(s=>({name:s.name,kind:s.kind,heatOnly:s.participationMode==='hot_signal'})),[state.sources]);return <div className="max-w-[1100px] mx-auto"><p className="text-[12px] tracking-[0.2em] font-semibold text-accent">HOTSTREAM · NATIVE DSH</p><h1 className="mt-6 text-[40px] font-bold leading-[1.25] tracking-tight">{props.t('newsTitle')}</h1><p className="mt-4 text-[20px] leading-relaxed text-ink-3">{props.t('aboutInfo')}</p><SignalRiver sources={sources} focus={focus} className="mt-8"/><div className="mt-4 grid grid-cols-4 gap-3 border-b border-line pb-6" aria-label={text('新闻处理流程')}>{['采集','归并','精选','成刊'].map((label,index)=><button key={label} className="text-left text-[14px] text-ink-3 hover:text-accent" onMouseEnter={()=>setFocus(index)} onMouseLeave={()=>setFocus(null)} onFocus={()=>setFocus(index)} onBlur={()=>setFocus(null)}><span className="mono mr-2 text-ink-4">0{index+1}</span>{text(label)}</button>)}</div><div className="mt-10 grid grid-cols-2 lg:grid-cols-4 border-y border-line py-6 gap-6">{[[text('启用信源'),sources.length],[props.t('data'),state.runtime?.state.counts.articles],[props.t('dailyPage')+'/'+props.t('weeklyPage')+'/'+props.t('monthlyPage'),state.runtime?.state.counts.reports],[props.t('eventsPage'),state.runtime?.state.counts.stories]].map(([label,n])=><div key={String(label)}><p className="text-[12px] text-ink-4">{label}</p><p className="mt-2 mono text-[32px] font-bold">{n}</p></div>)}</div><p className="mt-8 text-[14px] leading-[1.85] text-ink-3">{props.t('lifecycleInfo')}</p><p className="mt-4 text-[13px] text-ink-4">{props.t('licenseInfo')}</p><p className="mt-4 text-[12px] text-ink-4">0.1.0-alpha.7 · AIHOT cc66cceb · DSH 0.2.0-rc.2</p></div>;}
